// Code generated by scripts/gen-version-file.sh. DO NOT EDIT.
package version

func init(){
	b := &build_info
	b.Version   = "260702-r0"
	b.GitRev    = "c01b3de933eff401cc9c17318bcf53af11cd57be"
	b.GitDirty  = true
}
