// Code generated by scripts/gen-version-file.sh. DO NOT EDIT.
package version

func init(){
	b := &build_info
	b.Version   = "260701-r0"
	b.GitRev    = "3f043ccc70d7c3acd2b8efdd607f9a2cd679bf9b"
	b.GitDirty  = true
}
