services:
  app:
    image: ghcr.io/lesomnus/gantry:${REVISION:-local}
    command: ["--config", "/gantry.yaml", "serve"]

    network_mode: host
    privileged: true

    volumes:
      - ./gantry.yaml:/gantry.yaml:ro

    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 64M
        reservations:
          cpus: "2"
          memory: 32M
