// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: gantry/event.proto

package pb

import (
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED   EventType = 0
	EventType_EVENT_TYPE_JOB_ADMITTED  EventType = 1
	EventType_EVENT_TYPE_JOB_DONE      EventType = 2
	EventType_EVENT_TYPE_GC_APPLIED    EventType = 3
	EventType_EVENT_TYPE_IMAGE_PULLED  EventType = 4
	EventType_EVENT_TYPE_IMAGE_REMOVED EventType = 5
	EventType_EVENT_TYPE_PINNED        EventType = 6
	EventType_EVENT_TYPE_UNPINNED      EventType = 7
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_JOB_ADMITTED",
		2: "EVENT_TYPE_JOB_DONE",
		3: "EVENT_TYPE_GC_APPLIED",
		4: "EVENT_TYPE_IMAGE_PULLED",
		5: "EVENT_TYPE_IMAGE_REMOVED",
		6: "EVENT_TYPE_PINNED",
		7: "EVENT_TYPE_UNPINNED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":   0,
		"EVENT_TYPE_JOB_ADMITTED":  1,
		"EVENT_TYPE_JOB_DONE":      2,
		"EVENT_TYPE_GC_APPLIED":    3,
		"EVENT_TYPE_IMAGE_PULLED":  4,
		"EVENT_TYPE_IMAGE_REMOVED": 5,
		"EVENT_TYPE_PINNED":        6,
		"EVENT_TYPE_UNPINNED":      7,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_gantry_event_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_gantry_event_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Type-specific payload; which fields are set depends on the event type.
type EventDetail struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Source   string                 `protobuf:"bytes,1,opt,name=source"`
	xxx_hidden_Job      string                 `protobuf:"bytes,2,opt,name=job"`
	xxx_hidden_Bytes    int64                  `protobuf:"varint,3,opt,name=bytes"`
	xxx_hidden_Deleted  int32                  `protobuf:"varint,4,opt,name=deleted"`
	xxx_hidden_Untagged int32                  `protobuf:"varint,5,opt,name=untagged"`
	xxx_hidden_Reaped   int32                  `protobuf:"varint,6,opt,name=reaped"`
	xxx_hidden_Errors   int32                  `protobuf:"varint,7,opt,name=errors"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EventDetail) Reset() {
	*x = EventDetail{}
	mi := &file_gantry_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDetail) ProtoMessage() {}

func (x *EventDetail) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventDetail) GetSource() string {
	if x != nil {
		return x.xxx_hidden_Source
	}
	return ""
}

func (x *EventDetail) GetJob() string {
	if x != nil {
		return x.xxx_hidden_Job
	}
	return ""
}

func (x *EventDetail) GetBytes() int64 {
	if x != nil {
		return x.xxx_hidden_Bytes
	}
	return 0
}

func (x *EventDetail) GetDeleted() int32 {
	if x != nil {
		return x.xxx_hidden_Deleted
	}
	return 0
}

func (x *EventDetail) GetUntagged() int32 {
	if x != nil {
		return x.xxx_hidden_Untagged
	}
	return 0
}

func (x *EventDetail) GetReaped() int32 {
	if x != nil {
		return x.xxx_hidden_Reaped
	}
	return 0
}

func (x *EventDetail) GetErrors() int32 {
	if x != nil {
		return x.xxx_hidden_Errors
	}
	return 0
}

func (x *EventDetail) SetSource(v string) {
	x.xxx_hidden_Source = v
}

func (x *EventDetail) SetJob(v string) {
	x.xxx_hidden_Job = v
}

func (x *EventDetail) SetBytes(v int64) {
	x.xxx_hidden_Bytes = v
}

func (x *EventDetail) SetDeleted(v int32) {
	x.xxx_hidden_Deleted = v
}

func (x *EventDetail) SetUntagged(v int32) {
	x.xxx_hidden_Untagged = v
}

func (x *EventDetail) SetReaped(v int32) {
	x.xxx_hidden_Reaped = v
}

func (x *EventDetail) SetErrors(v int32) {
	x.xxx_hidden_Errors = v
}

type EventDetail_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// job_admitted: the source store.
	Source string
	// job_done: the job id and total bytes moved.
	Job   string
	Bytes int64
	// gc_applied: apply counters.
	Deleted  int32
	Untagged int32
	Reaped   int32
	Errors   int32
}

func (b0 EventDetail_builder) Build() *EventDetail {
	m0 := &EventDetail{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Source = b.Source
	x.xxx_hidden_Job = b.Job
	x.xxx_hidden_Bytes = b.Bytes
	x.xxx_hidden_Deleted = b.Deleted
	x.xxx_hidden_Untagged = b.Untagged
	x.xxx_hidden_Reaped = b.Reaped
	x.xxx_hidden_Errors = b.Errors
	return m0
}

// One entry of the append-only audit log. Written internally by gantry;
// Add/Patch/Erase exist for the contract and for seeding fakes in tests.
// The store is recorded by name (not an edge) so audit entries outlive
// store re-configuration.
type Event struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Seq    uint64                 `protobuf:"varint,1,opt,name=seq"`
	xxx_hidden_At     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=at"`
	xxx_hidden_Type   EventType              `protobuf:"varint,3,opt,name=type,enum=gantry.EventType"`
	xxx_hidden_Store  string                 `protobuf:"bytes,4,opt,name=store"`
	xxx_hidden_Ref    string                 `protobuf:"bytes,5,opt,name=ref"`
	xxx_hidden_State  JobState               `protobuf:"varint,6,opt,name=state,enum=gantry.JobState"`
	xxx_hidden_Digest string                 `protobuf:"bytes,7,opt,name=digest"`
	xxx_hidden_Error  string                 `protobuf:"bytes,8,opt,name=error"`
	xxx_hidden_Detail *EventDetail           `protobuf:"bytes,9,opt,name=detail"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_gantry_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Event) GetSeq() uint64 {
	if x != nil {
		return x.xxx_hidden_Seq
	}
	return 0
}

func (x *Event) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_At
	}
	return nil
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetStore() string {
	if x != nil {
		return x.xxx_hidden_Store
	}
	return ""
}

func (x *Event) GetRef() string {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return ""
}

func (x *Event) GetState() JobState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *Event) GetDigest() string {
	if x != nil {
		return x.xxx_hidden_Digest
	}
	return ""
}

func (x *Event) GetError() string {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return ""
}

func (x *Event) GetDetail() *EventDetail {
	if x != nil {
		return x.xxx_hidden_Detail
	}
	return nil
}

func (x *Event) SetSeq(v uint64) {
	x.xxx_hidden_Seq = v
}

func (x *Event) SetAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_At = v
}

func (x *Event) SetType(v EventType) {
	x.xxx_hidden_Type = v
}

func (x *Event) SetStore(v string) {
	x.xxx_hidden_Store = v
}

func (x *Event) SetRef(v string) {
	x.xxx_hidden_Ref = v
}

func (x *Event) SetState(v JobState) {
	x.xxx_hidden_State = v
}

func (x *Event) SetDigest(v string) {
	x.xxx_hidden_Digest = v
}

func (x *Event) SetError(v string) {
	x.xxx_hidden_Error = v
}

func (x *Event) SetDetail(v *EventDetail) {
	x.xxx_hidden_Detail = v
}

func (x *Event) HasAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_At != nil
}

func (x *Event) HasDetail() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Detail != nil
}

func (x *Event) ClearAt() {
	x.xxx_hidden_At = nil
}

func (x *Event) ClearDetail() {
	x.xxx_hidden_Detail = nil
}

type Event_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Assigned from the log's monotonic sequence.
	Seq   uint64
	At    *timestamppb.Timestamp
	Type  EventType
	Store string
	// Image reference; a pin value for pinned/unpinned, an image ID for
	// untagged reaps.
	Ref string
	// Terminal job state, on job_done.
	State JobState
	// Verified source digest, on job_admitted.
	Digest string
	// Failure text, on job_done of a failed job.
	Error  string
	Detail *EventDetail
}

func (b0 Event_builder) Build() *Event {
	m0 := &Event{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Seq = b.Seq
	x.xxx_hidden_At = b.At
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Store = b.Store
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_State = b.State
	x.xxx_hidden_Digest = b.Digest
	x.xxx_hidden_Error = b.Error
	x.xxx_hidden_Detail = b.Detail
	return m0
}

var File_gantry_event_proto protoreflect.FileDescriptor

const file_gantry_event_proto_rawDesc = "" +
	"\n" +
	"\x12gantry/event.proto\x12\x06gantry\x1a\x10gantry/job.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\torm.proto\"\xb3\x01\n" +
	"\vEventDetail\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x10\n" +
	"\x03job\x18\x02 \x01(\tR\x03job\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\x03R\x05bytes\x12\x18\n" +
	"\adeleted\x18\x04 \x01(\x05R\adeleted\x12\x1a\n" +
	"\buntagged\x18\x05 \x01(\x05R\buntagged\x12\x16\n" +
	"\x06reaped\x18\x06 \x01(\x05R\x06reaped\x12\x16\n" +
	"\x06errors\x18\a \x01(\x05R\x06errors\"\xec\x02\n" +
	"\x05Event\x12\x1b\n" +
	"\x03seq\x18\x01 \x01(\x04B\t\xea\x82\x16\x05(\x01\x82\x01\x00R\x03seq\x122\n" +
	"\x02at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xea\x82\x16\x02@\x01R\x02at\x12-\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.gantry.EventTypeB\x06\xea\x82\x16\x02@\x01R\x04type\x12\x1c\n" +
	"\x05store\x18\x04 \x01(\tB\x06\xea\x82\x16\x02@\x01R\x05store\x12\x18\n" +
	"\x03ref\x18\x05 \x01(\tB\x06\xea\x82\x16\x02@\x01R\x03ref\x12.\n" +
	"\x05state\x18\x06 \x01(\x0e2\x10.gantry.JobStateB\x06\xea\x82\x16\x02@\x01R\x05state\x12\x1e\n" +
	"\x06digest\x18\a \x01(\tB\x06\xea\x82\x16\x02@\x01R\x06digest\x12\x1c\n" +
	"\x05error\x18\b \x01(\tB\x06\xea\x82\x16\x02@\x01R\x05error\x123\n" +
	"\x06detail\x18\t \x01(\v2\x13.gantry.EventDetailB\x06\xea\x82\x16\x02@\x01R\x06detail:\b\xca\xfc\x15\x04\x12\x02\x10\x01*\xe3\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EVENT_TYPE_JOB_ADMITTED\x10\x01\x12\x17\n" +
	"\x13EVENT_TYPE_JOB_DONE\x10\x02\x12\x19\n" +
	"\x15EVENT_TYPE_GC_APPLIED\x10\x03\x12\x1b\n" +
	"\x17EVENT_TYPE_IMAGE_PULLED\x10\x04\x12\x1c\n" +
	"\x18EVENT_TYPE_IMAGE_REMOVED\x10\x05\x12\x15\n" +
	"\x11EVENT_TYPE_PINNED\x10\x06\x12\x17\n" +
	"\x13EVENT_TYPE_UNPINNED\x10\aB$Z\x1dgithub.com/lesomnus/gantry/pb\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_gantry_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gantry_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gantry_event_proto_goTypes = []any{
	(EventType)(0),                // 0: gantry.EventType
	(*EventDetail)(nil),           // 1: gantry.EventDetail
	(*Event)(nil),                 // 2: gantry.Event
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(JobState)(0),                 // 4: gantry.JobState
}
var file_gantry_event_proto_depIdxs = []int32{
	3, // 0: gantry.Event.at:type_name -> google.protobuf.Timestamp
	0, // 1: gantry.Event.type:type_name -> gantry.EventType
	4, // 2: gantry.Event.state:type_name -> gantry.JobState
	1, // 3: gantry.Event.detail:type_name -> gantry.EventDetail
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gantry_event_proto_init() }
func file_gantry_event_proto_init() {
	if File_gantry_event_proto != nil {
		return
	}
	file_gantry_job_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gantry_event_proto_rawDesc), len(file_gantry_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gantry_event_proto_goTypes,
		DependencyIndexes: file_gantry_event_proto_depIdxs,
		EnumInfos:         file_gantry_event_proto_enumTypes,
		MessageInfos:      file_gantry_event_proto_msgTypes,
	}.Build()
	File_gantry_event_proto = out.File
	file_gantry_event_proto_goTypes = nil
	file_gantry_event_proto_depIdxs = nil
}
