// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: gantry/event_svc.g.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventAddRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Seq         uint64                 `protobuf:"varint,1,opt,name=seq"`
	xxx_hidden_At          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=at"`
	xxx_hidden_Type        EventType              `protobuf:"varint,3,opt,name=type,enum=gantry.EventType"`
	xxx_hidden_Store       string                 `protobuf:"bytes,4,opt,name=store"`
	xxx_hidden_Ref         string                 `protobuf:"bytes,5,opt,name=ref"`
	xxx_hidden_State       JobState               `protobuf:"varint,6,opt,name=state,enum=gantry.JobState"`
	xxx_hidden_Digest      string                 `protobuf:"bytes,7,opt,name=digest"`
	xxx_hidden_Error       string                 `protobuf:"bytes,8,opt,name=error"`
	xxx_hidden_Detail      *EventDetail           `protobuf:"bytes,9,opt,name=detail"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EventAddRequest) Reset() {
	*x = EventAddRequest{}
	mi := &file_gantry_event_svc_g_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAddRequest) ProtoMessage() {}

func (x *EventAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_event_svc_g_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventAddRequest) GetSeq() uint64 {
	if x != nil {
		return x.xxx_hidden_Seq
	}
	return 0
}

func (x *EventAddRequest) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_At
	}
	return nil
}

func (x *EventAddRequest) GetType() EventType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *EventAddRequest) GetStore() string {
	if x != nil {
		return x.xxx_hidden_Store
	}
	return ""
}

func (x *EventAddRequest) GetRef() string {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return ""
}

func (x *EventAddRequest) GetState() JobState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *EventAddRequest) GetDigest() string {
	if x != nil {
		return x.xxx_hidden_Digest
	}
	return ""
}

func (x *EventAddRequest) GetError() string {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return ""
}

func (x *EventAddRequest) GetDetail() *EventDetail {
	if x != nil {
		return x.xxx_hidden_Detail
	}
	return nil
}

func (x *EventAddRequest) SetSeq(v uint64) {
	x.xxx_hidden_Seq = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 9)
}

func (x *EventAddRequest) SetAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_At = v
}

func (x *EventAddRequest) SetType(v EventType) {
	x.xxx_hidden_Type = v
}

func (x *EventAddRequest) SetStore(v string) {
	x.xxx_hidden_Store = v
}

func (x *EventAddRequest) SetRef(v string) {
	x.xxx_hidden_Ref = v
}

func (x *EventAddRequest) SetState(v JobState) {
	x.xxx_hidden_State = v
}

func (x *EventAddRequest) SetDigest(v string) {
	x.xxx_hidden_Digest = v
}

func (x *EventAddRequest) SetError(v string) {
	x.xxx_hidden_Error = v
}

func (x *EventAddRequest) SetDetail(v *EventDetail) {
	x.xxx_hidden_Detail = v
}

func (x *EventAddRequest) HasSeq() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *EventAddRequest) HasAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_At != nil
}

func (x *EventAddRequest) HasDetail() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Detail != nil
}

func (x *EventAddRequest) ClearSeq() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Seq = 0
}

func (x *EventAddRequest) ClearAt() {
	x.xxx_hidden_At = nil
}

func (x *EventAddRequest) ClearDetail() {
	x.xxx_hidden_Detail = nil
}

type EventAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Seq    *uint64
	At     *timestamppb.Timestamp
	Type   EventType
	Store  string
	Ref    string
	State  JobState
	Digest string
	Error  string
	Detail *EventDetail
}

func (b0 EventAddRequest_builder) Build() *EventAddRequest {
	m0 := &EventAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Seq != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 9)
		x.xxx_hidden_Seq = *b.Seq
	}
	x.xxx_hidden_At = b.At
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Store = b.Store
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_State = b.State
	x.xxx_hidden_Digest = b.Digest
	x.xxx_hidden_Error = b.Error
	x.xxx_hidden_Detail = b.Detail
	return m0
}

type EventGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *EventRef              `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *EventSelect           `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EventGetRequest) Reset() {
	*x = EventGetRequest{}
	mi := &file_gantry_event_svc_g_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventGetRequest) ProtoMessage() {}

func (x *EventGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_event_svc_g_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventGetRequest) GetRef() *EventRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *EventGetRequest) GetSelect() *EventSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *EventGetRequest) SetRef(v *EventRef) {
	x.xxx_hidden_Ref = v
}

func (x *EventGetRequest) SetSelect(v *EventSelect) {
	x.xxx_hidden_Select = v
}

func (x *EventGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *EventGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *EventGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *EventGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type EventGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *EventRef
	Select *EventSelect
}

func (b0 EventGetRequest_builder) Build() *EventGetRequest {
	m0 := &EventGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type EventRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isEventRef_Key         `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventRef) Reset() {
	*x = EventRef{}
	mi := &file_gantry_event_svc_g_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRef) ProtoMessage() {}

func (x *EventRef) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_event_svc_g_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventRef) GetSeq() uint64 {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*eventRef_Seq); ok {
			return x.Seq
		}
	}
	return 0
}

func (x *EventRef) SetSeq(v uint64) {
	x.xxx_hidden_Key = &eventRef_Seq{v}
}

func (x *EventRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *EventRef) HasSeq() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*eventRef_Seq)
	return ok
}

func (x *EventRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *EventRef) ClearSeq() {
	if _, ok := x.xxx_hidden_Key.(*eventRef_Seq); ok {
		x.xxx_hidden_Key = nil
	}
}

const EventRef_Key_not_set_case case_EventRef_Key = 0
const EventRef_Seq_case case_EventRef_Key = 1

func (x *EventRef) WhichKey() case_EventRef_Key {
	if x == nil {
		return EventRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *eventRef_Seq:
		return EventRef_Seq_case
	default:
		return EventRef_Key_not_set_case
	}
}

type EventRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Seq *uint64
	// -- end of xxx_hidden_Key
}

func (b0 EventRef_builder) Build() *EventRef {
	m0 := &EventRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Seq != nil {
		x.xxx_hidden_Key = &eventRef_Seq{*b.Seq}
	}
	return m0
}

type case_EventRef_Key protoreflect.FieldNumber

func (x case_EventRef_Key) String() string {
	md := file_gantry_event_svc_g_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isEventRef_Key interface {
	isEventRef_Key()
}

type eventRef_Seq struct {
	Seq uint64 `protobuf:"varint,1,opt,name=seq,oneof"`
}

func (*eventRef_Seq) isEventRef_Key() {}

type EventSelect struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All         bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_At          bool                   `protobuf:"varint,2,opt,name=at"`
	xxx_hidden_Type        bool                   `protobuf:"varint,3,opt,name=type"`
	xxx_hidden_Store       bool                   `protobuf:"varint,4,opt,name=store"`
	xxx_hidden_Ref         bool                   `protobuf:"varint,5,opt,name=ref"`
	xxx_hidden_State       bool                   `protobuf:"varint,6,opt,name=state"`
	xxx_hidden_Digest      bool                   `protobuf:"varint,7,opt,name=digest"`
	xxx_hidden_Error       bool                   `protobuf:"varint,8,opt,name=error"`
	xxx_hidden_Detail      bool                   `protobuf:"varint,9,opt,name=detail"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EventSelect) Reset() {
	*x = EventSelect{}
	mi := &file_gantry_event_svc_g_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSelect) ProtoMessage() {}

func (x *EventSelect) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_event_svc_g_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *EventSelect) GetAt() bool {
	if x != nil {
		return x.xxx_hidden_At
	}
	return false
}

func (x *EventSelect) GetType() bool {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return false
}

func (x *EventSelect) GetStore() bool {
	if x != nil {
		return x.xxx_hidden_Store
	}
	return false
}

func (x *EventSelect) GetRef() bool {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return false
}

func (x *EventSelect) GetState() bool {
	if x != nil {
		return x.xxx_hidden_State
	}
	return false
}

func (x *EventSelect) GetDigest() bool {
	if x != nil {
		return x.xxx_hidden_Digest
	}
	return false
}

func (x *EventSelect) GetError() bool {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return false
}

func (x *EventSelect) GetDetail() bool {
	if x != nil {
		return x.xxx_hidden_Detail
	}
	return false
}

func (x *EventSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 9)
}

func (x *EventSelect) SetAt(v bool) {
	x.xxx_hidden_At = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *EventSelect) SetType(v bool) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *EventSelect) SetStore(v bool) {
	x.xxx_hidden_Store = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 9)
}

func (x *EventSelect) SetRef(v bool) {
	x.xxx_hidden_Ref = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *EventSelect) SetState(v bool) {
	x.xxx_hidden_State = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *EventSelect) SetDigest(v bool) {
	x.xxx_hidden_Digest = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *EventSelect) SetError(v bool) {
	x.xxx_hidden_Error = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 9)
}

func (x *EventSelect) SetDetail(v bool) {
	x.xxx_hidden_Detail = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 9)
}

func (x *EventSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *EventSelect) HasAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *EventSelect) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *EventSelect) HasStore() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *EventSelect) HasRef() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *EventSelect) HasState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *EventSelect) HasDigest() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *EventSelect) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *EventSelect) HasDetail() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *EventSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *EventSelect) ClearAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_At = false
}

func (x *EventSelect) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Type = false
}

func (x *EventSelect) ClearStore() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Store = false
}

func (x *EventSelect) ClearRef() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Ref = false
}

func (x *EventSelect) ClearState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_State = false
}

func (x *EventSelect) ClearDigest() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Digest = false
}

func (x *EventSelect) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Error = false
}

func (x *EventSelect) ClearDetail() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Detail = false
}

type EventSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All    *bool
	At     *bool
	Type   *bool
	Store  *bool
	Ref    *bool
	State  *bool
	Digest *bool
	Error  *bool
	Detail *bool
}

func (b0 EventSelect_builder) Build() *EventSelect {
	m0 := &EventSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 9)
		x.xxx_hidden_All = *b.All
	}
	if b.At != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_At = *b.At
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Store != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 9)
		x.xxx_hidden_Store = *b.Store
	}
	if b.Ref != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_Ref = *b.Ref
	}
	if b.State != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_State = *b.State
	}
	if b.Digest != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_Digest = *b.Digest
	}
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 9)
		x.xxx_hidden_Error = *b.Error
	}
	if b.Detail != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 9)
		x.xxx_hidden_Detail = *b.Detail
	}
	return m0
}

type EventPatchRequest struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref *EventRef              `protobuf:"bytes,1,opt,name=ref"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventPatchRequest) Reset() {
	*x = EventPatchRequest{}
	mi := &file_gantry_event_svc_g_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventPatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventPatchRequest) ProtoMessage() {}

func (x *EventPatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_event_svc_g_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventPatchRequest) GetRef() *EventRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *EventPatchRequest) SetRef(v *EventRef) {
	x.xxx_hidden_Ref = v
}

func (x *EventPatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *EventPatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

type EventPatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref *EventRef
}

func (b0 EventPatchRequest_builder) Build() *EventPatchRequest {
	m0 := &EventPatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	return m0
}

type EventListRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type        EventType              `protobuf:"varint,1,opt,name=type,enum=gantry.EventType"`
	xxx_hidden_Store       *string                `protobuf:"bytes,2,opt,name=store"`
	xxx_hidden_Ref         *string                `protobuf:"bytes,3,opt,name=ref"`
	xxx_hidden_State       JobState               `protobuf:"varint,4,opt,name=state,enum=gantry.JobState"`
	xxx_hidden_Since       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=since"`
	xxx_hidden_PageSize    int32                  `protobuf:"varint,10,opt,name=page_size,json=pageSize"`
	xxx_hidden_PageToken   *string                `protobuf:"bytes,11,opt,name=page_token,json=pageToken"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EventListRequest) Reset() {
	*x = EventListRequest{}
	mi := &file_gantry_event_svc_g_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventListRequest) ProtoMessage() {}

func (x *EventListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_event_svc_g_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventListRequest) GetType() EventType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Type
		}
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *EventListRequest) GetStore() string {
	if x != nil {
		if x.xxx_hidden_Store != nil {
			return *x.xxx_hidden_Store
		}
		return ""
	}
	return ""
}

func (x *EventListRequest) GetRef() string {
	if x != nil {
		if x.xxx_hidden_Ref != nil {
			return *x.xxx_hidden_Ref
		}
		return ""
	}
	return ""
}

func (x *EventListRequest) GetState() JobState {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_State
		}
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *EventListRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Since
	}
	return nil
}

func (x *EventListRequest) GetPageSize() int32 {
	if x != nil {
		return x.xxx_hidden_PageSize
	}
	return 0
}

func (x *EventListRequest) GetPageToken() string {
	if x != nil {
		if x.xxx_hidden_PageToken != nil {
			return *x.xxx_hidden_PageToken
		}
		return ""
	}
	return ""
}

func (x *EventListRequest) SetType(v EventType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *EventListRequest) SetStore(v string) {
	x.xxx_hidden_Store = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *EventListRequest) SetRef(v string) {
	x.xxx_hidden_Ref = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *EventListRequest) SetState(v JobState) {
	x.xxx_hidden_State = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *EventListRequest) SetSince(v *timestamppb.Timestamp) {
	x.xxx_hidden_Since = v
}

func (x *EventListRequest) SetPageSize(v int32) {
	x.xxx_hidden_PageSize = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *EventListRequest) SetPageToken(v string) {
	x.xxx_hidden_PageToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *EventListRequest) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *EventListRequest) HasStore() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *EventListRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *EventListRequest) HasState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *EventListRequest) HasSince() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Since != nil
}

func (x *EventListRequest) HasPageSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *EventListRequest) HasPageToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *EventListRequest) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *EventListRequest) ClearStore() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Store = nil
}

func (x *EventListRequest) ClearRef() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Ref = nil
}

func (x *EventListRequest) ClearState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_State = JobState_JOB_STATE_UNSPECIFIED
}

func (x *EventListRequest) ClearSince() {
	x.xxx_hidden_Since = nil
}

func (x *EventListRequest) ClearPageSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_PageSize = 0
}

func (x *EventListRequest) ClearPageToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_PageToken = nil
}

type EventListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type  *EventType
	Store *string
	Ref   *string
	// Terminal job state, for job_done events.
	State *JobState
	// Events recorded at or after this instant.
	Since     *timestamppb.Timestamp
	PageSize  *int32
	PageToken *string
}

func (b0 EventListRequest_builder) Build() *EventListRequest {
	m0 := &EventListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Store != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Store = b.Store
	}
	if b.Ref != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Ref = b.Ref
	}
	if b.State != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_State = *b.State
	}
	x.xxx_hidden_Since = b.Since
	if b.PageSize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_PageSize = *b.PageSize
	}
	if b.PageToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_PageToken = b.PageToken
	}
	return m0
}

type EventListResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items         *[]*Event              `protobuf:"bytes,1,rep,name=items"`
	xxx_hidden_NextPageToken *string                `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *EventListResponse) Reset() {
	*x = EventListResponse{}
	mi := &file_gantry_event_svc_g_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventListResponse) ProtoMessage() {}

func (x *EventListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_event_svc_g_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventListResponse) GetItems() []*Event {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *EventListResponse) GetNextPageToken() string {
	if x != nil {
		if x.xxx_hidden_NextPageToken != nil {
			return *x.xxx_hidden_NextPageToken
		}
		return ""
	}
	return ""
}

func (x *EventListResponse) SetItems(v []*Event) {
	x.xxx_hidden_Items = &v
}

func (x *EventListResponse) SetNextPageToken(v string) {
	x.xxx_hidden_NextPageToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *EventListResponse) HasNextPageToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *EventListResponse) ClearNextPageToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NextPageToken = nil
}

type EventListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items         []*Event
	NextPageToken *string
}

func (b0 EventListResponse_builder) Build() *EventListResponse {
	m0 := &EventListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	if b.NextPageToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_NextPageToken = b.NextPageToken
	}
	return m0
}

var File_gantry_event_svc_g_proto protoreflect.FileDescriptor

const file_gantry_event_svc_g_proto_rawDesc = "" +
	"\n" +
	"\x18gantry/event_svc.g.proto\x12\x06gantry\x1a\x12gantry/event.proto\x1a\x10gantry/job.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcb\x02\n" +
	"\x0fEventAddRequest\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12*\n" +
	"\x02at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.gantry.EventTypeB\x05\xaa\x01\x02\b\x02R\x04type\x12\x1b\n" +
	"\x05store\x18\x04 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05store\x12\x17\n" +
	"\x03ref\x18\x05 \x01(\tB\x05\xaa\x01\x02\b\x02R\x03ref\x12-\n" +
	"\x05state\x18\x06 \x01(\x0e2\x10.gantry.JobStateB\x05\xaa\x01\x02\b\x02R\x05state\x12\x1d\n" +
	"\x06digest\x18\a \x01(\tB\x05\xaa\x01\x02\b\x02R\x06digest\x12\x1b\n" +
	"\x05error\x18\b \x01(\tB\x05\xaa\x01\x02\b\x02R\x05error\x12+\n" +
	"\x06detail\x18\t \x01(\v2\x13.gantry.EventDetailR\x06detail\"b\n" +
	"\x0fEventGetRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.gantry.EventRefR\x03ref\x12+\n" +
	"\x06select\x18\x02 \x01(\v2\x13.gantry.EventSelectR\x06select\"%\n" +
	"\bEventRef\x12\x12\n" +
	"\x03seq\x18\x01 \x01(\x04H\x00R\x03seqB\x05\n" +
	"\x03key\"\xc7\x01\n" +
	"\vEventSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x0e\n" +
	"\x02at\x18\x02 \x01(\bR\x02at\x12\x12\n" +
	"\x04type\x18\x03 \x01(\bR\x04type\x12\x14\n" +
	"\x05store\x18\x04 \x01(\bR\x05store\x12\x10\n" +
	"\x03ref\x18\x05 \x01(\bR\x03ref\x12\x14\n" +
	"\x05state\x18\x06 \x01(\bR\x05state\x12\x16\n" +
	"\x06digest\x18\a \x01(\bR\x06digest\x12\x14\n" +
	"\x05error\x18\b \x01(\bR\x05error\x12\x16\n" +
	"\x06detail\x18\t \x01(\bR\x06detail\"7\n" +
	"\x11EventPatchRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.gantry.EventRefR\x03ref\"\xf7\x01\n" +
	"\x10EventListRequest\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.gantry.EventTypeR\x04type\x12\x14\n" +
	"\x05store\x18\x02 \x01(\tR\x05store\x12\x10\n" +
	"\x03ref\x18\x03 \x01(\tR\x03ref\x12&\n" +
	"\x05state\x18\x04 \x01(\x0e2\x10.gantry.JobStateR\x05state\x120\n" +
	"\x05since\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\v \x01(\tR\tpageToken\"`\n" +
	"\x11EventListResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.gantry.EventR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\x8f\x02\n" +
	"\fEventService\x12-\n" +
	"\x03Add\x12\x17.gantry.EventAddRequest\x1a\r.gantry.Event\x12-\n" +
	"\x03Get\x12\x17.gantry.EventGetRequest\x1a\r.gantry.Event\x121\n" +
	"\x05Patch\x12\x19.gantry.EventPatchRequest\x1a\r.gantry.Event\x121\n" +
	"\x05Erase\x12\x10.gantry.EventRef\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\x04List\x12\x18.gantry.EventListRequest\x1a\x19.gantry.EventListResponseB\x1fZ\x1dgithub.com/lesomnus/gantry/pbb\beditionsp\xe8\a"

var file_gantry_event_svc_g_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gantry_event_svc_g_proto_goTypes = []any{
	(*EventAddRequest)(nil),       // 0: gantry.EventAddRequest
	(*EventGetRequest)(nil),       // 1: gantry.EventGetRequest
	(*EventRef)(nil),              // 2: gantry.EventRef
	(*EventSelect)(nil),           // 3: gantry.EventSelect
	(*EventPatchRequest)(nil),     // 4: gantry.EventPatchRequest
	(*EventListRequest)(nil),      // 5: gantry.EventListRequest
	(*EventListResponse)(nil),     // 6: gantry.EventListResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(EventType)(0),                // 8: gantry.EventType
	(JobState)(0),                 // 9: gantry.JobState
	(*EventDetail)(nil),           // 10: gantry.EventDetail
	(*Event)(nil),                 // 11: gantry.Event
	(*emptypb.Empty)(nil),         // 12: google.protobuf.Empty
}
var file_gantry_event_svc_g_proto_depIdxs = []int32{
	7,  // 0: gantry.EventAddRequest.at:type_name -> google.protobuf.Timestamp
	8,  // 1: gantry.EventAddRequest.type:type_name -> gantry.EventType
	9,  // 2: gantry.EventAddRequest.state:type_name -> gantry.JobState
	10, // 3: gantry.EventAddRequest.detail:type_name -> gantry.EventDetail
	2,  // 4: gantry.EventGetRequest.ref:type_name -> gantry.EventRef
	3,  // 5: gantry.EventGetRequest.select:type_name -> gantry.EventSelect
	2,  // 6: gantry.EventPatchRequest.ref:type_name -> gantry.EventRef
	8,  // 7: gantry.EventListRequest.type:type_name -> gantry.EventType
	9,  // 8: gantry.EventListRequest.state:type_name -> gantry.JobState
	7,  // 9: gantry.EventListRequest.since:type_name -> google.protobuf.Timestamp
	11, // 10: gantry.EventListResponse.items:type_name -> gantry.Event
	0,  // 11: gantry.EventService.Add:input_type -> gantry.EventAddRequest
	1,  // 12: gantry.EventService.Get:input_type -> gantry.EventGetRequest
	4,  // 13: gantry.EventService.Patch:input_type -> gantry.EventPatchRequest
	2,  // 14: gantry.EventService.Erase:input_type -> gantry.EventRef
	5,  // 15: gantry.EventService.List:input_type -> gantry.EventListRequest
	11, // 16: gantry.EventService.Add:output_type -> gantry.Event
	11, // 17: gantry.EventService.Get:output_type -> gantry.Event
	11, // 18: gantry.EventService.Patch:output_type -> gantry.Event
	12, // 19: gantry.EventService.Erase:output_type -> google.protobuf.Empty
	6,  // 20: gantry.EventService.List:output_type -> gantry.EventListResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_gantry_event_svc_g_proto_init() }
func file_gantry_event_svc_g_proto_init() {
	if File_gantry_event_svc_g_proto != nil {
		return
	}
	file_gantry_event_proto_init()
	file_gantry_job_proto_init()
	file_gantry_event_svc_g_proto_msgTypes[2].OneofWrappers = []any{
		(*eventRef_Seq)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gantry_event_svc_g_proto_rawDesc), len(file_gantry_event_svc_g_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gantry_event_svc_g_proto_goTypes,
		DependencyIndexes: file_gantry_event_svc_g_proto_depIdxs,
		MessageInfos:      file_gantry_event_svc_g_proto_msgTypes,
	}.Build()
	File_gantry_event_svc_g_proto = out.File
	file_gantry_event_svc_g_proto_goTypes = nil
	file_gantry_event_svc_g_proto_depIdxs = nil
}
