// Retention GC types, referenced by the StoreService GC RPCs (see
// proto.svc/gantry/store_svc.proto). Types only — the RPCs live on
// StoreService since GC is bound to a store.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: gantry/gc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GcDeleteReason int32

const (
	GcDeleteReason_GC_DELETE_REASON_UNSPECIFIED    GcDeleteReason = 0
	GcDeleteReason_GC_DELETE_REASON_AGE_EXCEEDED   GcDeleteReason = 1
	GcDeleteReason_GC_DELETE_REASON_MAX_N_EXCEEDED GcDeleteReason = 2
	GcDeleteReason_GC_DELETE_REASON_UNTAGGED       GcDeleteReason = 3
)

// Enum value maps for GcDeleteReason.
var (
	GcDeleteReason_name = map[int32]string{
		0: "GC_DELETE_REASON_UNSPECIFIED",
		1: "GC_DELETE_REASON_AGE_EXCEEDED",
		2: "GC_DELETE_REASON_MAX_N_EXCEEDED",
		3: "GC_DELETE_REASON_UNTAGGED",
	}
	GcDeleteReason_value = map[string]int32{
		"GC_DELETE_REASON_UNSPECIFIED":    0,
		"GC_DELETE_REASON_AGE_EXCEEDED":   1,
		"GC_DELETE_REASON_MAX_N_EXCEEDED": 2,
		"GC_DELETE_REASON_UNTAGGED":       3,
	}
)

func (x GcDeleteReason) Enum() *GcDeleteReason {
	p := new(GcDeleteReason)
	*p = x
	return p
}

func (x GcDeleteReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GcDeleteReason) Descriptor() protoreflect.EnumDescriptor {
	return file_gantry_gc_proto_enumTypes[0].Descriptor()
}

func (GcDeleteReason) Type() protoreflect.EnumType {
	return &file_gantry_gc_proto_enumTypes[0]
}

func (x GcDeleteReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type GcKeepReason int32

const (
	GcKeepReason_GC_KEEP_REASON_UNSPECIFIED     GcKeepReason = 0
	GcKeepReason_GC_KEEP_REASON_IN_USE          GcKeepReason = 1
	GcKeepReason_GC_KEEP_REASON_PINNED          GcKeepReason = 2
	GcKeepReason_GC_KEEP_REASON_KEEP_N_RECENT   GcKeepReason = 3
	GcKeepReason_GC_KEEP_REASON_WITHIN_MAX_AGE  GcKeepReason = 4
	GcKeepReason_GC_KEEP_REASON_GRACE           GcKeepReason = 5
	GcKeepReason_GC_KEEP_REASON_AGE_GC_DISABLED GcKeepReason = 6
	GcKeepReason_GC_KEEP_REASON_UNMANAGED       GcKeepReason = 7
	GcKeepReason_GC_KEEP_REASON_UNTAGGED_GRACE  GcKeepReason = 8
	GcKeepReason_GC_KEEP_REASON_DIGEST_TRACKED  GcKeepReason = 9
)

// Enum value maps for GcKeepReason.
var (
	GcKeepReason_name = map[int32]string{
		0: "GC_KEEP_REASON_UNSPECIFIED",
		1: "GC_KEEP_REASON_IN_USE",
		2: "GC_KEEP_REASON_PINNED",
		3: "GC_KEEP_REASON_KEEP_N_RECENT",
		4: "GC_KEEP_REASON_WITHIN_MAX_AGE",
		5: "GC_KEEP_REASON_GRACE",
		6: "GC_KEEP_REASON_AGE_GC_DISABLED",
		7: "GC_KEEP_REASON_UNMANAGED",
		8: "GC_KEEP_REASON_UNTAGGED_GRACE",
		9: "GC_KEEP_REASON_DIGEST_TRACKED",
	}
	GcKeepReason_value = map[string]int32{
		"GC_KEEP_REASON_UNSPECIFIED":     0,
		"GC_KEEP_REASON_IN_USE":          1,
		"GC_KEEP_REASON_PINNED":          2,
		"GC_KEEP_REASON_KEEP_N_RECENT":   3,
		"GC_KEEP_REASON_WITHIN_MAX_AGE":  4,
		"GC_KEEP_REASON_GRACE":           5,
		"GC_KEEP_REASON_AGE_GC_DISABLED": 6,
		"GC_KEEP_REASON_UNMANAGED":       7,
		"GC_KEEP_REASON_UNTAGGED_GRACE":  8,
		"GC_KEEP_REASON_DIGEST_TRACKED":  9,
	}
)

func (x GcKeepReason) Enum() *GcKeepReason {
	p := new(GcKeepReason)
	*p = x
	return p
}

func (x GcKeepReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GcKeepReason) Descriptor() protoreflect.EnumDescriptor {
	return file_gantry_gc_proto_enumTypes[1].Descriptor()
}

func (GcKeepReason) Type() protoreflect.EnumType {
	return &file_gantry_gc_proto_enumTypes[1]
}

func (x GcKeepReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type GcSchedule struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Interval    *durationpb.Duration   `protobuf:"bytes,1,opt,name=interval"`
	xxx_hidden_MinInterval *durationpb.Duration   `protobuf:"bytes,2,opt,name=min_interval,json=minInterval"`
	xxx_hidden_Grace       *durationpb.Duration   `protobuf:"bytes,3,opt,name=grace"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GcSchedule) Reset() {
	*x = GcSchedule{}
	mi := &file_gantry_gc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcSchedule) ProtoMessage() {}

func (x *GcSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_gc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GcSchedule) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_Interval
	}
	return nil
}

func (x *GcSchedule) GetMinInterval() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_MinInterval
	}
	return nil
}

func (x *GcSchedule) GetGrace() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_Grace
	}
	return nil
}

func (x *GcSchedule) SetInterval(v *durationpb.Duration) {
	x.xxx_hidden_Interval = v
}

func (x *GcSchedule) SetMinInterval(v *durationpb.Duration) {
	x.xxx_hidden_MinInterval = v
}

func (x *GcSchedule) SetGrace(v *durationpb.Duration) {
	x.xxx_hidden_Grace = v
}

func (x *GcSchedule) HasInterval() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Interval != nil
}

func (x *GcSchedule) HasMinInterval() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MinInterval != nil
}

func (x *GcSchedule) HasGrace() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Grace != nil
}

func (x *GcSchedule) ClearInterval() {
	x.xxx_hidden_Interval = nil
}

func (x *GcSchedule) ClearMinInterval() {
	x.xxx_hidden_MinInterval = nil
}

func (x *GcSchedule) ClearGrace() {
	x.xxx_hidden_Grace = nil
}

type GcSchedule_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Interval    *durationpb.Duration
	MinInterval *durationpb.Duration
	Grace       *durationpb.Duration
}

func (b0 GcSchedule_builder) Build() *GcSchedule {
	m0 := &GcSchedule{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Interval = b.Interval
	x.xxx_hidden_MinInterval = b.MinInterval
	x.xxx_hidden_Grace = b.Grace
	return m0
}

type GcRule struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Repo        *string                `protobuf:"bytes,1,opt,name=repo"`
	xxx_hidden_MaxAge      *durationpb.Duration   `protobuf:"bytes,2,opt,name=max_age,json=maxAge"`
	xxx_hidden_KeepN       int32                  `protobuf:"varint,3,opt,name=keep_n,json=keepN"`
	xxx_hidden_MaxN        int32                  `protobuf:"varint,4,opt,name=max_n,json=maxN"`
	xxx_hidden_Pins        []string               `protobuf:"bytes,5,rep,name=pins"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GcRule) Reset() {
	*x = GcRule{}
	mi := &file_gantry_gc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcRule) ProtoMessage() {}

func (x *GcRule) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_gc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GcRule) GetRepo() string {
	if x != nil {
		if x.xxx_hidden_Repo != nil {
			return *x.xxx_hidden_Repo
		}
		return ""
	}
	return ""
}

func (x *GcRule) GetMaxAge() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_MaxAge
	}
	return nil
}

func (x *GcRule) GetKeepN() int32 {
	if x != nil {
		return x.xxx_hidden_KeepN
	}
	return 0
}

func (x *GcRule) GetMaxN() int32 {
	if x != nil {
		return x.xxx_hidden_MaxN
	}
	return 0
}

func (x *GcRule) GetPins() []string {
	if x != nil {
		return x.xxx_hidden_Pins
	}
	return nil
}

func (x *GcRule) SetRepo(v string) {
	x.xxx_hidden_Repo = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *GcRule) SetMaxAge(v *durationpb.Duration) {
	x.xxx_hidden_MaxAge = v
}

func (x *GcRule) SetKeepN(v int32) {
	x.xxx_hidden_KeepN = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *GcRule) SetMaxN(v int32) {
	x.xxx_hidden_MaxN = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *GcRule) SetPins(v []string) {
	x.xxx_hidden_Pins = v
}

func (x *GcRule) HasRepo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GcRule) HasMaxAge() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MaxAge != nil
}

func (x *GcRule) HasKeepN() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GcRule) HasMaxN() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *GcRule) ClearRepo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Repo = nil
}

func (x *GcRule) ClearMaxAge() {
	x.xxx_hidden_MaxAge = nil
}

func (x *GcRule) ClearKeepN() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_KeepN = 0
}

func (x *GcRule) ClearMaxN() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_MaxN = 0
}

type GcRule_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Repo   *string
	MaxAge *durationpb.Duration
	KeepN  *int32
	MaxN   *int32
	Pins   []string
}

func (b0 GcRule_builder) Build() *GcRule {
	m0 := &GcRule{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Repo != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Repo = b.Repo
	}
	x.xxx_hidden_MaxAge = b.MaxAge
	if b.KeepN != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_KeepN = *b.KeepN
	}
	if b.MaxN != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_MaxN = *b.MaxN
	}
	x.xxx_hidden_Pins = b.Pins
	return m0
}

// One-shot policy override. A present override REPLACES the store's
// configured rules with a single blanket rule built from these fields; unset
// fields are zero, which disables the corresponding mechanism for the call.
type GcOverride struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MaxAge        *durationpb.Duration   `protobuf:"bytes,1,opt,name=max_age,json=maxAge"`
	xxx_hidden_KeepN         int32                  `protobuf:"varint,2,opt,name=keep_n,json=keepN"`
	xxx_hidden_MaxN          int32                  `protobuf:"varint,3,opt,name=max_n,json=maxN"`
	xxx_hidden_Pins          []string               `protobuf:"bytes,4,rep,name=pins"`
	xxx_hidden_UntaggedAfter *durationpb.Duration   `protobuf:"bytes,5,opt,name=untagged_after,json=untaggedAfter"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GcOverride) Reset() {
	*x = GcOverride{}
	mi := &file_gantry_gc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcOverride) ProtoMessage() {}

func (x *GcOverride) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_gc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GcOverride) GetMaxAge() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_MaxAge
	}
	return nil
}

func (x *GcOverride) GetKeepN() int32 {
	if x != nil {
		return x.xxx_hidden_KeepN
	}
	return 0
}

func (x *GcOverride) GetMaxN() int32 {
	if x != nil {
		return x.xxx_hidden_MaxN
	}
	return 0
}

func (x *GcOverride) GetPins() []string {
	if x != nil {
		return x.xxx_hidden_Pins
	}
	return nil
}

func (x *GcOverride) GetUntaggedAfter() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_UntaggedAfter
	}
	return nil
}

func (x *GcOverride) SetMaxAge(v *durationpb.Duration) {
	x.xxx_hidden_MaxAge = v
}

func (x *GcOverride) SetKeepN(v int32) {
	x.xxx_hidden_KeepN = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *GcOverride) SetMaxN(v int32) {
	x.xxx_hidden_MaxN = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *GcOverride) SetPins(v []string) {
	x.xxx_hidden_Pins = v
}

func (x *GcOverride) SetUntaggedAfter(v *durationpb.Duration) {
	x.xxx_hidden_UntaggedAfter = v
}

func (x *GcOverride) HasMaxAge() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MaxAge != nil
}

func (x *GcOverride) HasKeepN() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GcOverride) HasMaxN() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GcOverride) HasUntaggedAfter() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UntaggedAfter != nil
}

func (x *GcOverride) ClearMaxAge() {
	x.xxx_hidden_MaxAge = nil
}

func (x *GcOverride) ClearKeepN() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_KeepN = 0
}

func (x *GcOverride) ClearMaxN() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_MaxN = 0
}

func (x *GcOverride) ClearUntaggedAfter() {
	x.xxx_hidden_UntaggedAfter = nil
}

type GcOverride_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MaxAge        *durationpb.Duration
	KeepN         *int32
	MaxN          *int32
	Pins          []string
	UntaggedAfter *durationpb.Duration
}

func (b0 GcOverride_builder) Build() *GcOverride {
	m0 := &GcOverride{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MaxAge = b.MaxAge
	if b.KeepN != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_KeepN = *b.KeepN
	}
	if b.MaxN != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_MaxN = *b.MaxN
	}
	x.xxx_hidden_Pins = b.Pins
	x.xxx_hidden_UntaggedAfter = b.UntaggedAfter
	return m0
}

type GcCandidate struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref         *string                `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Digest      *string                `protobuf:"bytes,2,opt,name=digest"`
	xxx_hidden_ImageId     *string                `protobuf:"bytes,3,opt,name=image_id,json=imageId"`
	xxx_hidden_LastUsed    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_used,json=lastUsed"`
	xxx_hidden_Reason      GcDeleteReason         `protobuf:"varint,5,opt,name=reason,enum=gantry.GcDeleteReason"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GcCandidate) Reset() {
	*x = GcCandidate{}
	mi := &file_gantry_gc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcCandidate) ProtoMessage() {}

func (x *GcCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_gc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GcCandidate) GetRef() string {
	if x != nil {
		if x.xxx_hidden_Ref != nil {
			return *x.xxx_hidden_Ref
		}
		return ""
	}
	return ""
}

func (x *GcCandidate) GetDigest() string {
	if x != nil {
		if x.xxx_hidden_Digest != nil {
			return *x.xxx_hidden_Digest
		}
		return ""
	}
	return ""
}

func (x *GcCandidate) GetImageId() string {
	if x != nil {
		if x.xxx_hidden_ImageId != nil {
			return *x.xxx_hidden_ImageId
		}
		return ""
	}
	return ""
}

func (x *GcCandidate) GetLastUsed() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastUsed
	}
	return nil
}

func (x *GcCandidate) GetReason() GcDeleteReason {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 4) {
			return x.xxx_hidden_Reason
		}
	}
	return GcDeleteReason_GC_DELETE_REASON_UNSPECIFIED
}

func (x *GcCandidate) SetRef(v string) {
	x.xxx_hidden_Ref = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *GcCandidate) SetDigest(v string) {
	x.xxx_hidden_Digest = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *GcCandidate) SetImageId(v string) {
	x.xxx_hidden_ImageId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *GcCandidate) SetLastUsed(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastUsed = v
}

func (x *GcCandidate) SetReason(v GcDeleteReason) {
	x.xxx_hidden_Reason = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *GcCandidate) HasRef() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GcCandidate) HasDigest() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GcCandidate) HasImageId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GcCandidate) HasLastUsed() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastUsed != nil
}

func (x *GcCandidate) HasReason() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *GcCandidate) ClearRef() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Ref = nil
}

func (x *GcCandidate) ClearDigest() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Digest = nil
}

func (x *GcCandidate) ClearImageId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ImageId = nil
}

func (x *GcCandidate) ClearLastUsed() {
	x.xxx_hidden_LastUsed = nil
}

func (x *GcCandidate) ClearReason() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Reason = GcDeleteReason_GC_DELETE_REASON_UNSPECIFIED
}

type GcCandidate_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *string
	Digest *string
	// Set for untagged-reap candidates.
	ImageId  *string
	LastUsed *timestamppb.Timestamp
	Reason   *GcDeleteReason
}

func (b0 GcCandidate_builder) Build() *GcCandidate {
	m0 := &GcCandidate{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Ref != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Ref = b.Ref
	}
	if b.Digest != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Digest = b.Digest
	}
	if b.ImageId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_ImageId = b.ImageId
	}
	x.xxx_hidden_LastUsed = b.LastUsed
	if b.Reason != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_Reason = *b.Reason
	}
	return m0
}

type GcKept struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref         *string                `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Reason      GcKeepReason           `protobuf:"varint,2,opt,name=reason,enum=gantry.GcKeepReason"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GcKept) Reset() {
	*x = GcKept{}
	mi := &file_gantry_gc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcKept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcKept) ProtoMessage() {}

func (x *GcKept) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_gc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GcKept) GetRef() string {
	if x != nil {
		if x.xxx_hidden_Ref != nil {
			return *x.xxx_hidden_Ref
		}
		return ""
	}
	return ""
}

func (x *GcKept) GetReason() GcKeepReason {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Reason
		}
	}
	return GcKeepReason_GC_KEEP_REASON_UNSPECIFIED
}

func (x *GcKept) SetRef(v string) {
	x.xxx_hidden_Ref = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *GcKept) SetReason(v GcKeepReason) {
	x.xxx_hidden_Reason = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *GcKept) HasRef() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GcKept) HasReason() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GcKept) ClearRef() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Ref = nil
}

func (x *GcKept) ClearReason() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Reason = GcKeepReason_GC_KEEP_REASON_UNSPECIFIED
}

type GcKept_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *string
	Reason *GcKeepReason
}

func (b0 GcKept_builder) Build() *GcKept {
	m0 := &GcKept{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Ref != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Ref = b.Ref
	}
	if b.Reason != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Reason = *b.Reason
	}
	return m0
}

// Health of the usage-event stream that stamps last_used on the store's
// images. A dead stream freezes last_used and slowly turns age-GC against
// hot images, so it is reported as part of the GC status.
type GcWatcherStatus struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Connected     bool                   `protobuf:"varint,1,opt,name=connected"`
	xxx_hidden_WatchingSince *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=watching_since,json=watchingSince"`
	xxx_hidden_LastEventAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_event_at,json=lastEventAt"`
	xxx_hidden_LastSeedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_seed_at,json=lastSeedAt"`
	xxx_hidden_Reconnects    int32                  `protobuf:"varint,5,opt,name=reconnects"`
	xxx_hidden_LastError     *string                `protobuf:"bytes,6,opt,name=last_error,json=lastError"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GcWatcherStatus) Reset() {
	*x = GcWatcherStatus{}
	mi := &file_gantry_gc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcWatcherStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcWatcherStatus) ProtoMessage() {}

func (x *GcWatcherStatus) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_gc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GcWatcherStatus) GetConnected() bool {
	if x != nil {
		return x.xxx_hidden_Connected
	}
	return false
}

func (x *GcWatcherStatus) GetWatchingSince() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_WatchingSince
	}
	return nil
}

func (x *GcWatcherStatus) GetLastEventAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastEventAt
	}
	return nil
}

func (x *GcWatcherStatus) GetLastSeedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastSeedAt
	}
	return nil
}

func (x *GcWatcherStatus) GetReconnects() int32 {
	if x != nil {
		return x.xxx_hidden_Reconnects
	}
	return 0
}

func (x *GcWatcherStatus) GetLastError() string {
	if x != nil {
		if x.xxx_hidden_LastError != nil {
			return *x.xxx_hidden_LastError
		}
		return ""
	}
	return ""
}

func (x *GcWatcherStatus) SetConnected(v bool) {
	x.xxx_hidden_Connected = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *GcWatcherStatus) SetWatchingSince(v *timestamppb.Timestamp) {
	x.xxx_hidden_WatchingSince = v
}

func (x *GcWatcherStatus) SetLastEventAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastEventAt = v
}

func (x *GcWatcherStatus) SetLastSeedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastSeedAt = v
}

func (x *GcWatcherStatus) SetReconnects(v int32) {
	x.xxx_hidden_Reconnects = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *GcWatcherStatus) SetLastError(v string) {
	x.xxx_hidden_LastError = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *GcWatcherStatus) HasConnected() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GcWatcherStatus) HasWatchingSince() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_WatchingSince != nil
}

func (x *GcWatcherStatus) HasLastEventAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastEventAt != nil
}

func (x *GcWatcherStatus) HasLastSeedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastSeedAt != nil
}

func (x *GcWatcherStatus) HasReconnects() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *GcWatcherStatus) HasLastError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *GcWatcherStatus) ClearConnected() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Connected = false
}

func (x *GcWatcherStatus) ClearWatchingSince() {
	x.xxx_hidden_WatchingSince = nil
}

func (x *GcWatcherStatus) ClearLastEventAt() {
	x.xxx_hidden_LastEventAt = nil
}

func (x *GcWatcherStatus) ClearLastSeedAt() {
	x.xxx_hidden_LastSeedAt = nil
}

func (x *GcWatcherStatus) ClearReconnects() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Reconnects = 0
}

func (x *GcWatcherStatus) ClearLastError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_LastError = nil
}

type GcWatcherStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Connected     *bool
	WatchingSince *timestamppb.Timestamp
	// Receipt time of the last usage event.
	LastEventAt *timestamppb.Timestamp
	LastSeedAt  *timestamppb.Timestamp
	// Times the event stream ended and was re-established.
	Reconnects *int32
	LastError  *string
}

func (b0 GcWatcherStatus_builder) Build() *GcWatcherStatus {
	m0 := &GcWatcherStatus{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Connected != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Connected = *b.Connected
	}
	x.xxx_hidden_WatchingSince = b.WatchingSince
	x.xxx_hidden_LastEventAt = b.LastEventAt
	x.xxx_hidden_LastSeedAt = b.LastSeedAt
	if b.Reconnects != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Reconnects = *b.Reconnects
	}
	if b.LastError != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_LastError = b.LastError
	}
	return m0
}

var File_gantry_gc_proto protoreflect.FileDescriptor

const file_gantry_gc_proto_rawDesc = "" +
	"\n" +
	"\x0fgantry/gc.proto\x12\x06gantry\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x01\n" +
	"\n" +
	"GcSchedule\x125\n" +
	"\binterval\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\binterval\x12<\n" +
	"\fmin_interval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\vminInterval\x12/\n" +
	"\x05grace\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x05grace\"\x90\x01\n" +
	"\x06GcRule\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x122\n" +
	"\amax_age\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x06maxAge\x12\x15\n" +
	"\x06keep_n\x18\x03 \x01(\x05R\x05keepN\x12\x13\n" +
	"\x05max_n\x18\x04 \x01(\x05R\x04maxN\x12\x12\n" +
	"\x04pins\x18\x05 \x03(\tR\x04pins\"\xc2\x01\n" +
	"\n" +
	"GcOverride\x122\n" +
	"\amax_age\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x06maxAge\x12\x15\n" +
	"\x06keep_n\x18\x02 \x01(\x05R\x05keepN\x12\x13\n" +
	"\x05max_n\x18\x03 \x01(\x05R\x04maxN\x12\x12\n" +
	"\x04pins\x18\x04 \x03(\tR\x04pins\x12@\n" +
	"\x0euntagged_after\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\runtaggedAfter\"\xbb\x01\n" +
	"\vGcCandidate\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12\x19\n" +
	"\bimage_id\x18\x03 \x01(\tR\aimageId\x127\n" +
	"\tlast_used\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\blastUsed\x12.\n" +
	"\x06reason\x18\x05 \x01(\x0e2\x16.gantry.GcDeleteReasonR\x06reason\"H\n" +
	"\x06GcKept\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12,\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x14.gantry.GcKeepReasonR\x06reason\"\xaf\x02\n" +
	"\x0fGcWatcherStatus\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12A\n" +
	"\x0ewatching_since\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rwatchingSince\x12>\n" +
	"\rlast_event_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vlastEventAt\x12<\n" +
	"\flast_seed_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeedAt\x12\x1e\n" +
	"\n" +
	"reconnects\x18\x05 \x01(\x05R\n" +
	"reconnects\x12\x1d\n" +
	"\n" +
	"last_error\x18\x06 \x01(\tR\tlastError*\x99\x01\n" +
	"\x0eGcDeleteReason\x12 \n" +
	"\x1cGC_DELETE_REASON_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dGC_DELETE_REASON_AGE_EXCEEDED\x10\x01\x12#\n" +
	"\x1fGC_DELETE_REASON_MAX_N_EXCEEDED\x10\x02\x12\x1d\n" +
	"\x19GC_DELETE_REASON_UNTAGGED\x10\x03*\xcb\x02\n" +
	"\fGcKeepReason\x12\x1e\n" +
	"\x1aGC_KEEP_REASON_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15GC_KEEP_REASON_IN_USE\x10\x01\x12\x19\n" +
	"\x15GC_KEEP_REASON_PINNED\x10\x02\x12 \n" +
	"\x1cGC_KEEP_REASON_KEEP_N_RECENT\x10\x03\x12!\n" +
	"\x1dGC_KEEP_REASON_WITHIN_MAX_AGE\x10\x04\x12\x18\n" +
	"\x14GC_KEEP_REASON_GRACE\x10\x05\x12\"\n" +
	"\x1eGC_KEEP_REASON_AGE_GC_DISABLED\x10\x06\x12\x1c\n" +
	"\x18GC_KEEP_REASON_UNMANAGED\x10\a\x12!\n" +
	"\x1dGC_KEEP_REASON_UNTAGGED_GRACE\x10\b\x12!\n" +
	"\x1dGC_KEEP_REASON_DIGEST_TRACKED\x10\tB\x1fZ\x1dgithub.com/lesomnus/gantry/pbb\beditionsp\xe8\a"

var file_gantry_gc_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gantry_gc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gantry_gc_proto_goTypes = []any{
	(GcDeleteReason)(0),           // 0: gantry.GcDeleteReason
	(GcKeepReason)(0),             // 1: gantry.GcKeepReason
	(*GcSchedule)(nil),            // 2: gantry.GcSchedule
	(*GcRule)(nil),                // 3: gantry.GcRule
	(*GcOverride)(nil),            // 4: gantry.GcOverride
	(*GcCandidate)(nil),           // 5: gantry.GcCandidate
	(*GcKept)(nil),                // 6: gantry.GcKept
	(*GcWatcherStatus)(nil),       // 7: gantry.GcWatcherStatus
	(*durationpb.Duration)(nil),   // 8: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_gantry_gc_proto_depIdxs = []int32{
	8,  // 0: gantry.GcSchedule.interval:type_name -> google.protobuf.Duration
	8,  // 1: gantry.GcSchedule.min_interval:type_name -> google.protobuf.Duration
	8,  // 2: gantry.GcSchedule.grace:type_name -> google.protobuf.Duration
	8,  // 3: gantry.GcRule.max_age:type_name -> google.protobuf.Duration
	8,  // 4: gantry.GcOverride.max_age:type_name -> google.protobuf.Duration
	8,  // 5: gantry.GcOverride.untagged_after:type_name -> google.protobuf.Duration
	9,  // 6: gantry.GcCandidate.last_used:type_name -> google.protobuf.Timestamp
	0,  // 7: gantry.GcCandidate.reason:type_name -> gantry.GcDeleteReason
	1,  // 8: gantry.GcKept.reason:type_name -> gantry.GcKeepReason
	9,  // 9: gantry.GcWatcherStatus.watching_since:type_name -> google.protobuf.Timestamp
	9,  // 10: gantry.GcWatcherStatus.last_event_at:type_name -> google.protobuf.Timestamp
	9,  // 11: gantry.GcWatcherStatus.last_seed_at:type_name -> google.protobuf.Timestamp
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_gantry_gc_proto_init() }
func file_gantry_gc_proto_init() {
	if File_gantry_gc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gantry_gc_proto_rawDesc), len(file_gantry_gc_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gantry_gc_proto_goTypes,
		DependencyIndexes: file_gantry_gc_proto_depIdxs,
		EnumInfos:         file_gantry_gc_proto_enumTypes,
		MessageInfos:      file_gantry_gc_proto_msgTypes,
	}.Build()
	File_gantry_gc_proto = out.File
	file_gantry_gc_proto_goTypes = nil
	file_gantry_gc_proto_depIdxs = nil
}
