// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: gantry/image_svc.g.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageAddRequest struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id                  []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Store               *StoreRef              `protobuf:"bytes,2,opt,name=store"`
	xxx_hidden_Ref                 string                 `protobuf:"bytes,8,opt,name=ref"`
	xxx_hidden_Digest              string                 `protobuf:"bytes,9,opt,name=digest"`
	xxx_hidden_Repo                string                 `protobuf:"bytes,10,opt,name=repo"`
	xxx_hidden_Tag                 string                 `protobuf:"bytes,11,opt,name=tag"`
	xxx_hidden_DateLastDistributed *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=date_last_distributed,json=dateLastDistributed"`
	xxx_hidden_DateLastUsed        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=date_last_used,json=dateLastUsed"`
	xxx_hidden_DateFirstSeen       *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_first_seen,json=dateFirstSeen"`
	xxx_hidden_Pinned              bool                   `protobuf:"varint,16,opt,name=pinned"`
	xxx_hidden_InUse               bool                   `protobuf:"varint,17,opt,name=in_use,json=inUse"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *ImageAddRequest) Reset() {
	*x = ImageAddRequest{}
	mi := &file_gantry_image_svc_g_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageAddRequest) ProtoMessage() {}

func (x *ImageAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_image_svc_g_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ImageAddRequest) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *ImageAddRequest) GetStore() *StoreRef {
	if x != nil {
		return x.xxx_hidden_Store
	}
	return nil
}

func (x *ImageAddRequest) GetRef() string {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return ""
}

func (x *ImageAddRequest) GetDigest() string {
	if x != nil {
		return x.xxx_hidden_Digest
	}
	return ""
}

func (x *ImageAddRequest) GetRepo() string {
	if x != nil {
		return x.xxx_hidden_Repo
	}
	return ""
}

func (x *ImageAddRequest) GetTag() string {
	if x != nil {
		return x.xxx_hidden_Tag
	}
	return ""
}

func (x *ImageAddRequest) GetDateLastDistributed() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateLastDistributed
	}
	return nil
}

func (x *ImageAddRequest) GetDateLastUsed() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateLastUsed
	}
	return nil
}

func (x *ImageAddRequest) GetDateFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateFirstSeen
	}
	return nil
}

func (x *ImageAddRequest) GetPinned() bool {
	if x != nil {
		return x.xxx_hidden_Pinned
	}
	return false
}

func (x *ImageAddRequest) GetInUse() bool {
	if x != nil {
		return x.xxx_hidden_InUse
	}
	return false
}

func (x *ImageAddRequest) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 11)
}

func (x *ImageAddRequest) SetStore(v *StoreRef) {
	x.xxx_hidden_Store = v
}

func (x *ImageAddRequest) SetRef(v string) {
	x.xxx_hidden_Ref = v
}

func (x *ImageAddRequest) SetDigest(v string) {
	x.xxx_hidden_Digest = v
}

func (x *ImageAddRequest) SetRepo(v string) {
	x.xxx_hidden_Repo = v
}

func (x *ImageAddRequest) SetTag(v string) {
	x.xxx_hidden_Tag = v
}

func (x *ImageAddRequest) SetDateLastDistributed(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateLastDistributed = v
}

func (x *ImageAddRequest) SetDateLastUsed(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateLastUsed = v
}

func (x *ImageAddRequest) SetDateFirstSeen(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateFirstSeen = v
}

func (x *ImageAddRequest) SetPinned(v bool) {
	x.xxx_hidden_Pinned = v
}

func (x *ImageAddRequest) SetInUse(v bool) {
	x.xxx_hidden_InUse = v
}

func (x *ImageAddRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ImageAddRequest) HasStore() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Store != nil
}

func (x *ImageAddRequest) HasDateLastDistributed() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateLastDistributed != nil
}

func (x *ImageAddRequest) HasDateLastUsed() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateLastUsed != nil
}

func (x *ImageAddRequest) HasDateFirstSeen() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateFirstSeen != nil
}

func (x *ImageAddRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *ImageAddRequest) ClearStore() {
	x.xxx_hidden_Store = nil
}

func (x *ImageAddRequest) ClearDateLastDistributed() {
	x.xxx_hidden_DateLastDistributed = nil
}

func (x *ImageAddRequest) ClearDateLastUsed() {
	x.xxx_hidden_DateLastUsed = nil
}

func (x *ImageAddRequest) ClearDateFirstSeen() {
	x.xxx_hidden_DateFirstSeen = nil
}

type ImageAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id                  []byte
	Store               *StoreRef
	Ref                 string
	Digest              string
	Repo                string
	Tag                 string
	DateLastDistributed *timestamppb.Timestamp
	DateLastUsed        *timestamppb.Timestamp
	DateFirstSeen       *timestamppb.Timestamp
	Pinned              bool
	InUse               bool
}

func (b0 ImageAddRequest_builder) Build() *ImageAddRequest {
	m0 := &ImageAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 11)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Store = b.Store
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Digest = b.Digest
	x.xxx_hidden_Repo = b.Repo
	x.xxx_hidden_Tag = b.Tag
	x.xxx_hidden_DateLastDistributed = b.DateLastDistributed
	x.xxx_hidden_DateLastUsed = b.DateLastUsed
	x.xxx_hidden_DateFirstSeen = b.DateFirstSeen
	x.xxx_hidden_Pinned = b.Pinned
	x.xxx_hidden_InUse = b.InUse
	return m0
}

type ImageGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *ImageRef              `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *ImageSelect           `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ImageGetRequest) Reset() {
	*x = ImageGetRequest{}
	mi := &file_gantry_image_svc_g_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageGetRequest) ProtoMessage() {}

func (x *ImageGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_image_svc_g_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ImageGetRequest) GetRef() *ImageRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *ImageGetRequest) GetSelect() *ImageSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *ImageGetRequest) SetRef(v *ImageRef) {
	x.xxx_hidden_Ref = v
}

func (x *ImageGetRequest) SetSelect(v *ImageSelect) {
	x.xxx_hidden_Select = v
}

func (x *ImageGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *ImageGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *ImageGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *ImageGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type ImageGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *ImageRef
	Select *ImageSelect
}

func (b0 ImageGetRequest_builder) Build() *ImageGetRequest {
	m0 := &ImageGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type ImageRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isImageRef_Key         `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ImageRef) Reset() {
	*x = ImageRef{}
	mi := &file_gantry_image_svc_g_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRef) ProtoMessage() {}

func (x *ImageRef) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_image_svc_g_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ImageRef) GetId() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*imageRef_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *ImageRef) GetLocator() *ImageRefByLocator {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*imageRef_Locator); ok {
			return x.Locator
		}
	}
	return nil
}

func (x *ImageRef) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Key = &imageRef_Id{v}
}

func (x *ImageRef) SetLocator(v *ImageRefByLocator) {
	if v == nil {
		x.xxx_hidden_Key = nil
		return
	}
	x.xxx_hidden_Key = &imageRef_Locator{v}
}

func (x *ImageRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *ImageRef) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*imageRef_Id)
	return ok
}

func (x *ImageRef) HasLocator() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*imageRef_Locator)
	return ok
}

func (x *ImageRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *ImageRef) ClearId() {
	if _, ok := x.xxx_hidden_Key.(*imageRef_Id); ok {
		x.xxx_hidden_Key = nil
	}
}

func (x *ImageRef) ClearLocator() {
	if _, ok := x.xxx_hidden_Key.(*imageRef_Locator); ok {
		x.xxx_hidden_Key = nil
	}
}

const ImageRef_Key_not_set_case case_ImageRef_Key = 0
const ImageRef_Id_case case_ImageRef_Key = 1
const ImageRef_Locator_case case_ImageRef_Key = 2

func (x *ImageRef) WhichKey() case_ImageRef_Key {
	if x == nil {
		return ImageRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *imageRef_Id:
		return ImageRef_Id_case
	case *imageRef_Locator:
		return ImageRef_Locator_case
	default:
		return ImageRef_Key_not_set_case
	}
}

type ImageRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Id      []byte
	Locator *ImageRefByLocator
	// -- end of xxx_hidden_Key
}

func (b0 ImageRef_builder) Build() *ImageRef {
	m0 := &ImageRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Key = &imageRef_Id{b.Id}
	}
	if b.Locator != nil {
		x.xxx_hidden_Key = &imageRef_Locator{b.Locator}
	}
	return m0
}

type case_ImageRef_Key protoreflect.FieldNumber

func (x case_ImageRef_Key) String() string {
	md := file_gantry_image_svc_g_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isImageRef_Key interface {
	isImageRef_Key()
}

type imageRef_Id struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,oneof"`
}

type imageRef_Locator struct {
	Locator *ImageRefByLocator `protobuf:"bytes,2,opt,name=locator,oneof"`
}

func (*imageRef_Id) isImageRef_Key() {}

func (*imageRef_Locator) isImageRef_Key() {}

type ImageRefByLocator struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Store       *StoreRef              `protobuf:"bytes,2,opt,name=store"`
	xxx_hidden_Ref         *string                `protobuf:"bytes,8,opt,name=ref"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ImageRefByLocator) Reset() {
	*x = ImageRefByLocator{}
	mi := &file_gantry_image_svc_g_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRefByLocator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRefByLocator) ProtoMessage() {}

func (x *ImageRefByLocator) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_image_svc_g_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ImageRefByLocator) GetStore() *StoreRef {
	if x != nil {
		return x.xxx_hidden_Store
	}
	return nil
}

func (x *ImageRefByLocator) GetRef() string {
	if x != nil {
		if x.xxx_hidden_Ref != nil {
			return *x.xxx_hidden_Ref
		}
		return ""
	}
	return ""
}

func (x *ImageRefByLocator) SetStore(v *StoreRef) {
	x.xxx_hidden_Store = v
}

func (x *ImageRefByLocator) SetRef(v string) {
	x.xxx_hidden_Ref = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ImageRefByLocator) HasStore() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Store != nil
}

func (x *ImageRefByLocator) HasRef() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ImageRefByLocator) ClearStore() {
	x.xxx_hidden_Store = nil
}

func (x *ImageRefByLocator) ClearRef() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Ref = nil
}

type ImageRefByLocator_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Store *StoreRef
	Ref   *string
}

func (b0 ImageRefByLocator_builder) Build() *ImageRefByLocator {
	m0 := &ImageRefByLocator{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Store = b.Store
	if b.Ref != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Ref = b.Ref
	}
	return m0
}

type ImageSelect struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All                 bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_Store               *StoreSelect           `protobuf:"bytes,2,opt,name=store"`
	xxx_hidden_Ref                 bool                   `protobuf:"varint,8,opt,name=ref"`
	xxx_hidden_Digest              bool                   `protobuf:"varint,9,opt,name=digest"`
	xxx_hidden_Repo                bool                   `protobuf:"varint,10,opt,name=repo"`
	xxx_hidden_Tag                 bool                   `protobuf:"varint,11,opt,name=tag"`
	xxx_hidden_DateLastDistributed bool                   `protobuf:"varint,13,opt,name=date_last_distributed,json=dateLastDistributed"`
	xxx_hidden_DateLastUsed        bool                   `protobuf:"varint,14,opt,name=date_last_used,json=dateLastUsed"`
	xxx_hidden_DateFirstSeen       bool                   `protobuf:"varint,15,opt,name=date_first_seen,json=dateFirstSeen"`
	xxx_hidden_Pinned              bool                   `protobuf:"varint,16,opt,name=pinned"`
	xxx_hidden_InUse               bool                   `protobuf:"varint,17,opt,name=in_use,json=inUse"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *ImageSelect) Reset() {
	*x = ImageSelect{}
	mi := &file_gantry_image_svc_g_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSelect) ProtoMessage() {}

func (x *ImageSelect) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_image_svc_g_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ImageSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *ImageSelect) GetStore() *StoreSelect {
	if x != nil {
		return x.xxx_hidden_Store
	}
	return nil
}

func (x *ImageSelect) GetRef() bool {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return false
}

func (x *ImageSelect) GetDigest() bool {
	if x != nil {
		return x.xxx_hidden_Digest
	}
	return false
}

func (x *ImageSelect) GetRepo() bool {
	if x != nil {
		return x.xxx_hidden_Repo
	}
	return false
}

func (x *ImageSelect) GetTag() bool {
	if x != nil {
		return x.xxx_hidden_Tag
	}
	return false
}

func (x *ImageSelect) GetDateLastDistributed() bool {
	if x != nil {
		return x.xxx_hidden_DateLastDistributed
	}
	return false
}

func (x *ImageSelect) GetDateLastUsed() bool {
	if x != nil {
		return x.xxx_hidden_DateLastUsed
	}
	return false
}

func (x *ImageSelect) GetDateFirstSeen() bool {
	if x != nil {
		return x.xxx_hidden_DateFirstSeen
	}
	return false
}

func (x *ImageSelect) GetPinned() bool {
	if x != nil {
		return x.xxx_hidden_Pinned
	}
	return false
}

func (x *ImageSelect) GetInUse() bool {
	if x != nil {
		return x.xxx_hidden_InUse
	}
	return false
}

func (x *ImageSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 11)
}

func (x *ImageSelect) SetStore(v *StoreSelect) {
	x.xxx_hidden_Store = v
}

func (x *ImageSelect) SetRef(v bool) {
	x.xxx_hidden_Ref = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 11)
}

func (x *ImageSelect) SetDigest(v bool) {
	x.xxx_hidden_Digest = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 11)
}

func (x *ImageSelect) SetRepo(v bool) {
	x.xxx_hidden_Repo = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 11)
}

func (x *ImageSelect) SetTag(v bool) {
	x.xxx_hidden_Tag = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 11)
}

func (x *ImageSelect) SetDateLastDistributed(v bool) {
	x.xxx_hidden_DateLastDistributed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 11)
}

func (x *ImageSelect) SetDateLastUsed(v bool) {
	x.xxx_hidden_DateLastUsed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 11)
}

func (x *ImageSelect) SetDateFirstSeen(v bool) {
	x.xxx_hidden_DateFirstSeen = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 11)
}

func (x *ImageSelect) SetPinned(v bool) {
	x.xxx_hidden_Pinned = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 11)
}

func (x *ImageSelect) SetInUse(v bool) {
	x.xxx_hidden_InUse = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 11)
}

func (x *ImageSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ImageSelect) HasStore() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Store != nil
}

func (x *ImageSelect) HasRef() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ImageSelect) HasDigest() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ImageSelect) HasRepo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ImageSelect) HasTag() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ImageSelect) HasDateLastDistributed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *ImageSelect) HasDateLastUsed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *ImageSelect) HasDateFirstSeen() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *ImageSelect) HasPinned() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *ImageSelect) HasInUse() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *ImageSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *ImageSelect) ClearStore() {
	x.xxx_hidden_Store = nil
}

func (x *ImageSelect) ClearRef() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Ref = false
}

func (x *ImageSelect) ClearDigest() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Digest = false
}

func (x *ImageSelect) ClearRepo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Repo = false
}

func (x *ImageSelect) ClearTag() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Tag = false
}

func (x *ImageSelect) ClearDateLastDistributed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_DateLastDistributed = false
}

func (x *ImageSelect) ClearDateLastUsed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_DateLastUsed = false
}

func (x *ImageSelect) ClearDateFirstSeen() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_DateFirstSeen = false
}

func (x *ImageSelect) ClearPinned() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_Pinned = false
}

func (x *ImageSelect) ClearInUse() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_InUse = false
}

type ImageSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All                 *bool
	Store               *StoreSelect
	Ref                 *bool
	Digest              *bool
	Repo                *bool
	Tag                 *bool
	DateLastDistributed *bool
	DateLastUsed        *bool
	DateFirstSeen       *bool
	Pinned              *bool
	InUse               *bool
}

func (b0 ImageSelect_builder) Build() *ImageSelect {
	m0 := &ImageSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 11)
		x.xxx_hidden_All = *b.All
	}
	x.xxx_hidden_Store = b.Store
	if b.Ref != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 11)
		x.xxx_hidden_Ref = *b.Ref
	}
	if b.Digest != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 11)
		x.xxx_hidden_Digest = *b.Digest
	}
	if b.Repo != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 11)
		x.xxx_hidden_Repo = *b.Repo
	}
	if b.Tag != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 11)
		x.xxx_hidden_Tag = *b.Tag
	}
	if b.DateLastDistributed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 11)
		x.xxx_hidden_DateLastDistributed = *b.DateLastDistributed
	}
	if b.DateLastUsed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 11)
		x.xxx_hidden_DateLastUsed = *b.DateLastUsed
	}
	if b.DateFirstSeen != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 11)
		x.xxx_hidden_DateFirstSeen = *b.DateFirstSeen
	}
	if b.Pinned != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 11)
		x.xxx_hidden_Pinned = *b.Pinned
	}
	if b.InUse != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 11)
		x.xxx_hidden_InUse = *b.InUse
	}
	return m0
}

type ImagePatchRequest struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref                 *ImageRef              `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Digest              *string                `protobuf:"bytes,17,opt,name=digest"`
	xxx_hidden_DateLastDistributed *timestamppb.Timestamp `protobuf:"bytes,25,opt,name=date_last_distributed,json=dateLastDistributed"`
	xxx_hidden_DateLastUsed        *timestamppb.Timestamp `protobuf:"bytes,27,opt,name=date_last_used,json=dateLastUsed"`
	xxx_hidden_Pinned              bool                   `protobuf:"varint,31,opt,name=pinned"`
	xxx_hidden_InUse               bool                   `protobuf:"varint,33,opt,name=in_use,json=inUse"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *ImagePatchRequest) Reset() {
	*x = ImagePatchRequest{}
	mi := &file_gantry_image_svc_g_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagePatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePatchRequest) ProtoMessage() {}

func (x *ImagePatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_image_svc_g_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ImagePatchRequest) GetRef() *ImageRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *ImagePatchRequest) GetDigest() string {
	if x != nil {
		if x.xxx_hidden_Digest != nil {
			return *x.xxx_hidden_Digest
		}
		return ""
	}
	return ""
}

func (x *ImagePatchRequest) GetDateLastDistributed() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateLastDistributed
	}
	return nil
}

func (x *ImagePatchRequest) GetDateLastUsed() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateLastUsed
	}
	return nil
}

func (x *ImagePatchRequest) GetPinned() bool {
	if x != nil {
		return x.xxx_hidden_Pinned
	}
	return false
}

func (x *ImagePatchRequest) GetInUse() bool {
	if x != nil {
		return x.xxx_hidden_InUse
	}
	return false
}

func (x *ImagePatchRequest) SetRef(v *ImageRef) {
	x.xxx_hidden_Ref = v
}

func (x *ImagePatchRequest) SetDigest(v string) {
	x.xxx_hidden_Digest = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *ImagePatchRequest) SetDateLastDistributed(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateLastDistributed = v
}

func (x *ImagePatchRequest) SetDateLastUsed(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateLastUsed = v
}

func (x *ImagePatchRequest) SetPinned(v bool) {
	x.xxx_hidden_Pinned = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *ImagePatchRequest) SetInUse(v bool) {
	x.xxx_hidden_InUse = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *ImagePatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *ImagePatchRequest) HasDigest() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ImagePatchRequest) HasDateLastDistributed() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateLastDistributed != nil
}

func (x *ImagePatchRequest) HasDateLastUsed() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateLastUsed != nil
}

func (x *ImagePatchRequest) HasPinned() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ImagePatchRequest) HasInUse() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ImagePatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *ImagePatchRequest) ClearDigest() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Digest = nil
}

func (x *ImagePatchRequest) ClearDateLastDistributed() {
	x.xxx_hidden_DateLastDistributed = nil
}

func (x *ImagePatchRequest) ClearDateLastUsed() {
	x.xxx_hidden_DateLastUsed = nil
}

func (x *ImagePatchRequest) ClearPinned() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Pinned = false
}

func (x *ImagePatchRequest) ClearInUse() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_InUse = false
}

type ImagePatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref                 *ImageRef
	Digest              *string
	DateLastDistributed *timestamppb.Timestamp
	DateLastUsed        *timestamppb.Timestamp
	Pinned              *bool
	InUse               *bool
}

func (b0 ImagePatchRequest_builder) Build() *ImagePatchRequest {
	m0 := &ImagePatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	if b.Digest != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Digest = b.Digest
	}
	x.xxx_hidden_DateLastDistributed = b.DateLastDistributed
	x.xxx_hidden_DateLastUsed = b.DateLastUsed
	if b.Pinned != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Pinned = *b.Pinned
	}
	if b.InUse != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_InUse = *b.InUse
	}
	return m0
}

type ImageListRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Store       *StoreRef              `protobuf:"bytes,1,opt,name=store"`
	xxx_hidden_Repo        *string                `protobuf:"bytes,2,opt,name=repo"`
	xxx_hidden_Ref         *string                `protobuf:"bytes,3,opt,name=ref"`
	xxx_hidden_Pinned      bool                   `protobuf:"varint,4,opt,name=pinned"`
	xxx_hidden_InUse       bool                   `protobuf:"varint,5,opt,name=in_use,json=inUse"`
	xxx_hidden_PageSize    int32                  `protobuf:"varint,10,opt,name=page_size,json=pageSize"`
	xxx_hidden_PageToken   *string                `protobuf:"bytes,11,opt,name=page_token,json=pageToken"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ImageListRequest) Reset() {
	*x = ImageListRequest{}
	mi := &file_gantry_image_svc_g_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageListRequest) ProtoMessage() {}

func (x *ImageListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_image_svc_g_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ImageListRequest) GetStore() *StoreRef {
	if x != nil {
		return x.xxx_hidden_Store
	}
	return nil
}

func (x *ImageListRequest) GetRepo() string {
	if x != nil {
		if x.xxx_hidden_Repo != nil {
			return *x.xxx_hidden_Repo
		}
		return ""
	}
	return ""
}

func (x *ImageListRequest) GetRef() string {
	if x != nil {
		if x.xxx_hidden_Ref != nil {
			return *x.xxx_hidden_Ref
		}
		return ""
	}
	return ""
}

func (x *ImageListRequest) GetPinned() bool {
	if x != nil {
		return x.xxx_hidden_Pinned
	}
	return false
}

func (x *ImageListRequest) GetInUse() bool {
	if x != nil {
		return x.xxx_hidden_InUse
	}
	return false
}

func (x *ImageListRequest) GetPageSize() int32 {
	if x != nil {
		return x.xxx_hidden_PageSize
	}
	return 0
}

func (x *ImageListRequest) GetPageToken() string {
	if x != nil {
		if x.xxx_hidden_PageToken != nil {
			return *x.xxx_hidden_PageToken
		}
		return ""
	}
	return ""
}

func (x *ImageListRequest) SetStore(v *StoreRef) {
	x.xxx_hidden_Store = v
}

func (x *ImageListRequest) SetRepo(v string) {
	x.xxx_hidden_Repo = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *ImageListRequest) SetRef(v string) {
	x.xxx_hidden_Ref = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *ImageListRequest) SetPinned(v bool) {
	x.xxx_hidden_Pinned = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *ImageListRequest) SetInUse(v bool) {
	x.xxx_hidden_InUse = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *ImageListRequest) SetPageSize(v int32) {
	x.xxx_hidden_PageSize = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *ImageListRequest) SetPageToken(v string) {
	x.xxx_hidden_PageToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *ImageListRequest) HasStore() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Store != nil
}

func (x *ImageListRequest) HasRepo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ImageListRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ImageListRequest) HasPinned() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ImageListRequest) HasInUse() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ImageListRequest) HasPageSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ImageListRequest) HasPageToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *ImageListRequest) ClearStore() {
	x.xxx_hidden_Store = nil
}

func (x *ImageListRequest) ClearRepo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Repo = nil
}

func (x *ImageListRequest) ClearRef() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Ref = nil
}

func (x *ImageListRequest) ClearPinned() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Pinned = false
}

func (x *ImageListRequest) ClearInUse() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_InUse = false
}

func (x *ImageListRequest) ClearPageSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_PageSize = 0
}

func (x *ImageListRequest) ClearPageToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_PageToken = nil
}

type ImageListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Store whose inventory to list.
	Store *StoreRef
	// Exact match on the host-qualified repository.
	Repo *string
	// Exact match on the full reference.
	Ref *string
	// Keep only pinned (true) or unpinned (false) images.
	Pinned *bool
	// Filter on live container usage; replaces the REST /inuse endpoint.
	InUse *bool
	// Maximum items to return; 0 = no limit.
	PageSize *int32
	// Continuation token from the previous response; empty starts from the
	// beginning.
	PageToken *string
}

func (b0 ImageListRequest_builder) Build() *ImageListRequest {
	m0 := &ImageListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Store = b.Store
	if b.Repo != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Repo = b.Repo
	}
	if b.Ref != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Ref = b.Ref
	}
	if b.Pinned != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Pinned = *b.Pinned
	}
	if b.InUse != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_InUse = *b.InUse
	}
	if b.PageSize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_PageSize = *b.PageSize
	}
	if b.PageToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_PageToken = b.PageToken
	}
	return m0
}

type ImageListResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items         *[]*Image              `protobuf:"bytes,1,rep,name=items"`
	xxx_hidden_NextPageToken *string                `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken"`
	xxx_hidden_Untagged      *[]*UntaggedImage      `protobuf:"bytes,3,rep,name=untagged"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ImageListResponse) Reset() {
	*x = ImageListResponse{}
	mi := &file_gantry_image_svc_g_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageListResponse) ProtoMessage() {}

func (x *ImageListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_image_svc_g_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ImageListResponse) GetItems() []*Image {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *ImageListResponse) GetNextPageToken() string {
	if x != nil {
		if x.xxx_hidden_NextPageToken != nil {
			return *x.xxx_hidden_NextPageToken
		}
		return ""
	}
	return ""
}

func (x *ImageListResponse) GetUntagged() []*UntaggedImage {
	if x != nil {
		if x.xxx_hidden_Untagged != nil {
			return *x.xxx_hidden_Untagged
		}
	}
	return nil
}

func (x *ImageListResponse) SetItems(v []*Image) {
	x.xxx_hidden_Items = &v
}

func (x *ImageListResponse) SetNextPageToken(v string) {
	x.xxx_hidden_NextPageToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ImageListResponse) SetUntagged(v []*UntaggedImage) {
	x.xxx_hidden_Untagged = &v
}

func (x *ImageListResponse) HasNextPageToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ImageListResponse) ClearNextPageToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NextPageToken = nil
}

type ImageListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// One page of results.
	Items []*Image
	// Empty when there are no further results.
	NextPageToken *string
	// Present only on unfiltered lists, mirroring the REST endpoint.
	Untagged []*UntaggedImage
}

func (b0 ImageListResponse_builder) Build() *ImageListResponse {
	m0 := &ImageListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	if b.NextPageToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_NextPageToken = b.NextPageToken
	}
	x.xxx_hidden_Untagged = &b.Untagged
	return m0
}

// Reap clock of an image observed with no tags (docker engines only).
type UntaggedImage struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id            *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_DateFirstSeen *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_first_seen,json=dateFirstSeen"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *UntaggedImage) Reset() {
	*x = UntaggedImage{}
	mi := &file_gantry_image_svc_g_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UntaggedImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UntaggedImage) ProtoMessage() {}

func (x *UntaggedImage) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_image_svc_g_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UntaggedImage) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *UntaggedImage) GetDateFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateFirstSeen
	}
	return nil
}

func (x *UntaggedImage) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *UntaggedImage) SetDateFirstSeen(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateFirstSeen = v
}

func (x *UntaggedImage) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UntaggedImage) HasDateFirstSeen() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateFirstSeen != nil
}

func (x *UntaggedImage) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *UntaggedImage) ClearDateFirstSeen() {
	x.xxx_hidden_DateFirstSeen = nil
}

type UntaggedImage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Engine image ID.
	Id            *string
	DateFirstSeen *timestamppb.Timestamp
}

func (b0 UntaggedImage_builder) Build() *UntaggedImage {
	m0 := &UntaggedImage{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_DateFirstSeen = b.DateFirstSeen
	return m0
}

var File_gantry_image_svc_g_proto protoreflect.FileDescriptor

const file_gantry_image_svc_g_proto_rawDesc = "" +
	"\n" +
	"\x18gantry/image_svc.g.proto\x12\x06gantry\x1a\x12gantry/image.proto\x1a\x18gantry/store_svc.g.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc8\x03\n" +
	"\x0fImageAddRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12&\n" +
	"\x05store\x18\x02 \x01(\v2\x10.gantry.StoreRefR\x05store\x12\x17\n" +
	"\x03ref\x18\b \x01(\tB\x05\xaa\x01\x02\b\x02R\x03ref\x12\x1d\n" +
	"\x06digest\x18\t \x01(\tB\x05\xaa\x01\x02\b\x02R\x06digest\x12\x19\n" +
	"\x04repo\x18\n" +
	" \x01(\tB\x05\xaa\x01\x02\b\x02R\x04repo\x12\x17\n" +
	"\x03tag\x18\v \x01(\tB\x05\xaa\x01\x02\b\x02R\x03tag\x12N\n" +
	"\x15date_last_distributed\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x13dateLastDistributed\x12@\n" +
	"\x0edate_last_used\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\fdateLastUsed\x12B\n" +
	"\x0fdate_first_seen\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\rdateFirstSeen\x12\x1d\n" +
	"\x06pinned\x18\x10 \x01(\bB\x05\xaa\x01\x02\b\x02R\x06pinned\x12\x1c\n" +
	"\x06in_use\x18\x11 \x01(\bB\x05\xaa\x01\x02\b\x02R\x05inUse\"b\n" +
	"\x0fImageGetRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.gantry.ImageRefR\x03ref\x12+\n" +
	"\x06select\x18\x02 \x01(\v2\x13.gantry.ImageSelectR\x06select\"Z\n" +
	"\bImageRef\x12\x10\n" +
	"\x02id\x18\x01 \x01(\fH\x00R\x02id\x125\n" +
	"\alocator\x18\x02 \x01(\v2\x19.gantry.ImageRefByLocatorH\x00R\alocatorB\x05\n" +
	"\x03key\"M\n" +
	"\x11ImageRefByLocator\x12&\n" +
	"\x05store\x18\x02 \x01(\v2\x10.gantry.StoreRefR\x05store\x12\x10\n" +
	"\x03ref\x18\b \x01(\tR\x03ref\"\xcb\x02\n" +
	"\vImageSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12)\n" +
	"\x05store\x18\x02 \x01(\v2\x13.gantry.StoreSelectR\x05store\x12\x10\n" +
	"\x03ref\x18\b \x01(\bR\x03ref\x12\x16\n" +
	"\x06digest\x18\t \x01(\bR\x06digest\x12\x12\n" +
	"\x04repo\x18\n" +
	" \x01(\bR\x04repo\x12\x10\n" +
	"\x03tag\x18\v \x01(\bR\x03tag\x122\n" +
	"\x15date_last_distributed\x18\r \x01(\bR\x13dateLastDistributed\x12$\n" +
	"\x0edate_last_used\x18\x0e \x01(\bR\fdateLastUsed\x12&\n" +
	"\x0fdate_first_seen\x18\x0f \x01(\bR\rdateFirstSeen\x12\x16\n" +
	"\x06pinned\x18\x10 \x01(\bR\x06pinned\x12\x15\n" +
	"\x06in_use\x18\x11 \x01(\bR\x05inUse\"\x90\x02\n" +
	"\x11ImagePatchRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.gantry.ImageRefR\x03ref\x12\x16\n" +
	"\x06digest\x18\x11 \x01(\tR\x06digest\x12N\n" +
	"\x15date_last_distributed\x18\x19 \x01(\v2\x1a.google.protobuf.TimestampR\x13dateLastDistributed\x12@\n" +
	"\x0edate_last_used\x18\x1b \x01(\v2\x1a.google.protobuf.TimestampR\fdateLastUsed\x12\x16\n" +
	"\x06pinned\x18\x1f \x01(\bR\x06pinned\x12\x15\n" +
	"\x06in_use\x18! \x01(\bR\x05inUse\"\xcb\x01\n" +
	"\x10ImageListRequest\x12&\n" +
	"\x05store\x18\x01 \x01(\v2\x10.gantry.StoreRefR\x05store\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x10\n" +
	"\x03ref\x18\x03 \x01(\tR\x03ref\x12\x16\n" +
	"\x06pinned\x18\x04 \x01(\bR\x06pinned\x12\x15\n" +
	"\x06in_use\x18\x05 \x01(\bR\x05inUse\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\v \x01(\tR\tpageToken\"\x93\x01\n" +
	"\x11ImageListResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.gantry.ImageR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x121\n" +
	"\buntagged\x18\x03 \x03(\v2\x15.gantry.UntaggedImageR\buntagged\"c\n" +
	"\rUntaggedImage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12B\n" +
	"\x0fdate_first_seen\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\rdateFirstSeen2\x8f\x02\n" +
	"\fImageService\x12-\n" +
	"\x03Add\x12\x17.gantry.ImageAddRequest\x1a\r.gantry.Image\x12-\n" +
	"\x03Get\x12\x17.gantry.ImageGetRequest\x1a\r.gantry.Image\x121\n" +
	"\x05Patch\x12\x19.gantry.ImagePatchRequest\x1a\r.gantry.Image\x121\n" +
	"\x05Erase\x12\x10.gantry.ImageRef\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\x04List\x12\x18.gantry.ImageListRequest\x1a\x19.gantry.ImageListResponseB\x1fZ\x1dgithub.com/lesomnus/gantry/pbb\beditionsp\xe8\a"

var file_gantry_image_svc_g_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_gantry_image_svc_g_proto_goTypes = []any{
	(*ImageAddRequest)(nil),       // 0: gantry.ImageAddRequest
	(*ImageGetRequest)(nil),       // 1: gantry.ImageGetRequest
	(*ImageRef)(nil),              // 2: gantry.ImageRef
	(*ImageRefByLocator)(nil),     // 3: gantry.ImageRefByLocator
	(*ImageSelect)(nil),           // 4: gantry.ImageSelect
	(*ImagePatchRequest)(nil),     // 5: gantry.ImagePatchRequest
	(*ImageListRequest)(nil),      // 6: gantry.ImageListRequest
	(*ImageListResponse)(nil),     // 7: gantry.ImageListResponse
	(*UntaggedImage)(nil),         // 8: gantry.UntaggedImage
	(*StoreRef)(nil),              // 9: gantry.StoreRef
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*StoreSelect)(nil),           // 11: gantry.StoreSelect
	(*Image)(nil),                 // 12: gantry.Image
	(*emptypb.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_gantry_image_svc_g_proto_depIdxs = []int32{
	9,  // 0: gantry.ImageAddRequest.store:type_name -> gantry.StoreRef
	10, // 1: gantry.ImageAddRequest.date_last_distributed:type_name -> google.protobuf.Timestamp
	10, // 2: gantry.ImageAddRequest.date_last_used:type_name -> google.protobuf.Timestamp
	10, // 3: gantry.ImageAddRequest.date_first_seen:type_name -> google.protobuf.Timestamp
	2,  // 4: gantry.ImageGetRequest.ref:type_name -> gantry.ImageRef
	4,  // 5: gantry.ImageGetRequest.select:type_name -> gantry.ImageSelect
	3,  // 6: gantry.ImageRef.locator:type_name -> gantry.ImageRefByLocator
	9,  // 7: gantry.ImageRefByLocator.store:type_name -> gantry.StoreRef
	11, // 8: gantry.ImageSelect.store:type_name -> gantry.StoreSelect
	2,  // 9: gantry.ImagePatchRequest.ref:type_name -> gantry.ImageRef
	10, // 10: gantry.ImagePatchRequest.date_last_distributed:type_name -> google.protobuf.Timestamp
	10, // 11: gantry.ImagePatchRequest.date_last_used:type_name -> google.protobuf.Timestamp
	9,  // 12: gantry.ImageListRequest.store:type_name -> gantry.StoreRef
	12, // 13: gantry.ImageListResponse.items:type_name -> gantry.Image
	8,  // 14: gantry.ImageListResponse.untagged:type_name -> gantry.UntaggedImage
	10, // 15: gantry.UntaggedImage.date_first_seen:type_name -> google.protobuf.Timestamp
	0,  // 16: gantry.ImageService.Add:input_type -> gantry.ImageAddRequest
	1,  // 17: gantry.ImageService.Get:input_type -> gantry.ImageGetRequest
	5,  // 18: gantry.ImageService.Patch:input_type -> gantry.ImagePatchRequest
	2,  // 19: gantry.ImageService.Erase:input_type -> gantry.ImageRef
	6,  // 20: gantry.ImageService.List:input_type -> gantry.ImageListRequest
	12, // 21: gantry.ImageService.Add:output_type -> gantry.Image
	12, // 22: gantry.ImageService.Get:output_type -> gantry.Image
	12, // 23: gantry.ImageService.Patch:output_type -> gantry.Image
	13, // 24: gantry.ImageService.Erase:output_type -> google.protobuf.Empty
	7,  // 25: gantry.ImageService.List:output_type -> gantry.ImageListResponse
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_gantry_image_svc_g_proto_init() }
func file_gantry_image_svc_g_proto_init() {
	if File_gantry_image_svc_g_proto != nil {
		return
	}
	file_gantry_image_proto_init()
	file_gantry_store_svc_g_proto_init()
	file_gantry_image_svc_g_proto_msgTypes[2].OneofWrappers = []any{
		(*imageRef_Id)(nil),
		(*imageRef_Locator)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gantry_image_svc_g_proto_rawDesc), len(file_gantry_image_svc_g_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gantry_image_svc_g_proto_goTypes,
		DependencyIndexes: file_gantry_image_svc_g_proto_depIdxs,
		MessageInfos:      file_gantry_image_svc_g_proto_msgTypes,
	}.Build()
	File_gantry_image_svc_g_proto = out.File
	file_gantry_image_svc_g_proto_goTypes = nil
	file_gantry_image_svc_g_proto_depIdxs = nil
}
