// Code generated by protoc-gen-orm-go. DO NOT EDIT.

package pb

import (
	bytes "bytes"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

func (x *ImageRef) Pick() *ImageGetRequest {
	return ImageGetRequest_builder{Ref: x}.Build()
}

func (x *Image) Ref() *ImageRef {
	if v := x.GetId(); len(v) > 0 {
		return ImageById(v)
	}
	{
		v1 := x.GetStore()
		v2 := x.GetRef()
		if v1 != nil && len(v2) > 0 {
			return ImageByLocator(v1.Ref(), v2)
		}
	}

	return nil
}

func (x *Image) Pick() *ImageGetRequest {
	return x.Ref().Pick()
}

func (x *ImageRef) Picks(v *Image) bool {
	switch x.WhichKey() {
	case ImageRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	case ImageRef_Locator_case:
		x := x.GetLocator()
		return (x.GetStore().Picks(v.GetStore())) &&
			(x.GetRef() == v.GetRef())
	default:
		return false
	}
}

func (x *ImageGetRequest) WithSelect(f func(s *ImageSelect)) *ImageGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&ImageSelect{})
	}
	f(x.GetSelect())
	return x
}

func (x *Image) MarshalJSON() ([]byte, error) { return protojson.Marshal(x) }
func (x *Image) UnmarshalJSON(b []byte) error { return protojson.Unmarshal(b, x) }

func ImageById(v []byte) *ImageRef {
	x := &ImageRef{}
	x.SetId(v)
	return x
}

func ImageGetById(v []byte) *ImageGetRequest {
	return ImageGetRequest_builder{Ref: ImageById(v)}.Build()
}

func ImageByLocator(store *StoreRef, ref string) *ImageRef {
	x := &ImageRefByLocator{}
	x.SetStore(store)
	x.SetRef(ref)
	return ImageRef_builder{Locator: x}.Build()
}

func ImageGetByLocator(store *StoreRef, ref string) *ImageGetRequest {
	return ImageGetRequest_builder{Ref: ImageByLocator(store, ref)}.Build()
}
