// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: gantry/job.proto

package pb

import (
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobState int32

const (
	JobState_JOB_STATE_UNSPECIFIED JobState = 0
	JobState_JOB_STATE_PENDING     JobState = 1
	JobState_JOB_STATE_RUNNING     JobState = 2
	JobState_JOB_STATE_DONE        JobState = 3
	JobState_JOB_STATE_FAILED      JobState = 4
	JobState_JOB_STATE_CANCELED    JobState = 5
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "JOB_STATE_UNSPECIFIED",
		1: "JOB_STATE_PENDING",
		2: "JOB_STATE_RUNNING",
		3: "JOB_STATE_DONE",
		4: "JOB_STATE_FAILED",
		5: "JOB_STATE_CANCELED",
	}
	JobState_value = map[string]int32{
		"JOB_STATE_UNSPECIFIED": 0,
		"JOB_STATE_PENDING":     1,
		"JOB_STATE_RUNNING":     2,
		"JOB_STATE_DONE":        3,
		"JOB_STATE_FAILED":      4,
		"JOB_STATE_CANCELED":    5,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_gantry_job_proto_enumTypes[0].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_gantry_job_proto_enumTypes[0]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type VerifyMode int32

const (
	VerifyMode_VERIFY_MODE_UNSPECIFIED       VerifyMode = 0
	VerifyMode_VERIFY_MODE_OFF               VerifyMode = 1
	VerifyMode_VERIFY_MODE_VERIFY_IF_PRESENT VerifyMode = 2
	VerifyMode_VERIFY_MODE_REQUIRE           VerifyMode = 3
)

// Enum value maps for VerifyMode.
var (
	VerifyMode_name = map[int32]string{
		0: "VERIFY_MODE_UNSPECIFIED",
		1: "VERIFY_MODE_OFF",
		2: "VERIFY_MODE_VERIFY_IF_PRESENT",
		3: "VERIFY_MODE_REQUIRE",
	}
	VerifyMode_value = map[string]int32{
		"VERIFY_MODE_UNSPECIFIED":       0,
		"VERIFY_MODE_OFF":               1,
		"VERIFY_MODE_VERIFY_IF_PRESENT": 2,
		"VERIFY_MODE_REQUIRE":           3,
	}
)

func (x VerifyMode) Enum() *VerifyMode {
	p := new(VerifyMode)
	*p = x
	return p
}

func (x VerifyMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerifyMode) Descriptor() protoreflect.EnumDescriptor {
	return file_gantry_job_proto_enumTypes[1].Descriptor()
}

func (VerifyMode) Type() protoreflect.EnumType {
	return &file_gantry_job_proto_enumTypes[1]
}

func (x VerifyMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type TransferState int32

const (
	TransferState_TRANSFER_STATE_UNSPECIFIED TransferState = 0
	TransferState_TRANSFER_STATE_PENDING     TransferState = 1
	TransferState_TRANSFER_STATE_RUNNING     TransferState = 2
	TransferState_TRANSFER_STATE_DONE        TransferState = 3
	TransferState_TRANSFER_STATE_EXISTS      TransferState = 4
	TransferState_TRANSFER_STATE_FAILED      TransferState = 5
)

// Enum value maps for TransferState.
var (
	TransferState_name = map[int32]string{
		0: "TRANSFER_STATE_UNSPECIFIED",
		1: "TRANSFER_STATE_PENDING",
		2: "TRANSFER_STATE_RUNNING",
		3: "TRANSFER_STATE_DONE",
		4: "TRANSFER_STATE_EXISTS",
		5: "TRANSFER_STATE_FAILED",
	}
	TransferState_value = map[string]int32{
		"TRANSFER_STATE_UNSPECIFIED": 0,
		"TRANSFER_STATE_PENDING":     1,
		"TRANSFER_STATE_RUNNING":     2,
		"TRANSFER_STATE_DONE":        3,
		"TRANSFER_STATE_EXISTS":      4,
		"TRANSFER_STATE_FAILED":      5,
	}
)

func (x TransferState) Enum() *TransferState {
	p := new(TransferState)
	*p = x
	return p
}

func (x TransferState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferState) Descriptor() protoreflect.EnumDescriptor {
	return file_gantry_job_proto_enumTypes[2].Descriptor()
}

func (TransferState) Type() protoreflect.EnumType {
	return &file_gantry_job_proto_enumTypes[2]
}

func (x TransferState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type LayerState int32

const (
	LayerState_LAYER_STATE_UNSPECIFIED LayerState = 0
	LayerState_LAYER_STATE_PENDING     LayerState = 1
	LayerState_LAYER_STATE_PULLING     LayerState = 2
	LayerState_LAYER_STATE_DONE        LayerState = 3
	LayerState_LAYER_STATE_EXISTS      LayerState = 4
	LayerState_LAYER_STATE_FAILED      LayerState = 5
)

// Enum value maps for LayerState.
var (
	LayerState_name = map[int32]string{
		0: "LAYER_STATE_UNSPECIFIED",
		1: "LAYER_STATE_PENDING",
		2: "LAYER_STATE_PULLING",
		3: "LAYER_STATE_DONE",
		4: "LAYER_STATE_EXISTS",
		5: "LAYER_STATE_FAILED",
	}
	LayerState_value = map[string]int32{
		"LAYER_STATE_UNSPECIFIED": 0,
		"LAYER_STATE_PENDING":     1,
		"LAYER_STATE_PULLING":     2,
		"LAYER_STATE_DONE":        3,
		"LAYER_STATE_EXISTS":      4,
		"LAYER_STATE_FAILED":      5,
	}
)

func (x LayerState) Enum() *LayerState {
	p := new(LayerState)
	*p = x
	return p
}

func (x LayerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LayerState) Descriptor() protoreflect.EnumDescriptor {
	return file_gantry_job_proto_enumTypes[3].Descriptor()
}

func (LayerState) Type() protoreflect.EnumType {
	return &file_gantry_job_proto_enumTypes[3]
}

func (x LayerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Admission-time signature verification audit record; absent when
// verification is disabled.
type Verification struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Mode     VerifyMode             `protobuf:"varint,1,opt,name=mode,enum=gantry.VerifyMode"`
	xxx_hidden_Verified bool                   `protobuf:"varint,2,opt,name=verified"`
	xxx_hidden_Digest   string                 `protobuf:"bytes,3,opt,name=digest"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Verification) Reset() {
	*x = Verification{}
	mi := &file_gantry_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verification) ProtoMessage() {}

func (x *Verification) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Verification) GetMode() VerifyMode {
	if x != nil {
		return x.xxx_hidden_Mode
	}
	return VerifyMode_VERIFY_MODE_UNSPECIFIED
}

func (x *Verification) GetVerified() bool {
	if x != nil {
		return x.xxx_hidden_Verified
	}
	return false
}

func (x *Verification) GetDigest() string {
	if x != nil {
		return x.xxx_hidden_Digest
	}
	return ""
}

func (x *Verification) SetMode(v VerifyMode) {
	x.xxx_hidden_Mode = v
}

func (x *Verification) SetVerified(v bool) {
	x.xxx_hidden_Verified = v
}

func (x *Verification) SetDigest(v string) {
	x.xxx_hidden_Digest = v
}

type Verification_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Mode     VerifyMode
	Verified bool
	// The digest the job was pinned to when verified.
	Digest string
}

func (b0 Verification_builder) Build() *Verification {
	m0 := &Verification{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Mode = b.Mode
	x.xxx_hidden_Verified = b.Verified
	x.xxx_hidden_Digest = b.Digest
	return m0
}

// Per-blob progress of a transfer step.
type Layer struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Digest   string                 `protobuf:"bytes,1,opt,name=digest"`
	xxx_hidden_Platform string                 `protobuf:"bytes,2,opt,name=platform"`
	xxx_hidden_Total    int64                  `protobuf:"varint,3,opt,name=total"`
	xxx_hidden_Done     int64                  `protobuf:"varint,4,opt,name=done"`
	xxx_hidden_State    LayerState             `protobuf:"varint,5,opt,name=state,enum=gantry.LayerState"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Layer) Reset() {
	*x = Layer{}
	mi := &file_gantry_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Layer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer) ProtoMessage() {}

func (x *Layer) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Layer) GetDigest() string {
	if x != nil {
		return x.xxx_hidden_Digest
	}
	return ""
}

func (x *Layer) GetPlatform() string {
	if x != nil {
		return x.xxx_hidden_Platform
	}
	return ""
}

func (x *Layer) GetTotal() int64 {
	if x != nil {
		return x.xxx_hidden_Total
	}
	return 0
}

func (x *Layer) GetDone() int64 {
	if x != nil {
		return x.xxx_hidden_Done
	}
	return 0
}

func (x *Layer) GetState() LayerState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return LayerState_LAYER_STATE_UNSPECIFIED
}

func (x *Layer) SetDigest(v string) {
	x.xxx_hidden_Digest = v
}

func (x *Layer) SetPlatform(v string) {
	x.xxx_hidden_Platform = v
}

func (x *Layer) SetTotal(v int64) {
	x.xxx_hidden_Total = v
}

func (x *Layer) SetDone(v int64) {
	x.xxx_hidden_Done = v
}

func (x *Layer) SetState(v LayerState) {
	x.xxx_hidden_State = v
}

type Layer_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Digest   string
	Platform string
	Total    int64
	Done     int64
	State    LayerState
}

func (b0 Layer_builder) Build() *Layer {
	m0 := &Layer{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Digest = b.Digest
	x.xxx_hidden_Platform = b.Platform
	x.xxx_hidden_Total = b.Total
	x.xxx_hidden_Done = b.Done
	x.xxx_hidden_State = b.State
	return m0
}

// One step of a job: a registry copy or an engine pull.
type Transfer struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Store      string                 `protobuf:"bytes,1,opt,name=store"`
	xxx_hidden_Kind       StoreKind              `protobuf:"varint,2,opt,name=kind,enum=gantry.StoreKind"`
	xxx_hidden_Source     string                 `protobuf:"bytes,3,opt,name=source"`
	xxx_hidden_Ref        string                 `protobuf:"bytes,4,opt,name=ref"`
	xxx_hidden_Digest     string                 `protobuf:"bytes,5,opt,name=digest"`
	xxx_hidden_State      TransferState          `protobuf:"varint,6,opt,name=state,enum=gantry.TransferState"`
	xxx_hidden_BytesTotal int64                  `protobuf:"varint,7,opt,name=bytes_total,json=bytesTotal"`
	xxx_hidden_BytesDone  int64                  `protobuf:"varint,8,opt,name=bytes_done,json=bytesDone"`
	xxx_hidden_Layers     *[]*Layer              `protobuf:"bytes,9,rep,name=layers"`
	xxx_hidden_Error      string                 `protobuf:"bytes,10,opt,name=error"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_gantry_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Transfer) GetStore() string {
	if x != nil {
		return x.xxx_hidden_Store
	}
	return ""
}

func (x *Transfer) GetKind() StoreKind {
	if x != nil {
		return x.xxx_hidden_Kind
	}
	return StoreKind_STORE_KIND_UNSPECIFIED
}

func (x *Transfer) GetSource() string {
	if x != nil {
		return x.xxx_hidden_Source
	}
	return ""
}

func (x *Transfer) GetRef() string {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return ""
}

func (x *Transfer) GetDigest() string {
	if x != nil {
		return x.xxx_hidden_Digest
	}
	return ""
}

func (x *Transfer) GetState() TransferState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return TransferState_TRANSFER_STATE_UNSPECIFIED
}

func (x *Transfer) GetBytesTotal() int64 {
	if x != nil {
		return x.xxx_hidden_BytesTotal
	}
	return 0
}

func (x *Transfer) GetBytesDone() int64 {
	if x != nil {
		return x.xxx_hidden_BytesDone
	}
	return 0
}

func (x *Transfer) GetLayers() []*Layer {
	if x != nil {
		if x.xxx_hidden_Layers != nil {
			return *x.xxx_hidden_Layers
		}
	}
	return nil
}

func (x *Transfer) GetError() string {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return ""
}

func (x *Transfer) SetStore(v string) {
	x.xxx_hidden_Store = v
}

func (x *Transfer) SetKind(v StoreKind) {
	x.xxx_hidden_Kind = v
}

func (x *Transfer) SetSource(v string) {
	x.xxx_hidden_Source = v
}

func (x *Transfer) SetRef(v string) {
	x.xxx_hidden_Ref = v
}

func (x *Transfer) SetDigest(v string) {
	x.xxx_hidden_Digest = v
}

func (x *Transfer) SetState(v TransferState) {
	x.xxx_hidden_State = v
}

func (x *Transfer) SetBytesTotal(v int64) {
	x.xxx_hidden_BytesTotal = v
}

func (x *Transfer) SetBytesDone(v int64) {
	x.xxx_hidden_BytesDone = v
}

func (x *Transfer) SetLayers(v []*Layer) {
	x.xxx_hidden_Layers = &v
}

func (x *Transfer) SetError(v string) {
	x.xxx_hidden_Error = v
}

type Transfer_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Store  string
	Kind   StoreKind
	Source string
	// The reference placed in the target.
	Ref string
	// Manifest/index digest the step was anchored to, when known.
	Digest     string
	State      TransferState
	BytesTotal int64
	BytesDone  int64
	Layers     []*Layer
	Error      string
}

func (b0 Transfer_builder) Build() *Transfer {
	m0 := &Transfer{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Store = b.Store
	x.xxx_hidden_Kind = b.Kind
	x.xxx_hidden_Source = b.Source
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Digest = b.Digest
	x.xxx_hidden_State = b.State
	x.xxx_hidden_BytesTotal = b.BytesTotal
	x.xxx_hidden_BytesDone = b.BytesDone
	x.xxx_hidden_Layers = &b.Layers
	x.xxx_hidden_Error = b.Error
	return m0
}

// A move of one image from a source registry into a target store.
type Job struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id            string                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Ref           string                 `protobuf:"bytes,2,opt,name=ref"`
	xxx_hidden_Source        *Store                 `protobuf:"bytes,3,opt,name=source"`
	xxx_hidden_Target        *Store                 `protobuf:"bytes,4,opt,name=target"`
	xxx_hidden_Platforms     []string               `protobuf:"bytes,5,rep,name=platforms"`
	xxx_hidden_CopyReferrers bool                   `protobuf:"varint,6,opt,name=copy_referrers,json=copyReferrers"`
	xxx_hidden_As            []string               `protobuf:"bytes,14,rep,name=as"`
	xxx_hidden_State         JobState               `protobuf:"varint,7,opt,name=state,enum=gantry.JobState"`
	xxx_hidden_Error         string                 `protobuf:"bytes,8,opt,name=error"`
	xxx_hidden_Verification  *Verification          `protobuf:"bytes,9,opt,name=verification"`
	xxx_hidden_Transfers     *[]*Transfer           `protobuf:"bytes,10,rep,name=transfers"`
	xxx_hidden_CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt"`
	xxx_hidden_StartedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=started_at,json=startedAt"`
	xxx_hidden_EndedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=ended_at,json=endedAt"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_gantry_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Job) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *Job) GetRef() string {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return ""
}

func (x *Job) GetSource() *Store {
	if x != nil {
		return x.xxx_hidden_Source
	}
	return nil
}

func (x *Job) GetTarget() *Store {
	if x != nil {
		return x.xxx_hidden_Target
	}
	return nil
}

func (x *Job) GetPlatforms() []string {
	if x != nil {
		return x.xxx_hidden_Platforms
	}
	return nil
}

func (x *Job) GetCopyReferrers() bool {
	if x != nil {
		return x.xxx_hidden_CopyReferrers
	}
	return false
}

func (x *Job) GetAs() []string {
	if x != nil {
		return x.xxx_hidden_As
	}
	return nil
}

func (x *Job) GetState() JobState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *Job) GetError() string {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return ""
}

func (x *Job) GetVerification() *Verification {
	if x != nil {
		return x.xxx_hidden_Verification
	}
	return nil
}

func (x *Job) GetTransfers() []*Transfer {
	if x != nil {
		if x.xxx_hidden_Transfers != nil {
			return *x.xxx_hidden_Transfers
		}
	}
	return nil
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *Job) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_StartedAt
	}
	return nil
}

func (x *Job) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_EndedAt
	}
	return nil
}

func (x *Job) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *Job) SetRef(v string) {
	x.xxx_hidden_Ref = v
}

func (x *Job) SetSource(v *Store) {
	x.xxx_hidden_Source = v
}

func (x *Job) SetTarget(v *Store) {
	x.xxx_hidden_Target = v
}

func (x *Job) SetPlatforms(v []string) {
	x.xxx_hidden_Platforms = v
}

func (x *Job) SetCopyReferrers(v bool) {
	x.xxx_hidden_CopyReferrers = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 14)
}

func (x *Job) SetAs(v []string) {
	x.xxx_hidden_As = v
}

func (x *Job) SetState(v JobState) {
	x.xxx_hidden_State = v
}

func (x *Job) SetError(v string) {
	x.xxx_hidden_Error = v
}

func (x *Job) SetVerification(v *Verification) {
	x.xxx_hidden_Verification = v
}

func (x *Job) SetTransfers(v []*Transfer) {
	x.xxx_hidden_Transfers = &v
}

func (x *Job) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Job) SetStartedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_StartedAt = v
}

func (x *Job) SetEndedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_EndedAt = v
}

func (x *Job) HasSource() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Source != nil
}

func (x *Job) HasTarget() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Target != nil
}

func (x *Job) HasCopyReferrers() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Job) HasVerification() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Verification != nil
}

func (x *Job) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *Job) HasStartedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StartedAt != nil
}

func (x *Job) HasEndedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EndedAt != nil
}

func (x *Job) ClearSource() {
	x.xxx_hidden_Source = nil
}

func (x *Job) ClearTarget() {
	x.xxx_hidden_Target = nil
}

func (x *Job) ClearCopyReferrers() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_CopyReferrers = false
}

func (x *Job) ClearVerification() {
	x.xxx_hidden_Verification = nil
}

func (x *Job) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *Job) ClearStartedAt() {
	x.xxx_hidden_StartedAt = nil
}

func (x *Job) ClearEndedAt() {
	x.xxx_hidden_EndedAt = nil
}

type Job_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Server-generated, e.g. "job_1f2e...".
	Id string
	// Image reference to move, e.g. "docker.io/library/redis:7".
	Ref string
	// Source registry; defaults to the ref's registry. Unlike the REST API,
	// the gRPC surface addresses declared stores only — bare registry hosts
	// (allow_unknown_stores) are not expressible through a StoreRef.
	Source *Store
	// Target store: a registry (gantry copies) or an engine (daemon pulls).
	Target *Store
	// Registry target: platforms to copy (empty = all). Engine
	// target: the single platform to pull (empty = daemon's).
	Platforms []string
	// Copy source referrer artifacts (signatures) along with the image.
	// Absent = server default (on when the job is verified).
	CopyReferrers *bool
	// Engine target only: record the pulled image under these names
	// instead of the pull reference, so a cache-fed engine keeps the image
	// under its upstream name (e.g. "docker.io/library/redis:7"). Tag
	// references only; non-empty replaces the pull-reference name entirely —
	// include it in the list to keep it.
	As           []string
	State        JobState
	Error        string
	Verification *Verification
	Transfers    []*Transfer
	CreatedAt    *timestamppb.Timestamp
	StartedAt    *timestamppb.Timestamp
	EndedAt      *timestamppb.Timestamp
}

func (b0 Job_builder) Build() *Job {
	m0 := &Job{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Source = b.Source
	x.xxx_hidden_Target = b.Target
	x.xxx_hidden_Platforms = b.Platforms
	if b.CopyReferrers != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 14)
		x.xxx_hidden_CopyReferrers = *b.CopyReferrers
	}
	x.xxx_hidden_As = b.As
	x.xxx_hidden_State = b.State
	x.xxx_hidden_Error = b.Error
	x.xxx_hidden_Verification = b.Verification
	x.xxx_hidden_Transfers = &b.Transfers
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_StartedAt = b.StartedAt
	x.xxx_hidden_EndedAt = b.EndedAt
	return m0
}

var File_gantry_job_proto protoreflect.FileDescriptor

const file_gantry_job_proto_rawDesc = "" +
	"\n" +
	"\x10gantry/job.proto\x12\x06gantry\x1a\x12gantry/store.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\torm.proto\"j\n" +
	"\fVerification\x12&\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x12.gantry.VerifyModeR\x04mode\x12\x1a\n" +
	"\bverified\x18\x02 \x01(\bR\bverified\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\"\x8f\x01\n" +
	"\x05Layer\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12\x12\n" +
	"\x04done\x18\x04 \x01(\x03R\x04done\x12(\n" +
	"\x05state\x18\x05 \x01(\x0e2\x12.gantry.LayerStateR\x05state\"\xb3\x02\n" +
	"\bTransfer\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12%\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x11.gantry.StoreKindR\x04kind\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x10\n" +
	"\x03ref\x18\x04 \x01(\tR\x03ref\x12\x16\n" +
	"\x06digest\x18\x05 \x01(\tR\x06digest\x12+\n" +
	"\x05state\x18\x06 \x01(\x0e2\x15.gantry.TransferStateR\x05state\x12\x1f\n" +
	"\vbytes_total\x18\a \x01(\x03R\n" +
	"bytesTotal\x12\x1d\n" +
	"\n" +
	"bytes_done\x18\b \x01(\x03R\tbytesDone\x12%\n" +
	"\x06layers\x18\t \x03(\v2\r.gantry.LayerR\x06layers\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\"\xf6\x04\n" +
	"\x03Job\x12\x19\n" +
	"\x02id\x18\x01 \x01(\tB\t\xea\x82\x16\x05(\x01\x82\x01\x00R\x02id\x12\x18\n" +
	"\x03ref\x18\x02 \x01(\tB\x06\xea\x82\x16\x02@\x01R\x03ref\x12/\n" +
	"\x06source\x18\x03 \x01(\v2\r.gantry.StoreB\b\xf2\x82\x16\x048\x01@\x01R\x06source\x12-\n" +
	"\x06target\x18\x04 \x01(\v2\r.gantry.StoreB\x06\xf2\x82\x16\x02@\x01R\x06target\x12$\n" +
	"\tplatforms\x18\x05 \x03(\tB\x06\xea\x82\x16\x02@\x01R\tplatforms\x122\n" +
	"\x0ecopy_referrers\x18\x06 \x01(\bB\v\xea\x82\x16\x02@\x01\xaa\x01\x02\b\x01R\rcopyReferrers\x12\x16\n" +
	"\x02as\x18\x0e \x03(\tB\x06\xea\x82\x16\x02@\x01R\x02as\x12&\n" +
	"\x05state\x18\a \x01(\x0e2\x10.gantry.JobStateR\x05state\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x128\n" +
	"\fverification\x18\t \x01(\v2\x14.gantry.VerificationR\fverification\x12.\n" +
	"\ttransfers\x18\n" +
	" \x03(\v2\x10.gantry.TransferR\ttransfers\x12D\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampB\t\xea\x82\x16\x05@\x01\x82\x01\x00R\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt:\b\xca\xfc\x15\x04\x12\x02\x10\x01*\x95\x01\n" +
	"\bJobState\x12\x19\n" +
	"\x15JOB_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11JOB_STATE_PENDING\x10\x01\x12\x15\n" +
	"\x11JOB_STATE_RUNNING\x10\x02\x12\x12\n" +
	"\x0eJOB_STATE_DONE\x10\x03\x12\x14\n" +
	"\x10JOB_STATE_FAILED\x10\x04\x12\x16\n" +
	"\x12JOB_STATE_CANCELED\x10\x05*z\n" +
	"\n" +
	"VerifyMode\x12\x1b\n" +
	"\x17VERIFY_MODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fVERIFY_MODE_OFF\x10\x01\x12!\n" +
	"\x1dVERIFY_MODE_VERIFY_IF_PRESENT\x10\x02\x12\x17\n" +
	"\x13VERIFY_MODE_REQUIRE\x10\x03*\xb6\x01\n" +
	"\rTransferState\x12\x1e\n" +
	"\x1aTRANSFER_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TRANSFER_STATE_PENDING\x10\x01\x12\x1a\n" +
	"\x16TRANSFER_STATE_RUNNING\x10\x02\x12\x17\n" +
	"\x13TRANSFER_STATE_DONE\x10\x03\x12\x19\n" +
	"\x15TRANSFER_STATE_EXISTS\x10\x04\x12\x19\n" +
	"\x15TRANSFER_STATE_FAILED\x10\x05*\xa1\x01\n" +
	"\n" +
	"LayerState\x12\x1b\n" +
	"\x17LAYER_STATE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13LAYER_STATE_PENDING\x10\x01\x12\x17\n" +
	"\x13LAYER_STATE_PULLING\x10\x02\x12\x14\n" +
	"\x10LAYER_STATE_DONE\x10\x03\x12\x16\n" +
	"\x12LAYER_STATE_EXISTS\x10\x04\x12\x16\n" +
	"\x12LAYER_STATE_FAILED\x10\x05B$Z\x1dgithub.com/lesomnus/gantry/pb\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_gantry_job_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_gantry_job_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gantry_job_proto_goTypes = []any{
	(JobState)(0),                 // 0: gantry.JobState
	(VerifyMode)(0),               // 1: gantry.VerifyMode
	(TransferState)(0),            // 2: gantry.TransferState
	(LayerState)(0),               // 3: gantry.LayerState
	(*Verification)(nil),          // 4: gantry.Verification
	(*Layer)(nil),                 // 5: gantry.Layer
	(*Transfer)(nil),              // 6: gantry.Transfer
	(*Job)(nil),                   // 7: gantry.Job
	(StoreKind)(0),                // 8: gantry.StoreKind
	(*Store)(nil),                 // 9: gantry.Store
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_gantry_job_proto_depIdxs = []int32{
	1,  // 0: gantry.Verification.mode:type_name -> gantry.VerifyMode
	3,  // 1: gantry.Layer.state:type_name -> gantry.LayerState
	8,  // 2: gantry.Transfer.kind:type_name -> gantry.StoreKind
	2,  // 3: gantry.Transfer.state:type_name -> gantry.TransferState
	5,  // 4: gantry.Transfer.layers:type_name -> gantry.Layer
	9,  // 5: gantry.Job.source:type_name -> gantry.Store
	9,  // 6: gantry.Job.target:type_name -> gantry.Store
	0,  // 7: gantry.Job.state:type_name -> gantry.JobState
	4,  // 8: gantry.Job.verification:type_name -> gantry.Verification
	6,  // 9: gantry.Job.transfers:type_name -> gantry.Transfer
	10, // 10: gantry.Job.created_at:type_name -> google.protobuf.Timestamp
	10, // 11: gantry.Job.started_at:type_name -> google.protobuf.Timestamp
	10, // 12: gantry.Job.ended_at:type_name -> google.protobuf.Timestamp
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_gantry_job_proto_init() }
func file_gantry_job_proto_init() {
	if File_gantry_job_proto != nil {
		return
	}
	file_gantry_store_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gantry_job_proto_rawDesc), len(file_gantry_job_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gantry_job_proto_goTypes,
		DependencyIndexes: file_gantry_job_proto_depIdxs,
		EnumInfos:         file_gantry_job_proto_enumTypes,
		MessageInfos:      file_gantry_job_proto_msgTypes,
	}.Build()
	File_gantry_job_proto = out.File
	file_gantry_job_proto_goTypes = nil
	file_gantry_job_proto_depIdxs = nil
}
