// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: gantry/job_svc.g.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobAddRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id            *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Ref           string                 `protobuf:"bytes,2,opt,name=ref"`
	xxx_hidden_From          *StoreRef              `protobuf:"bytes,3,opt,name=from"`
	xxx_hidden_To            *StoreRef              `protobuf:"bytes,4,opt,name=to"`
	xxx_hidden_Platforms     []string               `protobuf:"bytes,5,rep,name=platforms"`
	xxx_hidden_CopyReferrers bool                   `protobuf:"varint,6,opt,name=copy_referrers,json=copyReferrers"`
	xxx_hidden_State         JobState               `protobuf:"varint,7,opt,name=state,enum=gantry.JobState"`
	xxx_hidden_Error         string                 `protobuf:"bytes,8,opt,name=error"`
	xxx_hidden_Verification  *Verification          `protobuf:"bytes,9,opt,name=verification"`
	xxx_hidden_Transfers     *[]*Transfer           `protobuf:"bytes,10,rep,name=transfers"`
	xxx_hidden_CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt"`
	xxx_hidden_StartedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=started_at,json=startedAt"`
	xxx_hidden_EndedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=ended_at,json=endedAt"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *JobAddRequest) Reset() {
	*x = JobAddRequest{}
	mi := &file_gantry_job_svc_g_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAddRequest) ProtoMessage() {}

func (x *JobAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_job_svc_g_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JobAddRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *JobAddRequest) GetRef() string {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return ""
}

func (x *JobAddRequest) GetFrom() *StoreRef {
	if x != nil {
		return x.xxx_hidden_From
	}
	return nil
}

func (x *JobAddRequest) GetTo() *StoreRef {
	if x != nil {
		return x.xxx_hidden_To
	}
	return nil
}

func (x *JobAddRequest) GetPlatforms() []string {
	if x != nil {
		return x.xxx_hidden_Platforms
	}
	return nil
}

func (x *JobAddRequest) GetCopyReferrers() bool {
	if x != nil {
		return x.xxx_hidden_CopyReferrers
	}
	return false
}

func (x *JobAddRequest) GetState() JobState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *JobAddRequest) GetError() string {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return ""
}

func (x *JobAddRequest) GetVerification() *Verification {
	if x != nil {
		return x.xxx_hidden_Verification
	}
	return nil
}

func (x *JobAddRequest) GetTransfers() []*Transfer {
	if x != nil {
		if x.xxx_hidden_Transfers != nil {
			return *x.xxx_hidden_Transfers
		}
	}
	return nil
}

func (x *JobAddRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *JobAddRequest) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_StartedAt
	}
	return nil
}

func (x *JobAddRequest) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_EndedAt
	}
	return nil
}

func (x *JobAddRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 13)
}

func (x *JobAddRequest) SetRef(v string) {
	x.xxx_hidden_Ref = v
}

func (x *JobAddRequest) SetFrom(v *StoreRef) {
	x.xxx_hidden_From = v
}

func (x *JobAddRequest) SetTo(v *StoreRef) {
	x.xxx_hidden_To = v
}

func (x *JobAddRequest) SetPlatforms(v []string) {
	x.xxx_hidden_Platforms = v
}

func (x *JobAddRequest) SetCopyReferrers(v bool) {
	x.xxx_hidden_CopyReferrers = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 13)
}

func (x *JobAddRequest) SetState(v JobState) {
	x.xxx_hidden_State = v
}

func (x *JobAddRequest) SetError(v string) {
	x.xxx_hidden_Error = v
}

func (x *JobAddRequest) SetVerification(v *Verification) {
	x.xxx_hidden_Verification = v
}

func (x *JobAddRequest) SetTransfers(v []*Transfer) {
	x.xxx_hidden_Transfers = &v
}

func (x *JobAddRequest) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *JobAddRequest) SetStartedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_StartedAt = v
}

func (x *JobAddRequest) SetEndedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_EndedAt = v
}

func (x *JobAddRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *JobAddRequest) HasFrom() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_From != nil
}

func (x *JobAddRequest) HasTo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_To != nil
}

func (x *JobAddRequest) HasCopyReferrers() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *JobAddRequest) HasVerification() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Verification != nil
}

func (x *JobAddRequest) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *JobAddRequest) HasStartedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StartedAt != nil
}

func (x *JobAddRequest) HasEndedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EndedAt != nil
}

func (x *JobAddRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *JobAddRequest) ClearFrom() {
	x.xxx_hidden_From = nil
}

func (x *JobAddRequest) ClearTo() {
	x.xxx_hidden_To = nil
}

func (x *JobAddRequest) ClearCopyReferrers() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_CopyReferrers = false
}

func (x *JobAddRequest) ClearVerification() {
	x.xxx_hidden_Verification = nil
}

func (x *JobAddRequest) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *JobAddRequest) ClearStartedAt() {
	x.xxx_hidden_StartedAt = nil
}

func (x *JobAddRequest) ClearEndedAt() {
	x.xxx_hidden_EndedAt = nil
}

type JobAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id            *string
	Ref           string
	From          *StoreRef
	To            *StoreRef
	Platforms     []string
	CopyReferrers *bool
	State         JobState
	Error         string
	Verification  *Verification
	Transfers     []*Transfer
	CreatedAt     *timestamppb.Timestamp
	StartedAt     *timestamppb.Timestamp
	EndedAt       *timestamppb.Timestamp
}

func (b0 JobAddRequest_builder) Build() *JobAddRequest {
	m0 := &JobAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 13)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_From = b.From
	x.xxx_hidden_To = b.To
	x.xxx_hidden_Platforms = b.Platforms
	if b.CopyReferrers != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 13)
		x.xxx_hidden_CopyReferrers = *b.CopyReferrers
	}
	x.xxx_hidden_State = b.State
	x.xxx_hidden_Error = b.Error
	x.xxx_hidden_Verification = b.Verification
	x.xxx_hidden_Transfers = &b.Transfers
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_StartedAt = b.StartedAt
	x.xxx_hidden_EndedAt = b.EndedAt
	return m0
}

type JobGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *JobRef                `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *JobSelect             `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *JobGetRequest) Reset() {
	*x = JobGetRequest{}
	mi := &file_gantry_job_svc_g_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobGetRequest) ProtoMessage() {}

func (x *JobGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_job_svc_g_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JobGetRequest) GetRef() *JobRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *JobGetRequest) GetSelect() *JobSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *JobGetRequest) SetRef(v *JobRef) {
	x.xxx_hidden_Ref = v
}

func (x *JobGetRequest) SetSelect(v *JobSelect) {
	x.xxx_hidden_Select = v
}

func (x *JobGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *JobGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *JobGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *JobGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type JobGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *JobRef
	Select *JobSelect
}

func (b0 JobGetRequest_builder) Build() *JobGetRequest {
	m0 := &JobGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type JobRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isJobRef_Key           `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobRef) Reset() {
	*x = JobRef{}
	mi := &file_gantry_job_svc_g_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRef) ProtoMessage() {}

func (x *JobRef) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_job_svc_g_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JobRef) GetId() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*jobRef_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *JobRef) SetId(v string) {
	x.xxx_hidden_Key = &jobRef_Id{v}
}

func (x *JobRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *JobRef) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*jobRef_Id)
	return ok
}

func (x *JobRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *JobRef) ClearId() {
	if _, ok := x.xxx_hidden_Key.(*jobRef_Id); ok {
		x.xxx_hidden_Key = nil
	}
}

const JobRef_Key_not_set_case case_JobRef_Key = 0
const JobRef_Id_case case_JobRef_Key = 1

func (x *JobRef) WhichKey() case_JobRef_Key {
	if x == nil {
		return JobRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *jobRef_Id:
		return JobRef_Id_case
	default:
		return JobRef_Key_not_set_case
	}
}

type JobRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Id *string
	// -- end of xxx_hidden_Key
}

func (b0 JobRef_builder) Build() *JobRef {
	m0 := &JobRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Key = &jobRef_Id{*b.Id}
	}
	return m0
}

type case_JobRef_Key protoreflect.FieldNumber

func (x case_JobRef_Key) String() string {
	md := file_gantry_job_svc_g_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isJobRef_Key interface {
	isJobRef_Key()
}

type jobRef_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,oneof"`
}

func (*jobRef_Id) isJobRef_Key() {}

type JobSelect struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All           bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_Ref           bool                   `protobuf:"varint,2,opt,name=ref"`
	xxx_hidden_From          *StoreSelect           `protobuf:"bytes,3,opt,name=from"`
	xxx_hidden_To            *StoreSelect           `protobuf:"bytes,4,opt,name=to"`
	xxx_hidden_Platforms     bool                   `protobuf:"varint,5,opt,name=platforms"`
	xxx_hidden_CopyReferrers bool                   `protobuf:"varint,6,opt,name=copy_referrers,json=copyReferrers"`
	xxx_hidden_State         bool                   `protobuf:"varint,7,opt,name=state"`
	xxx_hidden_Error         bool                   `protobuf:"varint,8,opt,name=error"`
	xxx_hidden_Verification  bool                   `protobuf:"varint,9,opt,name=verification"`
	xxx_hidden_Transfers     bool                   `protobuf:"varint,10,opt,name=transfers"`
	xxx_hidden_CreatedAt     bool                   `protobuf:"varint,11,opt,name=created_at,json=createdAt"`
	xxx_hidden_StartedAt     bool                   `protobuf:"varint,12,opt,name=started_at,json=startedAt"`
	xxx_hidden_EndedAt       bool                   `protobuf:"varint,13,opt,name=ended_at,json=endedAt"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *JobSelect) Reset() {
	*x = JobSelect{}
	mi := &file_gantry_job_svc_g_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSelect) ProtoMessage() {}

func (x *JobSelect) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_job_svc_g_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JobSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *JobSelect) GetRef() bool {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return false
}

func (x *JobSelect) GetFrom() *StoreSelect {
	if x != nil {
		return x.xxx_hidden_From
	}
	return nil
}

func (x *JobSelect) GetTo() *StoreSelect {
	if x != nil {
		return x.xxx_hidden_To
	}
	return nil
}

func (x *JobSelect) GetPlatforms() bool {
	if x != nil {
		return x.xxx_hidden_Platforms
	}
	return false
}

func (x *JobSelect) GetCopyReferrers() bool {
	if x != nil {
		return x.xxx_hidden_CopyReferrers
	}
	return false
}

func (x *JobSelect) GetState() bool {
	if x != nil {
		return x.xxx_hidden_State
	}
	return false
}

func (x *JobSelect) GetError() bool {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return false
}

func (x *JobSelect) GetVerification() bool {
	if x != nil {
		return x.xxx_hidden_Verification
	}
	return false
}

func (x *JobSelect) GetTransfers() bool {
	if x != nil {
		return x.xxx_hidden_Transfers
	}
	return false
}

func (x *JobSelect) GetCreatedAt() bool {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return false
}

func (x *JobSelect) GetStartedAt() bool {
	if x != nil {
		return x.xxx_hidden_StartedAt
	}
	return false
}

func (x *JobSelect) GetEndedAt() bool {
	if x != nil {
		return x.xxx_hidden_EndedAt
	}
	return false
}

func (x *JobSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 13)
}

func (x *JobSelect) SetRef(v bool) {
	x.xxx_hidden_Ref = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 13)
}

func (x *JobSelect) SetFrom(v *StoreSelect) {
	x.xxx_hidden_From = v
}

func (x *JobSelect) SetTo(v *StoreSelect) {
	x.xxx_hidden_To = v
}

func (x *JobSelect) SetPlatforms(v bool) {
	x.xxx_hidden_Platforms = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 13)
}

func (x *JobSelect) SetCopyReferrers(v bool) {
	x.xxx_hidden_CopyReferrers = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 13)
}

func (x *JobSelect) SetState(v bool) {
	x.xxx_hidden_State = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 13)
}

func (x *JobSelect) SetError(v bool) {
	x.xxx_hidden_Error = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 13)
}

func (x *JobSelect) SetVerification(v bool) {
	x.xxx_hidden_Verification = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 13)
}

func (x *JobSelect) SetTransfers(v bool) {
	x.xxx_hidden_Transfers = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 13)
}

func (x *JobSelect) SetCreatedAt(v bool) {
	x.xxx_hidden_CreatedAt = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 13)
}

func (x *JobSelect) SetStartedAt(v bool) {
	x.xxx_hidden_StartedAt = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 13)
}

func (x *JobSelect) SetEndedAt(v bool) {
	x.xxx_hidden_EndedAt = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 12, 13)
}

func (x *JobSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *JobSelect) HasRef() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *JobSelect) HasFrom() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_From != nil
}

func (x *JobSelect) HasTo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_To != nil
}

func (x *JobSelect) HasPlatforms() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *JobSelect) HasCopyReferrers() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *JobSelect) HasState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *JobSelect) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *JobSelect) HasVerification() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *JobSelect) HasTransfers() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *JobSelect) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *JobSelect) HasStartedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *JobSelect) HasEndedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 12)
}

func (x *JobSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *JobSelect) ClearRef() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Ref = false
}

func (x *JobSelect) ClearFrom() {
	x.xxx_hidden_From = nil
}

func (x *JobSelect) ClearTo() {
	x.xxx_hidden_To = nil
}

func (x *JobSelect) ClearPlatforms() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Platforms = false
}

func (x *JobSelect) ClearCopyReferrers() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_CopyReferrers = false
}

func (x *JobSelect) ClearState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_State = false
}

func (x *JobSelect) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Error = false
}

func (x *JobSelect) ClearVerification() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Verification = false
}

func (x *JobSelect) ClearTransfers() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_Transfers = false
}

func (x *JobSelect) ClearCreatedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_CreatedAt = false
}

func (x *JobSelect) ClearStartedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_StartedAt = false
}

func (x *JobSelect) ClearEndedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 12)
	x.xxx_hidden_EndedAt = false
}

type JobSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All           *bool
	Ref           *bool
	From          *StoreSelect
	To            *StoreSelect
	Platforms     *bool
	CopyReferrers *bool
	State         *bool
	Error         *bool
	Verification  *bool
	Transfers     *bool
	CreatedAt     *bool
	StartedAt     *bool
	EndedAt       *bool
}

func (b0 JobSelect_builder) Build() *JobSelect {
	m0 := &JobSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 13)
		x.xxx_hidden_All = *b.All
	}
	if b.Ref != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 13)
		x.xxx_hidden_Ref = *b.Ref
	}
	x.xxx_hidden_From = b.From
	x.xxx_hidden_To = b.To
	if b.Platforms != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 13)
		x.xxx_hidden_Platforms = *b.Platforms
	}
	if b.CopyReferrers != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 13)
		x.xxx_hidden_CopyReferrers = *b.CopyReferrers
	}
	if b.State != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 13)
		x.xxx_hidden_State = *b.State
	}
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 13)
		x.xxx_hidden_Error = *b.Error
	}
	if b.Verification != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 13)
		x.xxx_hidden_Verification = *b.Verification
	}
	if b.Transfers != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 13)
		x.xxx_hidden_Transfers = *b.Transfers
	}
	if b.CreatedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 13)
		x.xxx_hidden_CreatedAt = *b.CreatedAt
	}
	if b.StartedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 13)
		x.xxx_hidden_StartedAt = *b.StartedAt
	}
	if b.EndedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 12, 13)
		x.xxx_hidden_EndedAt = *b.EndedAt
	}
	return m0
}

type JobPatchRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref              *JobRef                `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_State            JobState               `protobuf:"varint,13,opt,name=state,enum=gantry.JobState"`
	xxx_hidden_Error            *string                `protobuf:"bytes,15,opt,name=error"`
	xxx_hidden_Verification     *Verification          `protobuf:"bytes,17,opt,name=verification"`
	xxx_hidden_VerificationNull bool                   `protobuf:"varint,18,opt,name=verification_null,json=verificationNull"`
	xxx_hidden_Transfers        *[]*Transfer           `protobuf:"bytes,19,rep,name=transfers"`
	xxx_hidden_StartedAt        *timestamppb.Timestamp `protobuf:"bytes,23,opt,name=started_at,json=startedAt"`
	xxx_hidden_EndedAt          *timestamppb.Timestamp `protobuf:"bytes,25,opt,name=ended_at,json=endedAt"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *JobPatchRequest) Reset() {
	*x = JobPatchRequest{}
	mi := &file_gantry_job_svc_g_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobPatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobPatchRequest) ProtoMessage() {}

func (x *JobPatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_job_svc_g_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JobPatchRequest) GetRef() *JobRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *JobPatchRequest) GetState() JobState {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_State
		}
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *JobPatchRequest) GetError() string {
	if x != nil {
		if x.xxx_hidden_Error != nil {
			return *x.xxx_hidden_Error
		}
		return ""
	}
	return ""
}

func (x *JobPatchRequest) GetVerification() *Verification {
	if x != nil {
		return x.xxx_hidden_Verification
	}
	return nil
}

func (x *JobPatchRequest) GetVerificationNull() bool {
	if x != nil {
		return x.xxx_hidden_VerificationNull
	}
	return false
}

func (x *JobPatchRequest) GetTransfers() []*Transfer {
	if x != nil {
		if x.xxx_hidden_Transfers != nil {
			return *x.xxx_hidden_Transfers
		}
	}
	return nil
}

func (x *JobPatchRequest) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_StartedAt
	}
	return nil
}

func (x *JobPatchRequest) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_EndedAt
	}
	return nil
}

func (x *JobPatchRequest) SetRef(v *JobRef) {
	x.xxx_hidden_Ref = v
}

func (x *JobPatchRequest) SetState(v JobState) {
	x.xxx_hidden_State = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *JobPatchRequest) SetError(v string) {
	x.xxx_hidden_Error = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *JobPatchRequest) SetVerification(v *Verification) {
	x.xxx_hidden_Verification = v
}

func (x *JobPatchRequest) SetVerificationNull(v bool) {
	x.xxx_hidden_VerificationNull = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *JobPatchRequest) SetTransfers(v []*Transfer) {
	x.xxx_hidden_Transfers = &v
}

func (x *JobPatchRequest) SetStartedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_StartedAt = v
}

func (x *JobPatchRequest) SetEndedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_EndedAt = v
}

func (x *JobPatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *JobPatchRequest) HasState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *JobPatchRequest) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *JobPatchRequest) HasVerification() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Verification != nil
}

func (x *JobPatchRequest) HasVerificationNull() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *JobPatchRequest) HasStartedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StartedAt != nil
}

func (x *JobPatchRequest) HasEndedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EndedAt != nil
}

func (x *JobPatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *JobPatchRequest) ClearState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_State = JobState_JOB_STATE_UNSPECIFIED
}

func (x *JobPatchRequest) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Error = nil
}

func (x *JobPatchRequest) ClearVerification() {
	x.xxx_hidden_Verification = nil
}

func (x *JobPatchRequest) ClearVerificationNull() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_VerificationNull = false
}

func (x *JobPatchRequest) ClearStartedAt() {
	x.xxx_hidden_StartedAt = nil
}

func (x *JobPatchRequest) ClearEndedAt() {
	x.xxx_hidden_EndedAt = nil
}

type JobPatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref              *JobRef
	State            *JobState
	Error            *string
	Verification     *Verification
	VerificationNull *bool
	Transfers        []*Transfer
	StartedAt        *timestamppb.Timestamp
	EndedAt          *timestamppb.Timestamp
}

func (b0 JobPatchRequest_builder) Build() *JobPatchRequest {
	m0 := &JobPatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	if b.State != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_State = *b.State
	}
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_Error = b.Error
	}
	x.xxx_hidden_Verification = b.Verification
	if b.VerificationNull != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_VerificationNull = *b.VerificationNull
	}
	x.xxx_hidden_Transfers = &b.Transfers
	x.xxx_hidden_StartedAt = b.StartedAt
	x.xxx_hidden_EndedAt = b.EndedAt
	return m0
}

type JobListRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_State       JobState               `protobuf:"varint,1,opt,name=state,enum=gantry.JobState"`
	xxx_hidden_Ref         *string                `protobuf:"bytes,2,opt,name=ref"`
	xxx_hidden_Since       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=since"`
	xxx_hidden_PageSize    int32                  `protobuf:"varint,10,opt,name=page_size,json=pageSize"`
	xxx_hidden_PageToken   *string                `protobuf:"bytes,11,opt,name=page_token,json=pageToken"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *JobListRequest) Reset() {
	*x = JobListRequest{}
	mi := &file_gantry_job_svc_g_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobListRequest) ProtoMessage() {}

func (x *JobListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_job_svc_g_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JobListRequest) GetState() JobState {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_State
		}
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *JobListRequest) GetRef() string {
	if x != nil {
		if x.xxx_hidden_Ref != nil {
			return *x.xxx_hidden_Ref
		}
		return ""
	}
	return ""
}

func (x *JobListRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Since
	}
	return nil
}

func (x *JobListRequest) GetPageSize() int32 {
	if x != nil {
		return x.xxx_hidden_PageSize
	}
	return 0
}

func (x *JobListRequest) GetPageToken() string {
	if x != nil {
		if x.xxx_hidden_PageToken != nil {
			return *x.xxx_hidden_PageToken
		}
		return ""
	}
	return ""
}

func (x *JobListRequest) SetState(v JobState) {
	x.xxx_hidden_State = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *JobListRequest) SetRef(v string) {
	x.xxx_hidden_Ref = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *JobListRequest) SetSince(v *timestamppb.Timestamp) {
	x.xxx_hidden_Since = v
}

func (x *JobListRequest) SetPageSize(v int32) {
	x.xxx_hidden_PageSize = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *JobListRequest) SetPageToken(v string) {
	x.xxx_hidden_PageToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *JobListRequest) HasState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *JobListRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *JobListRequest) HasSince() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Since != nil
}

func (x *JobListRequest) HasPageSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *JobListRequest) HasPageToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *JobListRequest) ClearState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_State = JobState_JOB_STATE_UNSPECIFIED
}

func (x *JobListRequest) ClearRef() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Ref = nil
}

func (x *JobListRequest) ClearSince() {
	x.xxx_hidden_Since = nil
}

func (x *JobListRequest) ClearPageSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_PageSize = 0
}

func (x *JobListRequest) ClearPageToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_PageToken = nil
}

type JobListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	State *JobState
	// Substring match on the requested ref.
	Ref *string
	// Jobs created at or after this instant.
	Since     *timestamppb.Timestamp
	PageSize  *int32
	PageToken *string
}

func (b0 JobListRequest_builder) Build() *JobListRequest {
	m0 := &JobListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.State != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_State = *b.State
	}
	if b.Ref != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Ref = b.Ref
	}
	x.xxx_hidden_Since = b.Since
	if b.PageSize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_PageSize = *b.PageSize
	}
	if b.PageToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_PageToken = b.PageToken
	}
	return m0
}

type JobListResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items         *[]*Job                `protobuf:"bytes,1,rep,name=items"`
	xxx_hidden_NextPageToken *string                `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *JobListResponse) Reset() {
	*x = JobListResponse{}
	mi := &file_gantry_job_svc_g_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobListResponse) ProtoMessage() {}

func (x *JobListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_job_svc_g_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JobListResponse) GetItems() []*Job {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *JobListResponse) GetNextPageToken() string {
	if x != nil {
		if x.xxx_hidden_NextPageToken != nil {
			return *x.xxx_hidden_NextPageToken
		}
		return ""
	}
	return ""
}

func (x *JobListResponse) SetItems(v []*Job) {
	x.xxx_hidden_Items = &v
}

func (x *JobListResponse) SetNextPageToken(v string) {
	x.xxx_hidden_NextPageToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *JobListResponse) HasNextPageToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *JobListResponse) ClearNextPageToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NextPageToken = nil
}

type JobListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items         []*Job
	NextPageToken *string
}

func (b0 JobListResponse_builder) Build() *JobListResponse {
	m0 := &JobListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	if b.NextPageToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_NextPageToken = b.NextPageToken
	}
	return m0
}

var File_gantry_job_svc_g_proto protoreflect.FileDescriptor

const file_gantry_job_svc_g_proto_rawDesc = "" +
	"\n" +
	"\x16gantry/job_svc.g.proto\x12\x06gantry\x1a\x10gantry/job.proto\x1a\x18gantry/store_svc.g.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x04\n" +
	"\rJobAddRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x03ref\x18\x02 \x01(\tB\x05\xaa\x01\x02\b\x02R\x03ref\x12$\n" +
	"\x04from\x18\x03 \x01(\v2\x10.gantry.StoreRefR\x04from\x12 \n" +
	"\x02to\x18\x04 \x01(\v2\x10.gantry.StoreRefR\x02to\x12\x1c\n" +
	"\tplatforms\x18\x05 \x03(\tR\tplatforms\x12%\n" +
	"\x0ecopy_referrers\x18\x06 \x01(\bR\rcopyReferrers\x12-\n" +
	"\x05state\x18\a \x01(\x0e2\x10.gantry.JobStateB\x05\xaa\x01\x02\b\x02R\x05state\x12\x1b\n" +
	"\x05error\x18\b \x01(\tB\x05\xaa\x01\x02\b\x02R\x05error\x128\n" +
	"\fverification\x18\t \x01(\v2\x14.gantry.VerificationR\fverification\x12.\n" +
	"\ttransfers\x18\n" +
	" \x03(\v2\x10.gantry.TransferR\ttransfers\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\"\\\n" +
	"\rJobGetRequest\x12 \n" +
	"\x03ref\x18\x01 \x01(\v2\x0e.gantry.JobRefR\x03ref\x12)\n" +
	"\x06select\x18\x02 \x01(\v2\x11.gantry.JobSelectR\x06select\"!\n" +
	"\x06JobRef\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02idB\x05\n" +
	"\x03key\"\x89\x03\n" +
	"\tJobSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\bR\x03ref\x12'\n" +
	"\x04from\x18\x03 \x01(\v2\x13.gantry.StoreSelectR\x04from\x12#\n" +
	"\x02to\x18\x04 \x01(\v2\x13.gantry.StoreSelectR\x02to\x12\x1c\n" +
	"\tplatforms\x18\x05 \x01(\bR\tplatforms\x12%\n" +
	"\x0ecopy_referrers\x18\x06 \x01(\bR\rcopyReferrers\x12\x14\n" +
	"\x05state\x18\a \x01(\bR\x05state\x12\x14\n" +
	"\x05error\x18\b \x01(\bR\x05error\x12\"\n" +
	"\fverification\x18\t \x01(\bR\fverification\x12\x1c\n" +
	"\ttransfers\x18\n" +
	" \x01(\bR\ttransfers\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\bR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\f \x01(\bR\tstartedAt\x12\x19\n" +
	"\bended_at\x18\r \x01(\bR\aendedAt\"\xfa\x02\n" +
	"\x0fJobPatchRequest\x12 \n" +
	"\x03ref\x18\x01 \x01(\v2\x0e.gantry.JobRefR\x03ref\x12&\n" +
	"\x05state\x18\r \x01(\x0e2\x10.gantry.JobStateR\x05state\x12\x14\n" +
	"\x05error\x18\x0f \x01(\tR\x05error\x128\n" +
	"\fverification\x18\x11 \x01(\v2\x14.gantry.VerificationR\fverification\x12+\n" +
	"\x11verification_null\x18\x12 \x01(\bR\x10verificationNull\x12.\n" +
	"\ttransfers\x18\x13 \x03(\v2\x10.gantry.TransferR\ttransfers\x129\n" +
	"\n" +
	"started_at\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\x19 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\"\xb8\x01\n" +
	"\x0eJobListRequest\x12&\n" +
	"\x05state\x18\x01 \x01(\x0e2\x10.gantry.JobStateR\x05state\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x120\n" +
	"\x05since\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\v \x01(\tR\tpageToken\"\\\n" +
	"\x0fJobListResponse\x12!\n" +
	"\x05items\x18\x01 \x03(\v2\v.gantry.JobR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xa3\x02\n" +
	"\n" +
	"JobService\x12)\n" +
	"\x03Add\x12\x15.gantry.JobAddRequest\x1a\v.gantry.Job\x12)\n" +
	"\x03Get\x12\x15.gantry.JobGetRequest\x1a\v.gantry.Job\x12-\n" +
	"\x05Patch\x12\x17.gantry.JobPatchRequest\x1a\v.gantry.Job\x12/\n" +
	"\x05Erase\x12\x0e.gantry.JobRef\x1a\x16.google.protobuf.Empty\x127\n" +
	"\x04List\x12\x16.gantry.JobListRequest\x1a\x17.gantry.JobListResponse\x12&\n" +
	"\x05Watch\x12\x0e.gantry.JobRef\x1a\v.gantry.Job0\x01B\x1fZ\x1dgithub.com/lesomnus/gantry/pbb\beditionsp\xe8\a"

var file_gantry_job_svc_g_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gantry_job_svc_g_proto_goTypes = []any{
	(*JobAddRequest)(nil),         // 0: gantry.JobAddRequest
	(*JobGetRequest)(nil),         // 1: gantry.JobGetRequest
	(*JobRef)(nil),                // 2: gantry.JobRef
	(*JobSelect)(nil),             // 3: gantry.JobSelect
	(*JobPatchRequest)(nil),       // 4: gantry.JobPatchRequest
	(*JobListRequest)(nil),        // 5: gantry.JobListRequest
	(*JobListResponse)(nil),       // 6: gantry.JobListResponse
	(*StoreRef)(nil),              // 7: gantry.StoreRef
	(JobState)(0),                 // 8: gantry.JobState
	(*Verification)(nil),          // 9: gantry.Verification
	(*Transfer)(nil),              // 10: gantry.Transfer
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*StoreSelect)(nil),           // 12: gantry.StoreSelect
	(*Job)(nil),                   // 13: gantry.Job
	(*emptypb.Empty)(nil),         // 14: google.protobuf.Empty
}
var file_gantry_job_svc_g_proto_depIdxs = []int32{
	7,  // 0: gantry.JobAddRequest.from:type_name -> gantry.StoreRef
	7,  // 1: gantry.JobAddRequest.to:type_name -> gantry.StoreRef
	8,  // 2: gantry.JobAddRequest.state:type_name -> gantry.JobState
	9,  // 3: gantry.JobAddRequest.verification:type_name -> gantry.Verification
	10, // 4: gantry.JobAddRequest.transfers:type_name -> gantry.Transfer
	11, // 5: gantry.JobAddRequest.created_at:type_name -> google.protobuf.Timestamp
	11, // 6: gantry.JobAddRequest.started_at:type_name -> google.protobuf.Timestamp
	11, // 7: gantry.JobAddRequest.ended_at:type_name -> google.protobuf.Timestamp
	2,  // 8: gantry.JobGetRequest.ref:type_name -> gantry.JobRef
	3,  // 9: gantry.JobGetRequest.select:type_name -> gantry.JobSelect
	12, // 10: gantry.JobSelect.from:type_name -> gantry.StoreSelect
	12, // 11: gantry.JobSelect.to:type_name -> gantry.StoreSelect
	2,  // 12: gantry.JobPatchRequest.ref:type_name -> gantry.JobRef
	8,  // 13: gantry.JobPatchRequest.state:type_name -> gantry.JobState
	9,  // 14: gantry.JobPatchRequest.verification:type_name -> gantry.Verification
	10, // 15: gantry.JobPatchRequest.transfers:type_name -> gantry.Transfer
	11, // 16: gantry.JobPatchRequest.started_at:type_name -> google.protobuf.Timestamp
	11, // 17: gantry.JobPatchRequest.ended_at:type_name -> google.protobuf.Timestamp
	8,  // 18: gantry.JobListRequest.state:type_name -> gantry.JobState
	11, // 19: gantry.JobListRequest.since:type_name -> google.protobuf.Timestamp
	13, // 20: gantry.JobListResponse.items:type_name -> gantry.Job
	0,  // 21: gantry.JobService.Add:input_type -> gantry.JobAddRequest
	1,  // 22: gantry.JobService.Get:input_type -> gantry.JobGetRequest
	4,  // 23: gantry.JobService.Patch:input_type -> gantry.JobPatchRequest
	2,  // 24: gantry.JobService.Erase:input_type -> gantry.JobRef
	5,  // 25: gantry.JobService.List:input_type -> gantry.JobListRequest
	2,  // 26: gantry.JobService.Watch:input_type -> gantry.JobRef
	13, // 27: gantry.JobService.Add:output_type -> gantry.Job
	13, // 28: gantry.JobService.Get:output_type -> gantry.Job
	13, // 29: gantry.JobService.Patch:output_type -> gantry.Job
	14, // 30: gantry.JobService.Erase:output_type -> google.protobuf.Empty
	6,  // 31: gantry.JobService.List:output_type -> gantry.JobListResponse
	13, // 32: gantry.JobService.Watch:output_type -> gantry.Job
	27, // [27:33] is the sub-list for method output_type
	21, // [21:27] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_gantry_job_svc_g_proto_init() }
func file_gantry_job_svc_g_proto_init() {
	if File_gantry_job_svc_g_proto != nil {
		return
	}
	file_gantry_job_proto_init()
	file_gantry_store_svc_g_proto_init()
	file_gantry_job_svc_g_proto_msgTypes[2].OneofWrappers = []any{
		(*jobRef_Id)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gantry_job_svc_g_proto_rawDesc), len(file_gantry_job_svc_g_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gantry_job_svc_g_proto_goTypes,
		DependencyIndexes: file_gantry_job_svc_g_proto_depIdxs,
		MessageInfos:      file_gantry_job_svc_g_proto_msgTypes,
	}.Build()
	File_gantry_job_svc_g_proto = out.File
	file_gantry_job_svc_g_proto_goTypes = nil
	file_gantry_job_svc_g_proto_depIdxs = nil
}
