// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: gantry/job_svc.g.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobAddRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id               *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Labels           map[string]string      `protobuf:"bytes,7,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Ref              string                 `protobuf:"bytes,8,opt,name=ref"`
	xxx_hidden_Source           *StoreRef              `protobuf:"bytes,9,opt,name=source"`
	xxx_hidden_Target           *StoreRef              `protobuf:"bytes,10,opt,name=target"`
	xxx_hidden_Platforms        []string               `protobuf:"bytes,11,rep,name=platforms"`
	xxx_hidden_As               []string               `protobuf:"bytes,12,rep,name=as"`
	xxx_hidden_DateEnded        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=date_ended,json=dateEnded"`
	xxx_hidden_DateStarted      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=date_started,json=dateStarted"`
	xxx_hidden_DateCreated      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	xxx_hidden_State            JobState               `protobuf:"varint,16,opt,name=state,enum=gantry.JobState"`
	xxx_hidden_Error            string                 `protobuf:"bytes,17,opt,name=error"`
	xxx_hidden_Verification     *Verification          `protobuf:"bytes,18,opt,name=verification"`
	xxx_hidden_Transfers        *[]*Transfer           `protobuf:"bytes,19,rep,name=transfers"`
	xxx_hidden_CopyReferrers    bool                   `protobuf:"varint,20,opt,name=copy_referrers,json=copyReferrers"`
	xxx_hidden_FallbackToOrigin bool                   `protobuf:"varint,21,opt,name=fallback_to_origin,json=fallbackToOrigin"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *JobAddRequest) Reset() {
	*x = JobAddRequest{}
	mi := &file_gantry_job_svc_g_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAddRequest) ProtoMessage() {}

func (x *JobAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_job_svc_g_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JobAddRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *JobAddRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *JobAddRequest) GetRef() string {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return ""
}

func (x *JobAddRequest) GetSource() *StoreRef {
	if x != nil {
		return x.xxx_hidden_Source
	}
	return nil
}

func (x *JobAddRequest) GetTarget() *StoreRef {
	if x != nil {
		return x.xxx_hidden_Target
	}
	return nil
}

func (x *JobAddRequest) GetPlatforms() []string {
	if x != nil {
		return x.xxx_hidden_Platforms
	}
	return nil
}

func (x *JobAddRequest) GetAs() []string {
	if x != nil {
		return x.xxx_hidden_As
	}
	return nil
}

func (x *JobAddRequest) GetDateEnded() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateEnded
	}
	return nil
}

func (x *JobAddRequest) GetDateStarted() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateStarted
	}
	return nil
}

func (x *JobAddRequest) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *JobAddRequest) GetState() JobState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *JobAddRequest) GetError() string {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return ""
}

func (x *JobAddRequest) GetVerification() *Verification {
	if x != nil {
		return x.xxx_hidden_Verification
	}
	return nil
}

func (x *JobAddRequest) GetTransfers() []*Transfer {
	if x != nil {
		if x.xxx_hidden_Transfers != nil {
			return *x.xxx_hidden_Transfers
		}
	}
	return nil
}

func (x *JobAddRequest) GetCopyReferrers() bool {
	if x != nil {
		return x.xxx_hidden_CopyReferrers
	}
	return false
}

func (x *JobAddRequest) GetFallbackToOrigin() bool {
	if x != nil {
		return x.xxx_hidden_FallbackToOrigin
	}
	return false
}

func (x *JobAddRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 16)
}

func (x *JobAddRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *JobAddRequest) SetRef(v string) {
	x.xxx_hidden_Ref = v
}

func (x *JobAddRequest) SetSource(v *StoreRef) {
	x.xxx_hidden_Source = v
}

func (x *JobAddRequest) SetTarget(v *StoreRef) {
	x.xxx_hidden_Target = v
}

func (x *JobAddRequest) SetPlatforms(v []string) {
	x.xxx_hidden_Platforms = v
}

func (x *JobAddRequest) SetAs(v []string) {
	x.xxx_hidden_As = v
}

func (x *JobAddRequest) SetDateEnded(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateEnded = v
}

func (x *JobAddRequest) SetDateStarted(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateStarted = v
}

func (x *JobAddRequest) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *JobAddRequest) SetState(v JobState) {
	x.xxx_hidden_State = v
}

func (x *JobAddRequest) SetError(v string) {
	x.xxx_hidden_Error = v
}

func (x *JobAddRequest) SetVerification(v *Verification) {
	x.xxx_hidden_Verification = v
}

func (x *JobAddRequest) SetTransfers(v []*Transfer) {
	x.xxx_hidden_Transfers = &v
}

func (x *JobAddRequest) SetCopyReferrers(v bool) {
	x.xxx_hidden_CopyReferrers = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 14, 16)
}

func (x *JobAddRequest) SetFallbackToOrigin(v bool) {
	x.xxx_hidden_FallbackToOrigin = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 15, 16)
}

func (x *JobAddRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *JobAddRequest) HasSource() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Source != nil
}

func (x *JobAddRequest) HasTarget() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Target != nil
}

func (x *JobAddRequest) HasDateEnded() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateEnded != nil
}

func (x *JobAddRequest) HasDateStarted() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateStarted != nil
}

func (x *JobAddRequest) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *JobAddRequest) HasVerification() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Verification != nil
}

func (x *JobAddRequest) HasCopyReferrers() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 14)
}

func (x *JobAddRequest) HasFallbackToOrigin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 15)
}

func (x *JobAddRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *JobAddRequest) ClearSource() {
	x.xxx_hidden_Source = nil
}

func (x *JobAddRequest) ClearTarget() {
	x.xxx_hidden_Target = nil
}

func (x *JobAddRequest) ClearDateEnded() {
	x.xxx_hidden_DateEnded = nil
}

func (x *JobAddRequest) ClearDateStarted() {
	x.xxx_hidden_DateStarted = nil
}

func (x *JobAddRequest) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

func (x *JobAddRequest) ClearVerification() {
	x.xxx_hidden_Verification = nil
}

func (x *JobAddRequest) ClearCopyReferrers() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 14)
	x.xxx_hidden_CopyReferrers = false
}

func (x *JobAddRequest) ClearFallbackToOrigin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 15)
	x.xxx_hidden_FallbackToOrigin = false
}

type JobAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id               *string
	Labels           map[string]string
	Ref              string
	Source           *StoreRef
	Target           *StoreRef
	Platforms        []string
	As               []string
	DateEnded        *timestamppb.Timestamp
	DateStarted      *timestamppb.Timestamp
	DateCreated      *timestamppb.Timestamp
	State            JobState
	Error            string
	Verification     *Verification
	Transfers        []*Transfer
	CopyReferrers    *bool
	FallbackToOrigin *bool
}

func (b0 JobAddRequest_builder) Build() *JobAddRequest {
	m0 := &JobAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 16)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Source = b.Source
	x.xxx_hidden_Target = b.Target
	x.xxx_hidden_Platforms = b.Platforms
	x.xxx_hidden_As = b.As
	x.xxx_hidden_DateEnded = b.DateEnded
	x.xxx_hidden_DateStarted = b.DateStarted
	x.xxx_hidden_DateCreated = b.DateCreated
	x.xxx_hidden_State = b.State
	x.xxx_hidden_Error = b.Error
	x.xxx_hidden_Verification = b.Verification
	x.xxx_hidden_Transfers = &b.Transfers
	if b.CopyReferrers != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 14, 16)
		x.xxx_hidden_CopyReferrers = *b.CopyReferrers
	}
	if b.FallbackToOrigin != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 15, 16)
		x.xxx_hidden_FallbackToOrigin = *b.FallbackToOrigin
	}
	return m0
}

type JobGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *JobRef                `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *JobSelect             `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *JobGetRequest) Reset() {
	*x = JobGetRequest{}
	mi := &file_gantry_job_svc_g_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobGetRequest) ProtoMessage() {}

func (x *JobGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_job_svc_g_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JobGetRequest) GetRef() *JobRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *JobGetRequest) GetSelect() *JobSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *JobGetRequest) SetRef(v *JobRef) {
	x.xxx_hidden_Ref = v
}

func (x *JobGetRequest) SetSelect(v *JobSelect) {
	x.xxx_hidden_Select = v
}

func (x *JobGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *JobGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *JobGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *JobGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type JobGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *JobRef
	Select *JobSelect
}

func (b0 JobGetRequest_builder) Build() *JobGetRequest {
	m0 := &JobGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type JobRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isJobRef_Key           `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobRef) Reset() {
	*x = JobRef{}
	mi := &file_gantry_job_svc_g_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRef) ProtoMessage() {}

func (x *JobRef) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_job_svc_g_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JobRef) GetId() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*jobRef_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *JobRef) SetId(v string) {
	x.xxx_hidden_Key = &jobRef_Id{v}
}

func (x *JobRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *JobRef) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*jobRef_Id)
	return ok
}

func (x *JobRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *JobRef) ClearId() {
	if _, ok := x.xxx_hidden_Key.(*jobRef_Id); ok {
		x.xxx_hidden_Key = nil
	}
}

const JobRef_Key_not_set_case case_JobRef_Key = 0
const JobRef_Id_case case_JobRef_Key = 1

func (x *JobRef) WhichKey() case_JobRef_Key {
	if x == nil {
		return JobRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *jobRef_Id:
		return JobRef_Id_case
	default:
		return JobRef_Key_not_set_case
	}
}

type JobRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Id *string
	// -- end of xxx_hidden_Key
}

func (b0 JobRef_builder) Build() *JobRef {
	m0 := &JobRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Key = &jobRef_Id{*b.Id}
	}
	return m0
}

type case_JobRef_Key protoreflect.FieldNumber

func (x case_JobRef_Key) String() string {
	md := file_gantry_job_svc_g_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isJobRef_Key interface {
	isJobRef_Key()
}

type jobRef_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,oneof"`
}

func (*jobRef_Id) isJobRef_Key() {}

type JobSelect struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All              bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_Labels           bool                   `protobuf:"varint,7,opt,name=labels"`
	xxx_hidden_Ref              bool                   `protobuf:"varint,8,opt,name=ref"`
	xxx_hidden_Source           *StoreSelect           `protobuf:"bytes,9,opt,name=source"`
	xxx_hidden_Target           *StoreSelect           `protobuf:"bytes,10,opt,name=target"`
	xxx_hidden_Platforms        bool                   `protobuf:"varint,11,opt,name=platforms"`
	xxx_hidden_As               bool                   `protobuf:"varint,12,opt,name=as"`
	xxx_hidden_DateEnded        bool                   `protobuf:"varint,13,opt,name=date_ended,json=dateEnded"`
	xxx_hidden_DateStarted      bool                   `protobuf:"varint,14,opt,name=date_started,json=dateStarted"`
	xxx_hidden_DateCreated      bool                   `protobuf:"varint,15,opt,name=date_created,json=dateCreated"`
	xxx_hidden_State            bool                   `protobuf:"varint,16,opt,name=state"`
	xxx_hidden_Error            bool                   `protobuf:"varint,17,opt,name=error"`
	xxx_hidden_Verification     bool                   `protobuf:"varint,18,opt,name=verification"`
	xxx_hidden_Transfers        bool                   `protobuf:"varint,19,opt,name=transfers"`
	xxx_hidden_CopyReferrers    bool                   `protobuf:"varint,20,opt,name=copy_referrers,json=copyReferrers"`
	xxx_hidden_FallbackToOrigin bool                   `protobuf:"varint,21,opt,name=fallback_to_origin,json=fallbackToOrigin"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *JobSelect) Reset() {
	*x = JobSelect{}
	mi := &file_gantry_job_svc_g_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSelect) ProtoMessage() {}

func (x *JobSelect) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_job_svc_g_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JobSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *JobSelect) GetLabels() bool {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return false
}

func (x *JobSelect) GetRef() bool {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return false
}

func (x *JobSelect) GetSource() *StoreSelect {
	if x != nil {
		return x.xxx_hidden_Source
	}
	return nil
}

func (x *JobSelect) GetTarget() *StoreSelect {
	if x != nil {
		return x.xxx_hidden_Target
	}
	return nil
}

func (x *JobSelect) GetPlatforms() bool {
	if x != nil {
		return x.xxx_hidden_Platforms
	}
	return false
}

func (x *JobSelect) GetAs() bool {
	if x != nil {
		return x.xxx_hidden_As
	}
	return false
}

func (x *JobSelect) GetDateEnded() bool {
	if x != nil {
		return x.xxx_hidden_DateEnded
	}
	return false
}

func (x *JobSelect) GetDateStarted() bool {
	if x != nil {
		return x.xxx_hidden_DateStarted
	}
	return false
}

func (x *JobSelect) GetDateCreated() bool {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return false
}

func (x *JobSelect) GetState() bool {
	if x != nil {
		return x.xxx_hidden_State
	}
	return false
}

func (x *JobSelect) GetError() bool {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return false
}

func (x *JobSelect) GetVerification() bool {
	if x != nil {
		return x.xxx_hidden_Verification
	}
	return false
}

func (x *JobSelect) GetTransfers() bool {
	if x != nil {
		return x.xxx_hidden_Transfers
	}
	return false
}

func (x *JobSelect) GetCopyReferrers() bool {
	if x != nil {
		return x.xxx_hidden_CopyReferrers
	}
	return false
}

func (x *JobSelect) GetFallbackToOrigin() bool {
	if x != nil {
		return x.xxx_hidden_FallbackToOrigin
	}
	return false
}

func (x *JobSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 16)
}

func (x *JobSelect) SetLabels(v bool) {
	x.xxx_hidden_Labels = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 16)
}

func (x *JobSelect) SetRef(v bool) {
	x.xxx_hidden_Ref = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 16)
}

func (x *JobSelect) SetSource(v *StoreSelect) {
	x.xxx_hidden_Source = v
}

func (x *JobSelect) SetTarget(v *StoreSelect) {
	x.xxx_hidden_Target = v
}

func (x *JobSelect) SetPlatforms(v bool) {
	x.xxx_hidden_Platforms = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 16)
}

func (x *JobSelect) SetAs(v bool) {
	x.xxx_hidden_As = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 16)
}

func (x *JobSelect) SetDateEnded(v bool) {
	x.xxx_hidden_DateEnded = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 16)
}

func (x *JobSelect) SetDateStarted(v bool) {
	x.xxx_hidden_DateStarted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 16)
}

func (x *JobSelect) SetDateCreated(v bool) {
	x.xxx_hidden_DateCreated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 16)
}

func (x *JobSelect) SetState(v bool) {
	x.xxx_hidden_State = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 16)
}

func (x *JobSelect) SetError(v bool) {
	x.xxx_hidden_Error = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 16)
}

func (x *JobSelect) SetVerification(v bool) {
	x.xxx_hidden_Verification = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 12, 16)
}

func (x *JobSelect) SetTransfers(v bool) {
	x.xxx_hidden_Transfers = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 13, 16)
}

func (x *JobSelect) SetCopyReferrers(v bool) {
	x.xxx_hidden_CopyReferrers = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 14, 16)
}

func (x *JobSelect) SetFallbackToOrigin(v bool) {
	x.xxx_hidden_FallbackToOrigin = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 15, 16)
}

func (x *JobSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *JobSelect) HasLabels() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *JobSelect) HasRef() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *JobSelect) HasSource() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Source != nil
}

func (x *JobSelect) HasTarget() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Target != nil
}

func (x *JobSelect) HasPlatforms() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *JobSelect) HasAs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *JobSelect) HasDateEnded() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *JobSelect) HasDateStarted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *JobSelect) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *JobSelect) HasState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *JobSelect) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *JobSelect) HasVerification() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 12)
}

func (x *JobSelect) HasTransfers() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 13)
}

func (x *JobSelect) HasCopyReferrers() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 14)
}

func (x *JobSelect) HasFallbackToOrigin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 15)
}

func (x *JobSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *JobSelect) ClearLabels() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Labels = false
}

func (x *JobSelect) ClearRef() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Ref = false
}

func (x *JobSelect) ClearSource() {
	x.xxx_hidden_Source = nil
}

func (x *JobSelect) ClearTarget() {
	x.xxx_hidden_Target = nil
}

func (x *JobSelect) ClearPlatforms() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Platforms = false
}

func (x *JobSelect) ClearAs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_As = false
}

func (x *JobSelect) ClearDateEnded() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_DateEnded = false
}

func (x *JobSelect) ClearDateStarted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_DateStarted = false
}

func (x *JobSelect) ClearDateCreated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_DateCreated = false
}

func (x *JobSelect) ClearState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_State = false
}

func (x *JobSelect) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_Error = false
}

func (x *JobSelect) ClearVerification() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 12)
	x.xxx_hidden_Verification = false
}

func (x *JobSelect) ClearTransfers() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 13)
	x.xxx_hidden_Transfers = false
}

func (x *JobSelect) ClearCopyReferrers() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 14)
	x.xxx_hidden_CopyReferrers = false
}

func (x *JobSelect) ClearFallbackToOrigin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 15)
	x.xxx_hidden_FallbackToOrigin = false
}

type JobSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All              *bool
	Labels           *bool
	Ref              *bool
	Source           *StoreSelect
	Target           *StoreSelect
	Platforms        *bool
	As               *bool
	DateEnded        *bool
	DateStarted      *bool
	DateCreated      *bool
	State            *bool
	Error            *bool
	Verification     *bool
	Transfers        *bool
	CopyReferrers    *bool
	FallbackToOrigin *bool
}

func (b0 JobSelect_builder) Build() *JobSelect {
	m0 := &JobSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 16)
		x.xxx_hidden_All = *b.All
	}
	if b.Labels != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 16)
		x.xxx_hidden_Labels = *b.Labels
	}
	if b.Ref != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 16)
		x.xxx_hidden_Ref = *b.Ref
	}
	x.xxx_hidden_Source = b.Source
	x.xxx_hidden_Target = b.Target
	if b.Platforms != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 16)
		x.xxx_hidden_Platforms = *b.Platforms
	}
	if b.As != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 16)
		x.xxx_hidden_As = *b.As
	}
	if b.DateEnded != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 16)
		x.xxx_hidden_DateEnded = *b.DateEnded
	}
	if b.DateStarted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 16)
		x.xxx_hidden_DateStarted = *b.DateStarted
	}
	if b.DateCreated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 16)
		x.xxx_hidden_DateCreated = *b.DateCreated
	}
	if b.State != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 16)
		x.xxx_hidden_State = *b.State
	}
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 16)
		x.xxx_hidden_Error = *b.Error
	}
	if b.Verification != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 12, 16)
		x.xxx_hidden_Verification = *b.Verification
	}
	if b.Transfers != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 13, 16)
		x.xxx_hidden_Transfers = *b.Transfers
	}
	if b.CopyReferrers != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 14, 16)
		x.xxx_hidden_CopyReferrers = *b.CopyReferrers
	}
	if b.FallbackToOrigin != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 15, 16)
		x.xxx_hidden_FallbackToOrigin = *b.FallbackToOrigin
	}
	return m0
}

type JobPatchRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref              *JobRef                `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Labels           map[string]string      `protobuf:"bytes,13,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_DateEnded        *timestamppb.Timestamp `protobuf:"bytes,25,opt,name=date_ended,json=dateEnded"`
	xxx_hidden_DateStarted      *timestamppb.Timestamp `protobuf:"bytes,27,opt,name=date_started,json=dateStarted"`
	xxx_hidden_State            JobState               `protobuf:"varint,31,opt,name=state,enum=gantry.JobState"`
	xxx_hidden_Error            *string                `protobuf:"bytes,33,opt,name=error"`
	xxx_hidden_Verification     *Verification          `protobuf:"bytes,35,opt,name=verification"`
	xxx_hidden_VerificationNull bool                   `protobuf:"varint,36,opt,name=verification_null,json=verificationNull"`
	xxx_hidden_Transfers        *[]*Transfer           `protobuf:"bytes,37,rep,name=transfers"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *JobPatchRequest) Reset() {
	*x = JobPatchRequest{}
	mi := &file_gantry_job_svc_g_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobPatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobPatchRequest) ProtoMessage() {}

func (x *JobPatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_job_svc_g_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JobPatchRequest) GetRef() *JobRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *JobPatchRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *JobPatchRequest) GetDateEnded() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateEnded
	}
	return nil
}

func (x *JobPatchRequest) GetDateStarted() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateStarted
	}
	return nil
}

func (x *JobPatchRequest) GetState() JobState {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 4) {
			return x.xxx_hidden_State
		}
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *JobPatchRequest) GetError() string {
	if x != nil {
		if x.xxx_hidden_Error != nil {
			return *x.xxx_hidden_Error
		}
		return ""
	}
	return ""
}

func (x *JobPatchRequest) GetVerification() *Verification {
	if x != nil {
		return x.xxx_hidden_Verification
	}
	return nil
}

func (x *JobPatchRequest) GetVerificationNull() bool {
	if x != nil {
		return x.xxx_hidden_VerificationNull
	}
	return false
}

func (x *JobPatchRequest) GetTransfers() []*Transfer {
	if x != nil {
		if x.xxx_hidden_Transfers != nil {
			return *x.xxx_hidden_Transfers
		}
	}
	return nil
}

func (x *JobPatchRequest) SetRef(v *JobRef) {
	x.xxx_hidden_Ref = v
}

func (x *JobPatchRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *JobPatchRequest) SetDateEnded(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateEnded = v
}

func (x *JobPatchRequest) SetDateStarted(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateStarted = v
}

func (x *JobPatchRequest) SetState(v JobState) {
	x.xxx_hidden_State = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *JobPatchRequest) SetError(v string) {
	x.xxx_hidden_Error = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *JobPatchRequest) SetVerification(v *Verification) {
	x.xxx_hidden_Verification = v
}

func (x *JobPatchRequest) SetVerificationNull(v bool) {
	x.xxx_hidden_VerificationNull = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 9)
}

func (x *JobPatchRequest) SetTransfers(v []*Transfer) {
	x.xxx_hidden_Transfers = &v
}

func (x *JobPatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *JobPatchRequest) HasDateEnded() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateEnded != nil
}

func (x *JobPatchRequest) HasDateStarted() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateStarted != nil
}

func (x *JobPatchRequest) HasState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *JobPatchRequest) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *JobPatchRequest) HasVerification() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Verification != nil
}

func (x *JobPatchRequest) HasVerificationNull() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *JobPatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *JobPatchRequest) ClearDateEnded() {
	x.xxx_hidden_DateEnded = nil
}

func (x *JobPatchRequest) ClearDateStarted() {
	x.xxx_hidden_DateStarted = nil
}

func (x *JobPatchRequest) ClearState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_State = JobState_JOB_STATE_UNSPECIFIED
}

func (x *JobPatchRequest) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Error = nil
}

func (x *JobPatchRequest) ClearVerification() {
	x.xxx_hidden_Verification = nil
}

func (x *JobPatchRequest) ClearVerificationNull() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_VerificationNull = false
}

type JobPatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref              *JobRef
	Labels           map[string]string
	DateEnded        *timestamppb.Timestamp
	DateStarted      *timestamppb.Timestamp
	State            *JobState
	Error            *string
	Verification     *Verification
	VerificationNull *bool
	Transfers        []*Transfer
}

func (b0 JobPatchRequest_builder) Build() *JobPatchRequest {
	m0 := &JobPatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_DateEnded = b.DateEnded
	x.xxx_hidden_DateStarted = b.DateStarted
	if b.State != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_State = *b.State
	}
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_Error = b.Error
	}
	x.xxx_hidden_Verification = b.Verification
	if b.VerificationNull != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 9)
		x.xxx_hidden_VerificationNull = *b.VerificationNull
	}
	x.xxx_hidden_Transfers = &b.Transfers
	return m0
}

type JobListRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_State       JobState               `protobuf:"varint,1,opt,name=state,enum=gantry.JobState"`
	xxx_hidden_Ref         *string                `protobuf:"bytes,2,opt,name=ref"`
	xxx_hidden_Since       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=since"`
	xxx_hidden_Labels      map[string]string      `protobuf:"bytes,4,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_PageSize    int32                  `protobuf:"varint,10,opt,name=page_size,json=pageSize"`
	xxx_hidden_PageToken   *string                `protobuf:"bytes,11,opt,name=page_token,json=pageToken"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *JobListRequest) Reset() {
	*x = JobListRequest{}
	mi := &file_gantry_job_svc_g_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobListRequest) ProtoMessage() {}

func (x *JobListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_job_svc_g_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JobListRequest) GetState() JobState {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_State
		}
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *JobListRequest) GetRef() string {
	if x != nil {
		if x.xxx_hidden_Ref != nil {
			return *x.xxx_hidden_Ref
		}
		return ""
	}
	return ""
}

func (x *JobListRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Since
	}
	return nil
}

func (x *JobListRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *JobListRequest) GetPageSize() int32 {
	if x != nil {
		return x.xxx_hidden_PageSize
	}
	return 0
}

func (x *JobListRequest) GetPageToken() string {
	if x != nil {
		if x.xxx_hidden_PageToken != nil {
			return *x.xxx_hidden_PageToken
		}
		return ""
	}
	return ""
}

func (x *JobListRequest) SetState(v JobState) {
	x.xxx_hidden_State = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *JobListRequest) SetRef(v string) {
	x.xxx_hidden_Ref = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *JobListRequest) SetSince(v *timestamppb.Timestamp) {
	x.xxx_hidden_Since = v
}

func (x *JobListRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *JobListRequest) SetPageSize(v int32) {
	x.xxx_hidden_PageSize = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *JobListRequest) SetPageToken(v string) {
	x.xxx_hidden_PageToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *JobListRequest) HasState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *JobListRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *JobListRequest) HasSince() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Since != nil
}

func (x *JobListRequest) HasPageSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *JobListRequest) HasPageToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *JobListRequest) ClearState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_State = JobState_JOB_STATE_UNSPECIFIED
}

func (x *JobListRequest) ClearRef() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Ref = nil
}

func (x *JobListRequest) ClearSince() {
	x.xxx_hidden_Since = nil
}

func (x *JobListRequest) ClearPageSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_PageSize = 0
}

func (x *JobListRequest) ClearPageToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_PageToken = nil
}

type JobListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Keep only jobs in this state.
	State *JobState
	// Substring match on the requested ref.
	Ref *string
	// Jobs created at or after this instant.
	Since *timestamppb.Timestamp
	// Label selector: a job matches when it carries every key with the given
	// value (subset match). An empty map matches everything.
	Labels map[string]string
	// Maximum items to return; 0 = no limit.
	PageSize *int32
	// Continuation token from the previous response; empty starts from the
	// beginning.
	PageToken *string
}

func (b0 JobListRequest_builder) Build() *JobListRequest {
	m0 := &JobListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.State != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_State = *b.State
	}
	if b.Ref != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Ref = b.Ref
	}
	x.xxx_hidden_Since = b.Since
	x.xxx_hidden_Labels = b.Labels
	if b.PageSize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_PageSize = *b.PageSize
	}
	if b.PageToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_PageToken = b.PageToken
	}
	return m0
}

type JobListResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items         *[]*Job                `protobuf:"bytes,1,rep,name=items"`
	xxx_hidden_NextPageToken *string                `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *JobListResponse) Reset() {
	*x = JobListResponse{}
	mi := &file_gantry_job_svc_g_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobListResponse) ProtoMessage() {}

func (x *JobListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_job_svc_g_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JobListResponse) GetItems() []*Job {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *JobListResponse) GetNextPageToken() string {
	if x != nil {
		if x.xxx_hidden_NextPageToken != nil {
			return *x.xxx_hidden_NextPageToken
		}
		return ""
	}
	return ""
}

func (x *JobListResponse) SetItems(v []*Job) {
	x.xxx_hidden_Items = &v
}

func (x *JobListResponse) SetNextPageToken(v string) {
	x.xxx_hidden_NextPageToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *JobListResponse) HasNextPageToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *JobListResponse) ClearNextPageToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NextPageToken = nil
}

type JobListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// One page of results, newest-first.
	Items []*Job
	// Empty when there are no further results.
	NextPageToken *string
}

func (b0 JobListResponse_builder) Build() *JobListResponse {
	m0 := &JobListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	if b.NextPageToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_NextPageToken = b.NextPageToken
	}
	return m0
}

// The same inputs as JobAddRequest, evaluated without submitting.
type JobPlanRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref              *string                `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Source           *StoreRef              `protobuf:"bytes,2,opt,name=source"`
	xxx_hidden_Target           *StoreRef              `protobuf:"bytes,3,opt,name=target"`
	xxx_hidden_Platforms        []string               `protobuf:"bytes,4,rep,name=platforms"`
	xxx_hidden_CopyReferrers    bool                   `protobuf:"varint,5,opt,name=copy_referrers,json=copyReferrers"`
	xxx_hidden_As               []string               `protobuf:"bytes,6,rep,name=as"`
	xxx_hidden_FallbackToOrigin bool                   `protobuf:"varint,7,opt,name=fallback_to_origin,json=fallbackToOrigin"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *JobPlanRequest) Reset() {
	*x = JobPlanRequest{}
	mi := &file_gantry_job_svc_g_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobPlanRequest) ProtoMessage() {}

func (x *JobPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_job_svc_g_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JobPlanRequest) GetRef() string {
	if x != nil {
		if x.xxx_hidden_Ref != nil {
			return *x.xxx_hidden_Ref
		}
		return ""
	}
	return ""
}

func (x *JobPlanRequest) GetSource() *StoreRef {
	if x != nil {
		return x.xxx_hidden_Source
	}
	return nil
}

func (x *JobPlanRequest) GetTarget() *StoreRef {
	if x != nil {
		return x.xxx_hidden_Target
	}
	return nil
}

func (x *JobPlanRequest) GetPlatforms() []string {
	if x != nil {
		return x.xxx_hidden_Platforms
	}
	return nil
}

func (x *JobPlanRequest) GetCopyReferrers() bool {
	if x != nil {
		return x.xxx_hidden_CopyReferrers
	}
	return false
}

func (x *JobPlanRequest) GetAs() []string {
	if x != nil {
		return x.xxx_hidden_As
	}
	return nil
}

func (x *JobPlanRequest) GetFallbackToOrigin() bool {
	if x != nil {
		return x.xxx_hidden_FallbackToOrigin
	}
	return false
}

func (x *JobPlanRequest) SetRef(v string) {
	x.xxx_hidden_Ref = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *JobPlanRequest) SetSource(v *StoreRef) {
	x.xxx_hidden_Source = v
}

func (x *JobPlanRequest) SetTarget(v *StoreRef) {
	x.xxx_hidden_Target = v
}

func (x *JobPlanRequest) SetPlatforms(v []string) {
	x.xxx_hidden_Platforms = v
}

func (x *JobPlanRequest) SetCopyReferrers(v bool) {
	x.xxx_hidden_CopyReferrers = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *JobPlanRequest) SetAs(v []string) {
	x.xxx_hidden_As = v
}

func (x *JobPlanRequest) SetFallbackToOrigin(v bool) {
	x.xxx_hidden_FallbackToOrigin = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *JobPlanRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *JobPlanRequest) HasSource() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Source != nil
}

func (x *JobPlanRequest) HasTarget() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Target != nil
}

func (x *JobPlanRequest) HasCopyReferrers() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *JobPlanRequest) HasFallbackToOrigin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *JobPlanRequest) ClearRef() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Ref = nil
}

func (x *JobPlanRequest) ClearSource() {
	x.xxx_hidden_Source = nil
}

func (x *JobPlanRequest) ClearTarget() {
	x.xxx_hidden_Target = nil
}

func (x *JobPlanRequest) ClearCopyReferrers() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_CopyReferrers = false
}

func (x *JobPlanRequest) ClearFallbackToOrigin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_FallbackToOrigin = false
}

type JobPlanRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Image reference to move.
	Ref *string
	// Source registry; defaults to the ref's registry.
	Source *StoreRef
	// Target store: a registry or an engine.
	Target *StoreRef
	// Registry target: platforms to copy (empty = all). Engine target: the
	// single platform to pull (empty = daemon's).
	Platforms []string
	// Copy source referrer artifacts along with the image; absent = server
	// default.
	CopyReferrers *bool
	// Engine target only: names the image would be recorded under.
	As []string
	// Engine target only: pull from the registry named in `ref` when `source`
	// cannot serve the image; absent = server default.
	FallbackToOrigin *bool
}

func (b0 JobPlanRequest_builder) Build() *JobPlanRequest {
	m0 := &JobPlanRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Ref != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Ref = b.Ref
	}
	x.xxx_hidden_Source = b.Source
	x.xxx_hidden_Target = b.Target
	x.xxx_hidden_Platforms = b.Platforms
	if b.CopyReferrers != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_CopyReferrers = *b.CopyReferrers
	}
	x.xxx_hidden_As = b.As
	if b.FallbackToOrigin != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_FallbackToOrigin = *b.FallbackToOrigin
	}
	return m0
}

type JobPlanResponse struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Source           *string                `protobuf:"bytes,1,opt,name=source"`
	xxx_hidden_Target           *string                `protobuf:"bytes,2,opt,name=target"`
	xxx_hidden_SourceRef        *string                `protobuf:"bytes,3,opt,name=source_ref,json=sourceRef"`
	xxx_hidden_TargetRef        *string                `protobuf:"bytes,4,opt,name=target_ref,json=targetRef"`
	xxx_hidden_Platforms        []string               `protobuf:"bytes,5,rep,name=platforms"`
	xxx_hidden_CopyReferrers    bool                   `protobuf:"varint,6,opt,name=copy_referrers,json=copyReferrers"`
	xxx_hidden_Verification     *Verification          `protobuf:"bytes,7,opt,name=verification"`
	xxx_hidden_Coalesces        *string                `protobuf:"bytes,8,opt,name=coalesces"`
	xxx_hidden_As               []string               `protobuf:"bytes,9,rep,name=as"`
	xxx_hidden_FallbackToOrigin bool                   `protobuf:"varint,10,opt,name=fallback_to_origin,json=fallbackToOrigin"`
	xxx_hidden_FallbackRef      *string                `protobuf:"bytes,11,opt,name=fallback_ref,json=fallbackRef"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *JobPlanResponse) Reset() {
	*x = JobPlanResponse{}
	mi := &file_gantry_job_svc_g_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobPlanResponse) ProtoMessage() {}

func (x *JobPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_job_svc_g_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JobPlanResponse) GetSource() string {
	if x != nil {
		if x.xxx_hidden_Source != nil {
			return *x.xxx_hidden_Source
		}
		return ""
	}
	return ""
}

func (x *JobPlanResponse) GetTarget() string {
	if x != nil {
		if x.xxx_hidden_Target != nil {
			return *x.xxx_hidden_Target
		}
		return ""
	}
	return ""
}

func (x *JobPlanResponse) GetSourceRef() string {
	if x != nil {
		if x.xxx_hidden_SourceRef != nil {
			return *x.xxx_hidden_SourceRef
		}
		return ""
	}
	return ""
}

func (x *JobPlanResponse) GetTargetRef() string {
	if x != nil {
		if x.xxx_hidden_TargetRef != nil {
			return *x.xxx_hidden_TargetRef
		}
		return ""
	}
	return ""
}

func (x *JobPlanResponse) GetPlatforms() []string {
	if x != nil {
		return x.xxx_hidden_Platforms
	}
	return nil
}

func (x *JobPlanResponse) GetCopyReferrers() bool {
	if x != nil {
		return x.xxx_hidden_CopyReferrers
	}
	return false
}

func (x *JobPlanResponse) GetVerification() *Verification {
	if x != nil {
		return x.xxx_hidden_Verification
	}
	return nil
}

func (x *JobPlanResponse) GetCoalesces() string {
	if x != nil {
		if x.xxx_hidden_Coalesces != nil {
			return *x.xxx_hidden_Coalesces
		}
		return ""
	}
	return ""
}

func (x *JobPlanResponse) GetAs() []string {
	if x != nil {
		return x.xxx_hidden_As
	}
	return nil
}

func (x *JobPlanResponse) GetFallbackToOrigin() bool {
	if x != nil {
		return x.xxx_hidden_FallbackToOrigin
	}
	return false
}

func (x *JobPlanResponse) GetFallbackRef() string {
	if x != nil {
		if x.xxx_hidden_FallbackRef != nil {
			return *x.xxx_hidden_FallbackRef
		}
		return ""
	}
	return ""
}

func (x *JobPlanResponse) SetSource(v string) {
	x.xxx_hidden_Source = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 11)
}

func (x *JobPlanResponse) SetTarget(v string) {
	x.xxx_hidden_Target = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 11)
}

func (x *JobPlanResponse) SetSourceRef(v string) {
	x.xxx_hidden_SourceRef = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 11)
}

func (x *JobPlanResponse) SetTargetRef(v string) {
	x.xxx_hidden_TargetRef = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 11)
}

func (x *JobPlanResponse) SetPlatforms(v []string) {
	x.xxx_hidden_Platforms = v
}

func (x *JobPlanResponse) SetCopyReferrers(v bool) {
	x.xxx_hidden_CopyReferrers = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 11)
}

func (x *JobPlanResponse) SetVerification(v *Verification) {
	x.xxx_hidden_Verification = v
}

func (x *JobPlanResponse) SetCoalesces(v string) {
	x.xxx_hidden_Coalesces = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 11)
}

func (x *JobPlanResponse) SetAs(v []string) {
	x.xxx_hidden_As = v
}

func (x *JobPlanResponse) SetFallbackToOrigin(v bool) {
	x.xxx_hidden_FallbackToOrigin = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 11)
}

func (x *JobPlanResponse) SetFallbackRef(v string) {
	x.xxx_hidden_FallbackRef = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 11)
}

func (x *JobPlanResponse) HasSource() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *JobPlanResponse) HasTarget() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *JobPlanResponse) HasSourceRef() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *JobPlanResponse) HasTargetRef() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *JobPlanResponse) HasCopyReferrers() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *JobPlanResponse) HasVerification() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Verification != nil
}

func (x *JobPlanResponse) HasCoalesces() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *JobPlanResponse) HasFallbackToOrigin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *JobPlanResponse) HasFallbackRef() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *JobPlanResponse) ClearSource() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Source = nil
}

func (x *JobPlanResponse) ClearTarget() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Target = nil
}

func (x *JobPlanResponse) ClearSourceRef() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SourceRef = nil
}

func (x *JobPlanResponse) ClearTargetRef() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_TargetRef = nil
}

func (x *JobPlanResponse) ClearCopyReferrers() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_CopyReferrers = false
}

func (x *JobPlanResponse) ClearVerification() {
	x.xxx_hidden_Verification = nil
}

func (x *JobPlanResponse) ClearCoalesces() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Coalesces = nil
}

func (x *JobPlanResponse) ClearFallbackToOrigin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_FallbackToOrigin = false
}

func (x *JobPlanResponse) ClearFallbackRef() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_FallbackRef = nil
}

type JobPlanResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Resolved source store name.
	Source *string
	// Resolved target store name.
	Target *string
	// Source-side ref, digest-pinned when verified.
	SourceRef *string
	// Target-side ref: the rewritten cache ref, or the ref the engine
	// is told to pull.
	TargetRef *string
	// Registry target: empty = all platforms; engine target: the
	// single platform pulled.
	Platforms []string
	// Effective value after the server default is applied.
	CopyReferrers *bool
	// Admission verification outcome, when verification ran.
	Verification *Verification
	// The active job an identical submit would coalesce onto, if any.
	Coalesces *string
	// Engine target: the (normalized) names the image is recorded under.
	As []string
	// Effective value after the server default is applied.
	FallbackToOrigin *bool
	// Engine target: the ref the engine would be told to pull if `source` could
	// not serve the image. Empty when the job has no fallback — the flag is off,
	// `source` already is the origin, or the origin is not addressable from this
	// engine.
	FallbackRef *string
}

func (b0 JobPlanResponse_builder) Build() *JobPlanResponse {
	m0 := &JobPlanResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Source != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 11)
		x.xxx_hidden_Source = b.Source
	}
	if b.Target != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 11)
		x.xxx_hidden_Target = b.Target
	}
	if b.SourceRef != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 11)
		x.xxx_hidden_SourceRef = b.SourceRef
	}
	if b.TargetRef != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 11)
		x.xxx_hidden_TargetRef = b.TargetRef
	}
	x.xxx_hidden_Platforms = b.Platforms
	if b.CopyReferrers != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 11)
		x.xxx_hidden_CopyReferrers = *b.CopyReferrers
	}
	x.xxx_hidden_Verification = b.Verification
	if b.Coalesces != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 11)
		x.xxx_hidden_Coalesces = b.Coalesces
	}
	x.xxx_hidden_As = b.As
	if b.FallbackToOrigin != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 11)
		x.xxx_hidden_FallbackToOrigin = *b.FallbackToOrigin
	}
	if b.FallbackRef != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 11)
		x.xxx_hidden_FallbackRef = b.FallbackRef
	}
	return m0
}

var File_gantry_job_svc_g_proto protoreflect.FileDescriptor

const file_gantry_job_svc_g_proto_rawDesc = "" +
	"\n" +
	"\x16gantry/job_svc.g.proto\x12\x06gantry\x1a\x10gantry/job.proto\x1a\x18gantry/store_svc.g.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf4\x05\n" +
	"\rJobAddRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\x06labels\x18\a \x03(\v2!.gantry.JobAddRequest.LabelsEntryR\x06labels\x12\x17\n" +
	"\x03ref\x18\b \x01(\tB\x05\xaa\x01\x02\b\x02R\x03ref\x12(\n" +
	"\x06source\x18\t \x01(\v2\x10.gantry.StoreRefR\x06source\x12(\n" +
	"\x06target\x18\n" +
	" \x01(\v2\x10.gantry.StoreRefR\x06target\x12\x1c\n" +
	"\tplatforms\x18\v \x03(\tR\tplatforms\x12\x0e\n" +
	"\x02as\x18\f \x03(\tR\x02as\x129\n" +
	"\n" +
	"date_ended\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tdateEnded\x12=\n" +
	"\fdate_started\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vdateStarted\x12=\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vdateCreated\x12-\n" +
	"\x05state\x18\x10 \x01(\x0e2\x10.gantry.JobStateB\x05\xaa\x01\x02\b\x02R\x05state\x12\x1b\n" +
	"\x05error\x18\x11 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05error\x128\n" +
	"\fverification\x18\x12 \x01(\v2\x14.gantry.VerificationR\fverification\x12.\n" +
	"\ttransfers\x18\x13 \x03(\v2\x10.gantry.TransferR\ttransfers\x12%\n" +
	"\x0ecopy_referrers\x18\x14 \x01(\bR\rcopyReferrers\x12,\n" +
	"\x12fallback_to_origin\x18\x15 \x01(\bR\x10fallbackToOrigin\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\rJobGetRequest\x12 \n" +
	"\x03ref\x18\x01 \x01(\v2\x0e.gantry.JobRefR\x03ref\x12)\n" +
	"\x06select\x18\x02 \x01(\v2\x11.gantry.JobSelectR\x06select\"!\n" +
	"\x06JobRef\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02idB\x05\n" +
	"\x03key\"\xf7\x03\n" +
	"\tJobSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x16\n" +
	"\x06labels\x18\a \x01(\bR\x06labels\x12\x10\n" +
	"\x03ref\x18\b \x01(\bR\x03ref\x12+\n" +
	"\x06source\x18\t \x01(\v2\x13.gantry.StoreSelectR\x06source\x12+\n" +
	"\x06target\x18\n" +
	" \x01(\v2\x13.gantry.StoreSelectR\x06target\x12\x1c\n" +
	"\tplatforms\x18\v \x01(\bR\tplatforms\x12\x0e\n" +
	"\x02as\x18\f \x01(\bR\x02as\x12\x1d\n" +
	"\n" +
	"date_ended\x18\r \x01(\bR\tdateEnded\x12!\n" +
	"\fdate_started\x18\x0e \x01(\bR\vdateStarted\x12!\n" +
	"\fdate_created\x18\x0f \x01(\bR\vdateCreated\x12\x14\n" +
	"\x05state\x18\x10 \x01(\bR\x05state\x12\x14\n" +
	"\x05error\x18\x11 \x01(\bR\x05error\x12\"\n" +
	"\fverification\x18\x12 \x01(\bR\fverification\x12\x1c\n" +
	"\ttransfers\x18\x13 \x01(\bR\ttransfers\x12%\n" +
	"\x0ecopy_referrers\x18\x14 \x01(\bR\rcopyReferrers\x12,\n" +
	"\x12fallback_to_origin\x18\x15 \x01(\bR\x10fallbackToOrigin\"\xfa\x03\n" +
	"\x0fJobPatchRequest\x12 \n" +
	"\x03ref\x18\x01 \x01(\v2\x0e.gantry.JobRefR\x03ref\x12;\n" +
	"\x06labels\x18\r \x03(\v2#.gantry.JobPatchRequest.LabelsEntryR\x06labels\x129\n" +
	"\n" +
	"date_ended\x18\x19 \x01(\v2\x1a.google.protobuf.TimestampR\tdateEnded\x12=\n" +
	"\fdate_started\x18\x1b \x01(\v2\x1a.google.protobuf.TimestampR\vdateStarted\x12&\n" +
	"\x05state\x18\x1f \x01(\x0e2\x10.gantry.JobStateR\x05state\x12\x14\n" +
	"\x05error\x18! \x01(\tR\x05error\x128\n" +
	"\fverification\x18# \x01(\v2\x14.gantry.VerificationR\fverification\x12+\n" +
	"\x11verification_null\x18$ \x01(\bR\x10verificationNull\x12.\n" +
	"\ttransfers\x18% \x03(\v2\x10.gantry.TransferR\ttransfers\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x02\n" +
	"\x0eJobListRequest\x12&\n" +
	"\x05state\x18\x01 \x01(\x0e2\x10.gantry.JobStateR\x05state\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x120\n" +
	"\x05since\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12:\n" +
	"\x06labels\x18\x04 \x03(\v2\".gantry.JobListRequest.LabelsEntryR\x06labels\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\v \x01(\tR\tpageToken\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\x0fJobListResponse\x12!\n" +
	"\x05items\x18\x01 \x03(\v2\v.gantry.JobR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xf9\x01\n" +
	"\x0eJobPlanRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12(\n" +
	"\x06source\x18\x02 \x01(\v2\x10.gantry.StoreRefR\x06source\x12(\n" +
	"\x06target\x18\x03 \x01(\v2\x10.gantry.StoreRefR\x06target\x12\x1c\n" +
	"\tplatforms\x18\x04 \x03(\tR\tplatforms\x12%\n" +
	"\x0ecopy_referrers\x18\x05 \x01(\bR\rcopyReferrers\x12\x0e\n" +
	"\x02as\x18\x06 \x03(\tR\x02as\x12,\n" +
	"\x12fallback_to_origin\x18\a \x01(\bR\x10fallbackToOrigin\"\xfd\x02\n" +
	"\x0fJobPlanResponse\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1d\n" +
	"\n" +
	"source_ref\x18\x03 \x01(\tR\tsourceRef\x12\x1d\n" +
	"\n" +
	"target_ref\x18\x04 \x01(\tR\ttargetRef\x12\x1c\n" +
	"\tplatforms\x18\x05 \x03(\tR\tplatforms\x12%\n" +
	"\x0ecopy_referrers\x18\x06 \x01(\bR\rcopyReferrers\x128\n" +
	"\fverification\x18\a \x01(\v2\x14.gantry.VerificationR\fverification\x12\x1c\n" +
	"\tcoalesces\x18\b \x01(\tR\tcoalesces\x12\x0e\n" +
	"\x02as\x18\t \x03(\tR\x02as\x12,\n" +
	"\x12fallback_to_origin\x18\n" +
	" \x01(\bR\x10fallbackToOrigin\x12!\n" +
	"\ffallback_ref\x18\v \x01(\tR\vfallbackRef2\xa9\x03\n" +
	"\n" +
	"JobService\x12)\n" +
	"\x03Add\x12\x15.gantry.JobAddRequest\x1a\v.gantry.Job\x12)\n" +
	"\x03Get\x12\x15.gantry.JobGetRequest\x1a\v.gantry.Job\x12-\n" +
	"\x05Patch\x12\x17.gantry.JobPatchRequest\x1a\v.gantry.Job\x12/\n" +
	"\x05Erase\x12\x0e.gantry.JobRef\x1a\x16.google.protobuf.Empty\x127\n" +
	"\x04List\x12\x16.gantry.JobListRequest\x1a\x17.gantry.JobListResponse\x12&\n" +
	"\x05Watch\x12\x0e.gantry.JobRef\x1a\v.gantry.Job0\x01\x127\n" +
	"\x04Plan\x12\x16.gantry.JobPlanRequest\x1a\x17.gantry.JobPlanResponse\x12%\n" +
	"\x06Cancel\x12\x0e.gantry.JobRef\x1a\v.gantry.Job\x12$\n" +
	"\x05Retry\x12\x0e.gantry.JobRef\x1a\v.gantry.JobB\x1fZ\x1dgithub.com/lesomnus/gantry/pbb\beditionsp\xe8\a"

var file_gantry_job_svc_g_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_gantry_job_svc_g_proto_goTypes = []any{
	(*JobAddRequest)(nil),         // 0: gantry.JobAddRequest
	(*JobGetRequest)(nil),         // 1: gantry.JobGetRequest
	(*JobRef)(nil),                // 2: gantry.JobRef
	(*JobSelect)(nil),             // 3: gantry.JobSelect
	(*JobPatchRequest)(nil),       // 4: gantry.JobPatchRequest
	(*JobListRequest)(nil),        // 5: gantry.JobListRequest
	(*JobListResponse)(nil),       // 6: gantry.JobListResponse
	(*JobPlanRequest)(nil),        // 7: gantry.JobPlanRequest
	(*JobPlanResponse)(nil),       // 8: gantry.JobPlanResponse
	nil,                           // 9: gantry.JobAddRequest.LabelsEntry
	nil,                           // 10: gantry.JobPatchRequest.LabelsEntry
	nil,                           // 11: gantry.JobListRequest.LabelsEntry
	(*StoreRef)(nil),              // 12: gantry.StoreRef
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(JobState)(0),                 // 14: gantry.JobState
	(*Verification)(nil),          // 15: gantry.Verification
	(*Transfer)(nil),              // 16: gantry.Transfer
	(*StoreSelect)(nil),           // 17: gantry.StoreSelect
	(*Job)(nil),                   // 18: gantry.Job
	(*emptypb.Empty)(nil),         // 19: google.protobuf.Empty
}
var file_gantry_job_svc_g_proto_depIdxs = []int32{
	9,  // 0: gantry.JobAddRequest.labels:type_name -> gantry.JobAddRequest.LabelsEntry
	12, // 1: gantry.JobAddRequest.source:type_name -> gantry.StoreRef
	12, // 2: gantry.JobAddRequest.target:type_name -> gantry.StoreRef
	13, // 3: gantry.JobAddRequest.date_ended:type_name -> google.protobuf.Timestamp
	13, // 4: gantry.JobAddRequest.date_started:type_name -> google.protobuf.Timestamp
	13, // 5: gantry.JobAddRequest.date_created:type_name -> google.protobuf.Timestamp
	14, // 6: gantry.JobAddRequest.state:type_name -> gantry.JobState
	15, // 7: gantry.JobAddRequest.verification:type_name -> gantry.Verification
	16, // 8: gantry.JobAddRequest.transfers:type_name -> gantry.Transfer
	2,  // 9: gantry.JobGetRequest.ref:type_name -> gantry.JobRef
	3,  // 10: gantry.JobGetRequest.select:type_name -> gantry.JobSelect
	17, // 11: gantry.JobSelect.source:type_name -> gantry.StoreSelect
	17, // 12: gantry.JobSelect.target:type_name -> gantry.StoreSelect
	2,  // 13: gantry.JobPatchRequest.ref:type_name -> gantry.JobRef
	10, // 14: gantry.JobPatchRequest.labels:type_name -> gantry.JobPatchRequest.LabelsEntry
	13, // 15: gantry.JobPatchRequest.date_ended:type_name -> google.protobuf.Timestamp
	13, // 16: gantry.JobPatchRequest.date_started:type_name -> google.protobuf.Timestamp
	14, // 17: gantry.JobPatchRequest.state:type_name -> gantry.JobState
	15, // 18: gantry.JobPatchRequest.verification:type_name -> gantry.Verification
	16, // 19: gantry.JobPatchRequest.transfers:type_name -> gantry.Transfer
	14, // 20: gantry.JobListRequest.state:type_name -> gantry.JobState
	13, // 21: gantry.JobListRequest.since:type_name -> google.protobuf.Timestamp
	11, // 22: gantry.JobListRequest.labels:type_name -> gantry.JobListRequest.LabelsEntry
	18, // 23: gantry.JobListResponse.items:type_name -> gantry.Job
	12, // 24: gantry.JobPlanRequest.source:type_name -> gantry.StoreRef
	12, // 25: gantry.JobPlanRequest.target:type_name -> gantry.StoreRef
	15, // 26: gantry.JobPlanResponse.verification:type_name -> gantry.Verification
	0,  // 27: gantry.JobService.Add:input_type -> gantry.JobAddRequest
	1,  // 28: gantry.JobService.Get:input_type -> gantry.JobGetRequest
	4,  // 29: gantry.JobService.Patch:input_type -> gantry.JobPatchRequest
	2,  // 30: gantry.JobService.Erase:input_type -> gantry.JobRef
	5,  // 31: gantry.JobService.List:input_type -> gantry.JobListRequest
	2,  // 32: gantry.JobService.Watch:input_type -> gantry.JobRef
	7,  // 33: gantry.JobService.Plan:input_type -> gantry.JobPlanRequest
	2,  // 34: gantry.JobService.Cancel:input_type -> gantry.JobRef
	2,  // 35: gantry.JobService.Retry:input_type -> gantry.JobRef
	18, // 36: gantry.JobService.Add:output_type -> gantry.Job
	18, // 37: gantry.JobService.Get:output_type -> gantry.Job
	18, // 38: gantry.JobService.Patch:output_type -> gantry.Job
	19, // 39: gantry.JobService.Erase:output_type -> google.protobuf.Empty
	6,  // 40: gantry.JobService.List:output_type -> gantry.JobListResponse
	18, // 41: gantry.JobService.Watch:output_type -> gantry.Job
	8,  // 42: gantry.JobService.Plan:output_type -> gantry.JobPlanResponse
	18, // 43: gantry.JobService.Cancel:output_type -> gantry.Job
	18, // 44: gantry.JobService.Retry:output_type -> gantry.Job
	36, // [36:45] is the sub-list for method output_type
	27, // [27:36] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_gantry_job_svc_g_proto_init() }
func file_gantry_job_svc_g_proto_init() {
	if File_gantry_job_svc_g_proto != nil {
		return
	}
	file_gantry_job_proto_init()
	file_gantry_store_svc_g_proto_init()
	file_gantry_job_svc_g_proto_msgTypes[2].OneofWrappers = []any{
		(*jobRef_Id)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gantry_job_svc_g_proto_rawDesc), len(file_gantry_job_svc_g_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gantry_job_svc_g_proto_goTypes,
		DependencyIndexes: file_gantry_job_svc_g_proto_depIdxs,
		MessageInfos:      file_gantry_job_svc_g_proto_msgTypes,
	}.Build()
	File_gantry_job_svc_g_proto = out.File
	file_gantry_job_svc_g_proto_goTypes = nil
	file_gantry_job_svc_g_proto_depIdxs = nil
}
