// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: gantry/pin_svc.g.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PinAddRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Store       *StoreRef              `protobuf:"bytes,2,opt,name=store"`
	xxx_hidden_Value       string                 `protobuf:"bytes,3,opt,name=value"`
	xxx_hidden_Pattern     bool                   `protobuf:"varint,4,opt,name=pattern"`
	xxx_hidden_PinnedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=pinned_at,json=pinnedAt"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PinAddRequest) Reset() {
	*x = PinAddRequest{}
	mi := &file_gantry_pin_svc_g_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinAddRequest) ProtoMessage() {}

func (x *PinAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_pin_svc_g_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PinAddRequest) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *PinAddRequest) GetStore() *StoreRef {
	if x != nil {
		return x.xxx_hidden_Store
	}
	return nil
}

func (x *PinAddRequest) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *PinAddRequest) GetPattern() bool {
	if x != nil {
		return x.xxx_hidden_Pattern
	}
	return false
}

func (x *PinAddRequest) GetPinnedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_PinnedAt
	}
	return nil
}

func (x *PinAddRequest) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *PinAddRequest) SetStore(v *StoreRef) {
	x.xxx_hidden_Store = v
}

func (x *PinAddRequest) SetValue(v string) {
	x.xxx_hidden_Value = v
}

func (x *PinAddRequest) SetPattern(v bool) {
	x.xxx_hidden_Pattern = v
}

func (x *PinAddRequest) SetPinnedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_PinnedAt = v
}

func (x *PinAddRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PinAddRequest) HasStore() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Store != nil
}

func (x *PinAddRequest) HasPinnedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PinnedAt != nil
}

func (x *PinAddRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *PinAddRequest) ClearStore() {
	x.xxx_hidden_Store = nil
}

func (x *PinAddRequest) ClearPinnedAt() {
	x.xxx_hidden_PinnedAt = nil
}

type PinAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id       []byte
	Store    *StoreRef
	Value    string
	Pattern  bool
	PinnedAt *timestamppb.Timestamp
}

func (b0 PinAddRequest_builder) Build() *PinAddRequest {
	m0 := &PinAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Store = b.Store
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_Pattern = b.Pattern
	x.xxx_hidden_PinnedAt = b.PinnedAt
	return m0
}

type PinGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *PinRef                `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *PinSelect             `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PinGetRequest) Reset() {
	*x = PinGetRequest{}
	mi := &file_gantry_pin_svc_g_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinGetRequest) ProtoMessage() {}

func (x *PinGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_pin_svc_g_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PinGetRequest) GetRef() *PinRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *PinGetRequest) GetSelect() *PinSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *PinGetRequest) SetRef(v *PinRef) {
	x.xxx_hidden_Ref = v
}

func (x *PinGetRequest) SetSelect(v *PinSelect) {
	x.xxx_hidden_Select = v
}

func (x *PinGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *PinGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *PinGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *PinGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type PinGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *PinRef
	Select *PinSelect
}

func (b0 PinGetRequest_builder) Build() *PinGetRequest {
	m0 := &PinGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type PinRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isPinRef_Key           `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PinRef) Reset() {
	*x = PinRef{}
	mi := &file_gantry_pin_svc_g_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinRef) ProtoMessage() {}

func (x *PinRef) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_pin_svc_g_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PinRef) GetId() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*pinRef_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *PinRef) GetValue() *PinRefByValue {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*pinRef_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *PinRef) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Key = &pinRef_Id{v}
}

func (x *PinRef) SetValue(v *PinRefByValue) {
	if v == nil {
		x.xxx_hidden_Key = nil
		return
	}
	x.xxx_hidden_Key = &pinRef_Value{v}
}

func (x *PinRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *PinRef) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*pinRef_Id)
	return ok
}

func (x *PinRef) HasValue() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*pinRef_Value)
	return ok
}

func (x *PinRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *PinRef) ClearId() {
	if _, ok := x.xxx_hidden_Key.(*pinRef_Id); ok {
		x.xxx_hidden_Key = nil
	}
}

func (x *PinRef) ClearValue() {
	if _, ok := x.xxx_hidden_Key.(*pinRef_Value); ok {
		x.xxx_hidden_Key = nil
	}
}

const PinRef_Key_not_set_case case_PinRef_Key = 0
const PinRef_Id_case case_PinRef_Key = 1
const PinRef_Value_case case_PinRef_Key = 2

func (x *PinRef) WhichKey() case_PinRef_Key {
	if x == nil {
		return PinRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *pinRef_Id:
		return PinRef_Id_case
	case *pinRef_Value:
		return PinRef_Value_case
	default:
		return PinRef_Key_not_set_case
	}
}

type PinRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Id    []byte
	Value *PinRefByValue
	// -- end of xxx_hidden_Key
}

func (b0 PinRef_builder) Build() *PinRef {
	m0 := &PinRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Key = &pinRef_Id{b.Id}
	}
	if b.Value != nil {
		x.xxx_hidden_Key = &pinRef_Value{b.Value}
	}
	return m0
}

type case_PinRef_Key protoreflect.FieldNumber

func (x case_PinRef_Key) String() string {
	md := file_gantry_pin_svc_g_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isPinRef_Key interface {
	isPinRef_Key()
}

type pinRef_Id struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,oneof"`
}

type pinRef_Value struct {
	Value *PinRefByValue `protobuf:"bytes,2,opt,name=value,oneof"`
}

func (*pinRef_Id) isPinRef_Key() {}

func (*pinRef_Value) isPinRef_Key() {}

type PinRefByValue struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Store       *StoreRef              `protobuf:"bytes,2,opt,name=store"`
	xxx_hidden_Value       *string                `protobuf:"bytes,3,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PinRefByValue) Reset() {
	*x = PinRefByValue{}
	mi := &file_gantry_pin_svc_g_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinRefByValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinRefByValue) ProtoMessage() {}

func (x *PinRefByValue) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_pin_svc_g_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PinRefByValue) GetStore() *StoreRef {
	if x != nil {
		return x.xxx_hidden_Store
	}
	return nil
}

func (x *PinRefByValue) GetValue() string {
	if x != nil {
		if x.xxx_hidden_Value != nil {
			return *x.xxx_hidden_Value
		}
		return ""
	}
	return ""
}

func (x *PinRefByValue) SetStore(v *StoreRef) {
	x.xxx_hidden_Store = v
}

func (x *PinRefByValue) SetValue(v string) {
	x.xxx_hidden_Value = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *PinRefByValue) HasStore() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Store != nil
}

func (x *PinRefByValue) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PinRefByValue) ClearStore() {
	x.xxx_hidden_Store = nil
}

func (x *PinRefByValue) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Value = nil
}

type PinRefByValue_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Store *StoreRef
	Value *string
}

func (b0 PinRefByValue_builder) Build() *PinRefByValue {
	m0 := &PinRefByValue{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Store = b.Store
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Value = b.Value
	}
	return m0
}

type PinSelect struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All         bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_Store       *StoreSelect           `protobuf:"bytes,2,opt,name=store"`
	xxx_hidden_Value       bool                   `protobuf:"varint,3,opt,name=value"`
	xxx_hidden_Pattern     bool                   `protobuf:"varint,4,opt,name=pattern"`
	xxx_hidden_PinnedAt    bool                   `protobuf:"varint,5,opt,name=pinned_at,json=pinnedAt"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PinSelect) Reset() {
	*x = PinSelect{}
	mi := &file_gantry_pin_svc_g_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinSelect) ProtoMessage() {}

func (x *PinSelect) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_pin_svc_g_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PinSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *PinSelect) GetStore() *StoreSelect {
	if x != nil {
		return x.xxx_hidden_Store
	}
	return nil
}

func (x *PinSelect) GetValue() bool {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return false
}

func (x *PinSelect) GetPattern() bool {
	if x != nil {
		return x.xxx_hidden_Pattern
	}
	return false
}

func (x *PinSelect) GetPinnedAt() bool {
	if x != nil {
		return x.xxx_hidden_PinnedAt
	}
	return false
}

func (x *PinSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *PinSelect) SetStore(v *StoreSelect) {
	x.xxx_hidden_Store = v
}

func (x *PinSelect) SetValue(v bool) {
	x.xxx_hidden_Value = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *PinSelect) SetPattern(v bool) {
	x.xxx_hidden_Pattern = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *PinSelect) SetPinnedAt(v bool) {
	x.xxx_hidden_PinnedAt = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *PinSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PinSelect) HasStore() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Store != nil
}

func (x *PinSelect) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *PinSelect) HasPattern() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *PinSelect) HasPinnedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *PinSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *PinSelect) ClearStore() {
	x.xxx_hidden_Store = nil
}

func (x *PinSelect) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Value = false
}

func (x *PinSelect) ClearPattern() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Pattern = false
}

func (x *PinSelect) ClearPinnedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_PinnedAt = false
}

type PinSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All      *bool
	Store    *StoreSelect
	Value    *bool
	Pattern  *bool
	PinnedAt *bool
}

func (b0 PinSelect_builder) Build() *PinSelect {
	m0 := &PinSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_All = *b.All
	}
	x.xxx_hidden_Store = b.Store
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Value = *b.Value
	}
	if b.Pattern != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Pattern = *b.Pattern
	}
	if b.PinnedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_PinnedAt = *b.PinnedAt
	}
	return m0
}

type PinPatchRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref         *PinRef                `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Pattern     bool                   `protobuf:"varint,7,opt,name=pattern"`
	xxx_hidden_PinnedAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=pinned_at,json=pinnedAt"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PinPatchRequest) Reset() {
	*x = PinPatchRequest{}
	mi := &file_gantry_pin_svc_g_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinPatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinPatchRequest) ProtoMessage() {}

func (x *PinPatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_pin_svc_g_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PinPatchRequest) GetRef() *PinRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *PinPatchRequest) GetPattern() bool {
	if x != nil {
		return x.xxx_hidden_Pattern
	}
	return false
}

func (x *PinPatchRequest) GetPinnedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_PinnedAt
	}
	return nil
}

func (x *PinPatchRequest) SetRef(v *PinRef) {
	x.xxx_hidden_Ref = v
}

func (x *PinPatchRequest) SetPattern(v bool) {
	x.xxx_hidden_Pattern = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *PinPatchRequest) SetPinnedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_PinnedAt = v
}

func (x *PinPatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *PinPatchRequest) HasPattern() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PinPatchRequest) HasPinnedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PinnedAt != nil
}

func (x *PinPatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *PinPatchRequest) ClearPattern() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Pattern = false
}

func (x *PinPatchRequest) ClearPinnedAt() {
	x.xxx_hidden_PinnedAt = nil
}

type PinPatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref      *PinRef
	Pattern  *bool
	PinnedAt *timestamppb.Timestamp
}

func (b0 PinPatchRequest_builder) Build() *PinPatchRequest {
	m0 := &PinPatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	if b.Pattern != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Pattern = *b.Pattern
	}
	x.xxx_hidden_PinnedAt = b.PinnedAt
	return m0
}

type PinListRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Store       *StoreRef              `protobuf:"bytes,1,opt,name=store"`
	xxx_hidden_PageSize    int32                  `protobuf:"varint,10,opt,name=page_size,json=pageSize"`
	xxx_hidden_PageToken   *string                `protobuf:"bytes,11,opt,name=page_token,json=pageToken"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PinListRequest) Reset() {
	*x = PinListRequest{}
	mi := &file_gantry_pin_svc_g_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinListRequest) ProtoMessage() {}

func (x *PinListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_pin_svc_g_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PinListRequest) GetStore() *StoreRef {
	if x != nil {
		return x.xxx_hidden_Store
	}
	return nil
}

func (x *PinListRequest) GetPageSize() int32 {
	if x != nil {
		return x.xxx_hidden_PageSize
	}
	return 0
}

func (x *PinListRequest) GetPageToken() string {
	if x != nil {
		if x.xxx_hidden_PageToken != nil {
			return *x.xxx_hidden_PageToken
		}
		return ""
	}
	return ""
}

func (x *PinListRequest) SetStore(v *StoreRef) {
	x.xxx_hidden_Store = v
}

func (x *PinListRequest) SetPageSize(v int32) {
	x.xxx_hidden_PageSize = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *PinListRequest) SetPageToken(v string) {
	x.xxx_hidden_PageToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *PinListRequest) HasStore() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Store != nil
}

func (x *PinListRequest) HasPageSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PinListRequest) HasPageToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *PinListRequest) ClearStore() {
	x.xxx_hidden_Store = nil
}

func (x *PinListRequest) ClearPageSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PageSize = 0
}

func (x *PinListRequest) ClearPageToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_PageToken = nil
}

type PinListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Store     *StoreRef
	PageSize  *int32
	PageToken *string
}

func (b0 PinListRequest_builder) Build() *PinListRequest {
	m0 := &PinListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Store = b.Store
	if b.PageSize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_PageSize = *b.PageSize
	}
	if b.PageToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_PageToken = b.PageToken
	}
	return m0
}

type PinListResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items         *[]*Pin                `protobuf:"bytes,1,rep,name=items"`
	xxx_hidden_NextPageToken *string                `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *PinListResponse) Reset() {
	*x = PinListResponse{}
	mi := &file_gantry_pin_svc_g_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinListResponse) ProtoMessage() {}

func (x *PinListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_pin_svc_g_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PinListResponse) GetItems() []*Pin {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *PinListResponse) GetNextPageToken() string {
	if x != nil {
		if x.xxx_hidden_NextPageToken != nil {
			return *x.xxx_hidden_NextPageToken
		}
		return ""
	}
	return ""
}

func (x *PinListResponse) SetItems(v []*Pin) {
	x.xxx_hidden_Items = &v
}

func (x *PinListResponse) SetNextPageToken(v string) {
	x.xxx_hidden_NextPageToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *PinListResponse) HasNextPageToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PinListResponse) ClearNextPageToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NextPageToken = nil
}

type PinListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items         []*Pin
	NextPageToken *string
}

func (b0 PinListResponse_builder) Build() *PinListResponse {
	m0 := &PinListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	if b.NextPageToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_NextPageToken = b.NextPageToken
	}
	return m0
}

var File_gantry_pin_svc_g_proto protoreflect.FileDescriptor

const file_gantry_pin_svc_g_proto_rawDesc = "" +
	"\n" +
	"\x16gantry/pin_svc.g.proto\x12\x06gantry\x1a\x10gantry/pin.proto\x1a\x18gantry/store_svc.g.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x01\n" +
	"\rPinAddRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12&\n" +
	"\x05store\x18\x02 \x01(\v2\x10.gantry.StoreRefR\x05store\x12\x1b\n" +
	"\x05value\x18\x03 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05value\x12\x1f\n" +
	"\apattern\x18\x04 \x01(\bB\x05\xaa\x01\x02\b\x02R\apattern\x127\n" +
	"\tpinned_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bpinnedAt\"\\\n" +
	"\rPinGetRequest\x12 \n" +
	"\x03ref\x18\x01 \x01(\v2\x0e.gantry.PinRefR\x03ref\x12)\n" +
	"\x06select\x18\x02 \x01(\v2\x11.gantry.PinSelectR\x06select\"P\n" +
	"\x06PinRef\x12\x10\n" +
	"\x02id\x18\x01 \x01(\fH\x00R\x02id\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x15.gantry.PinRefByValueH\x00R\x05valueB\x05\n" +
	"\x03key\"M\n" +
	"\rPinRefByValue\x12&\n" +
	"\x05store\x18\x02 \x01(\v2\x10.gantry.StoreRefR\x05store\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\x95\x01\n" +
	"\tPinSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12)\n" +
	"\x05store\x18\x02 \x01(\v2\x13.gantry.StoreSelectR\x05store\x12\x14\n" +
	"\x05value\x18\x03 \x01(\bR\x05value\x12\x18\n" +
	"\apattern\x18\x04 \x01(\bR\apattern\x12\x1b\n" +
	"\tpinned_at\x18\x05 \x01(\bR\bpinnedAt\"\x86\x01\n" +
	"\x0fPinPatchRequest\x12 \n" +
	"\x03ref\x18\x01 \x01(\v2\x0e.gantry.PinRefR\x03ref\x12\x18\n" +
	"\apattern\x18\a \x01(\bR\apattern\x127\n" +
	"\tpinned_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bpinnedAt\"t\n" +
	"\x0ePinListRequest\x12&\n" +
	"\x05store\x18\x01 \x01(\v2\x10.gantry.StoreRefR\x05store\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\v \x01(\tR\tpageToken\"\\\n" +
	"\x0fPinListResponse\x12!\n" +
	"\x05items\x18\x01 \x03(\v2\v.gantry.PinR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xfb\x01\n" +
	"\n" +
	"PinService\x12)\n" +
	"\x03Add\x12\x15.gantry.PinAddRequest\x1a\v.gantry.Pin\x12)\n" +
	"\x03Get\x12\x15.gantry.PinGetRequest\x1a\v.gantry.Pin\x12-\n" +
	"\x05Patch\x12\x17.gantry.PinPatchRequest\x1a\v.gantry.Pin\x12/\n" +
	"\x05Erase\x12\x0e.gantry.PinRef\x1a\x16.google.protobuf.Empty\x127\n" +
	"\x04List\x12\x16.gantry.PinListRequest\x1a\x17.gantry.PinListResponseB\x1fZ\x1dgithub.com/lesomnus/gantry/pbb\beditionsp\xe8\a"

var file_gantry_pin_svc_g_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gantry_pin_svc_g_proto_goTypes = []any{
	(*PinAddRequest)(nil),         // 0: gantry.PinAddRequest
	(*PinGetRequest)(nil),         // 1: gantry.PinGetRequest
	(*PinRef)(nil),                // 2: gantry.PinRef
	(*PinRefByValue)(nil),         // 3: gantry.PinRefByValue
	(*PinSelect)(nil),             // 4: gantry.PinSelect
	(*PinPatchRequest)(nil),       // 5: gantry.PinPatchRequest
	(*PinListRequest)(nil),        // 6: gantry.PinListRequest
	(*PinListResponse)(nil),       // 7: gantry.PinListResponse
	(*StoreRef)(nil),              // 8: gantry.StoreRef
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*StoreSelect)(nil),           // 10: gantry.StoreSelect
	(*Pin)(nil),                   // 11: gantry.Pin
	(*emptypb.Empty)(nil),         // 12: google.protobuf.Empty
}
var file_gantry_pin_svc_g_proto_depIdxs = []int32{
	8,  // 0: gantry.PinAddRequest.store:type_name -> gantry.StoreRef
	9,  // 1: gantry.PinAddRequest.pinned_at:type_name -> google.protobuf.Timestamp
	2,  // 2: gantry.PinGetRequest.ref:type_name -> gantry.PinRef
	4,  // 3: gantry.PinGetRequest.select:type_name -> gantry.PinSelect
	3,  // 4: gantry.PinRef.value:type_name -> gantry.PinRefByValue
	8,  // 5: gantry.PinRefByValue.store:type_name -> gantry.StoreRef
	10, // 6: gantry.PinSelect.store:type_name -> gantry.StoreSelect
	2,  // 7: gantry.PinPatchRequest.ref:type_name -> gantry.PinRef
	9,  // 8: gantry.PinPatchRequest.pinned_at:type_name -> google.protobuf.Timestamp
	8,  // 9: gantry.PinListRequest.store:type_name -> gantry.StoreRef
	11, // 10: gantry.PinListResponse.items:type_name -> gantry.Pin
	0,  // 11: gantry.PinService.Add:input_type -> gantry.PinAddRequest
	1,  // 12: gantry.PinService.Get:input_type -> gantry.PinGetRequest
	5,  // 13: gantry.PinService.Patch:input_type -> gantry.PinPatchRequest
	2,  // 14: gantry.PinService.Erase:input_type -> gantry.PinRef
	6,  // 15: gantry.PinService.List:input_type -> gantry.PinListRequest
	11, // 16: gantry.PinService.Add:output_type -> gantry.Pin
	11, // 17: gantry.PinService.Get:output_type -> gantry.Pin
	11, // 18: gantry.PinService.Patch:output_type -> gantry.Pin
	12, // 19: gantry.PinService.Erase:output_type -> google.protobuf.Empty
	7,  // 20: gantry.PinService.List:output_type -> gantry.PinListResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_gantry_pin_svc_g_proto_init() }
func file_gantry_pin_svc_g_proto_init() {
	if File_gantry_pin_svc_g_proto != nil {
		return
	}
	file_gantry_pin_proto_init()
	file_gantry_store_svc_g_proto_init()
	file_gantry_pin_svc_g_proto_msgTypes[2].OneofWrappers = []any{
		(*pinRef_Id)(nil),
		(*pinRef_Value)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gantry_pin_svc_g_proto_rawDesc), len(file_gantry_pin_svc_g_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gantry_pin_svc_g_proto_goTypes,
		DependencyIndexes: file_gantry_pin_svc_g_proto_depIdxs,
		MessageInfos:      file_gantry_pin_svc_g_proto_msgTypes,
	}.Build()
	File_gantry_pin_svc_g_proto = out.File
	file_gantry_pin_svc_g_proto_goTypes = nil
	file_gantry_pin_svc_g_proto_depIdxs = nil
}
