// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: gantry/store_svc.g.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreAddRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name         string                 `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Kind         StoreKind              `protobuf:"varint,2,opt,name=kind,enum=gantry.StoreKind"`
	xxx_hidden_Host         string                 `protobuf:"bytes,3,opt,name=host"`
	xxx_hidden_Mode         StoreMode              `protobuf:"varint,4,opt,name=mode,enum=gantry.StoreMode"`
	xxx_hidden_Address      string                 `protobuf:"bytes,5,opt,name=address"`
	xxx_hidden_Namespace    string                 `protobuf:"bytes,6,opt,name=namespace"`
	xxx_hidden_Ready        bool                   `protobuf:"varint,7,opt,name=ready"`
	xxx_hidden_Error        string                 `protobuf:"bytes,8,opt,name=error"`
	xxx_hidden_Capabilities *StoreCapabilities     `protobuf:"bytes,9,opt,name=capabilities"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *StoreAddRequest) Reset() {
	*x = StoreAddRequest{}
	mi := &file_gantry_store_svc_g_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreAddRequest) ProtoMessage() {}

func (x *StoreAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_store_svc_g_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StoreAddRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *StoreAddRequest) GetKind() StoreKind {
	if x != nil {
		return x.xxx_hidden_Kind
	}
	return StoreKind_STORE_KIND_UNSPECIFIED
}

func (x *StoreAddRequest) GetHost() string {
	if x != nil {
		return x.xxx_hidden_Host
	}
	return ""
}

func (x *StoreAddRequest) GetMode() StoreMode {
	if x != nil {
		return x.xxx_hidden_Mode
	}
	return StoreMode_STORE_MODE_UNSPECIFIED
}

func (x *StoreAddRequest) GetAddress() string {
	if x != nil {
		return x.xxx_hidden_Address
	}
	return ""
}

func (x *StoreAddRequest) GetNamespace() string {
	if x != nil {
		return x.xxx_hidden_Namespace
	}
	return ""
}

func (x *StoreAddRequest) GetReady() bool {
	if x != nil {
		return x.xxx_hidden_Ready
	}
	return false
}

func (x *StoreAddRequest) GetError() string {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return ""
}

func (x *StoreAddRequest) GetCapabilities() *StoreCapabilities {
	if x != nil {
		return x.xxx_hidden_Capabilities
	}
	return nil
}

func (x *StoreAddRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *StoreAddRequest) SetKind(v StoreKind) {
	x.xxx_hidden_Kind = v
}

func (x *StoreAddRequest) SetHost(v string) {
	x.xxx_hidden_Host = v
}

func (x *StoreAddRequest) SetMode(v StoreMode) {
	x.xxx_hidden_Mode = v
}

func (x *StoreAddRequest) SetAddress(v string) {
	x.xxx_hidden_Address = v
}

func (x *StoreAddRequest) SetNamespace(v string) {
	x.xxx_hidden_Namespace = v
}

func (x *StoreAddRequest) SetReady(v bool) {
	x.xxx_hidden_Ready = v
}

func (x *StoreAddRequest) SetError(v string) {
	x.xxx_hidden_Error = v
}

func (x *StoreAddRequest) SetCapabilities(v *StoreCapabilities) {
	x.xxx_hidden_Capabilities = v
}

func (x *StoreAddRequest) HasCapabilities() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Capabilities != nil
}

func (x *StoreAddRequest) ClearCapabilities() {
	x.xxx_hidden_Capabilities = nil
}

type StoreAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name         string
	Kind         StoreKind
	Host         string
	Mode         StoreMode
	Address      string
	Namespace    string
	Ready        bool
	Error        string
	Capabilities *StoreCapabilities
}

func (b0 StoreAddRequest_builder) Build() *StoreAddRequest {
	m0 := &StoreAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Kind = b.Kind
	x.xxx_hidden_Host = b.Host
	x.xxx_hidden_Mode = b.Mode
	x.xxx_hidden_Address = b.Address
	x.xxx_hidden_Namespace = b.Namespace
	x.xxx_hidden_Ready = b.Ready
	x.xxx_hidden_Error = b.Error
	x.xxx_hidden_Capabilities = b.Capabilities
	return m0
}

type StoreGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *StoreRef              `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *StoreSelect           `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StoreGetRequest) Reset() {
	*x = StoreGetRequest{}
	mi := &file_gantry_store_svc_g_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreGetRequest) ProtoMessage() {}

func (x *StoreGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_store_svc_g_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StoreGetRequest) GetRef() *StoreRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *StoreGetRequest) GetSelect() *StoreSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *StoreGetRequest) SetRef(v *StoreRef) {
	x.xxx_hidden_Ref = v
}

func (x *StoreGetRequest) SetSelect(v *StoreSelect) {
	x.xxx_hidden_Select = v
}

func (x *StoreGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *StoreGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *StoreGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *StoreGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type StoreGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *StoreRef
	Select *StoreSelect
}

func (b0 StoreGetRequest_builder) Build() *StoreGetRequest {
	m0 := &StoreGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type StoreRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isStoreRef_Key         `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StoreRef) Reset() {
	*x = StoreRef{}
	mi := &file_gantry_store_svc_g_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRef) ProtoMessage() {}

func (x *StoreRef) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_store_svc_g_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StoreRef) GetName() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*storeRef_Name); ok {
			return x.Name
		}
	}
	return ""
}

func (x *StoreRef) SetName(v string) {
	x.xxx_hidden_Key = &storeRef_Name{v}
}

func (x *StoreRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *StoreRef) HasName() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*storeRef_Name)
	return ok
}

func (x *StoreRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *StoreRef) ClearName() {
	if _, ok := x.xxx_hidden_Key.(*storeRef_Name); ok {
		x.xxx_hidden_Key = nil
	}
}

const StoreRef_Key_not_set_case case_StoreRef_Key = 0
const StoreRef_Name_case case_StoreRef_Key = 1

func (x *StoreRef) WhichKey() case_StoreRef_Key {
	if x == nil {
		return StoreRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *storeRef_Name:
		return StoreRef_Name_case
	default:
		return StoreRef_Key_not_set_case
	}
}

type StoreRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Name *string
	// -- end of xxx_hidden_Key
}

func (b0 StoreRef_builder) Build() *StoreRef {
	m0 := &StoreRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		x.xxx_hidden_Key = &storeRef_Name{*b.Name}
	}
	return m0
}

type case_StoreRef_Key protoreflect.FieldNumber

func (x case_StoreRef_Key) String() string {
	md := file_gantry_store_svc_g_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isStoreRef_Key interface {
	isStoreRef_Key()
}

type storeRef_Name struct {
	Name string `protobuf:"bytes,1,opt,name=name,oneof"`
}

func (*storeRef_Name) isStoreRef_Key() {}

type StoreSelect struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All          bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_Kind         bool                   `protobuf:"varint,2,opt,name=kind"`
	xxx_hidden_Host         bool                   `protobuf:"varint,3,opt,name=host"`
	xxx_hidden_Mode         bool                   `protobuf:"varint,4,opt,name=mode"`
	xxx_hidden_Address      bool                   `protobuf:"varint,5,opt,name=address"`
	xxx_hidden_Namespace    bool                   `protobuf:"varint,6,opt,name=namespace"`
	xxx_hidden_Ready        bool                   `protobuf:"varint,7,opt,name=ready"`
	xxx_hidden_Error        bool                   `protobuf:"varint,8,opt,name=error"`
	xxx_hidden_Capabilities bool                   `protobuf:"varint,9,opt,name=capabilities"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *StoreSelect) Reset() {
	*x = StoreSelect{}
	mi := &file_gantry_store_svc_g_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreSelect) ProtoMessage() {}

func (x *StoreSelect) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_store_svc_g_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StoreSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *StoreSelect) GetKind() bool {
	if x != nil {
		return x.xxx_hidden_Kind
	}
	return false
}

func (x *StoreSelect) GetHost() bool {
	if x != nil {
		return x.xxx_hidden_Host
	}
	return false
}

func (x *StoreSelect) GetMode() bool {
	if x != nil {
		return x.xxx_hidden_Mode
	}
	return false
}

func (x *StoreSelect) GetAddress() bool {
	if x != nil {
		return x.xxx_hidden_Address
	}
	return false
}

func (x *StoreSelect) GetNamespace() bool {
	if x != nil {
		return x.xxx_hidden_Namespace
	}
	return false
}

func (x *StoreSelect) GetReady() bool {
	if x != nil {
		return x.xxx_hidden_Ready
	}
	return false
}

func (x *StoreSelect) GetError() bool {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return false
}

func (x *StoreSelect) GetCapabilities() bool {
	if x != nil {
		return x.xxx_hidden_Capabilities
	}
	return false
}

func (x *StoreSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 9)
}

func (x *StoreSelect) SetKind(v bool) {
	x.xxx_hidden_Kind = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *StoreSelect) SetHost(v bool) {
	x.xxx_hidden_Host = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *StoreSelect) SetMode(v bool) {
	x.xxx_hidden_Mode = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 9)
}

func (x *StoreSelect) SetAddress(v bool) {
	x.xxx_hidden_Address = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *StoreSelect) SetNamespace(v bool) {
	x.xxx_hidden_Namespace = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *StoreSelect) SetReady(v bool) {
	x.xxx_hidden_Ready = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *StoreSelect) SetError(v bool) {
	x.xxx_hidden_Error = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 9)
}

func (x *StoreSelect) SetCapabilities(v bool) {
	x.xxx_hidden_Capabilities = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 9)
}

func (x *StoreSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StoreSelect) HasKind() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StoreSelect) HasHost() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *StoreSelect) HasMode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *StoreSelect) HasAddress() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *StoreSelect) HasNamespace() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *StoreSelect) HasReady() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *StoreSelect) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *StoreSelect) HasCapabilities() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *StoreSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *StoreSelect) ClearKind() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Kind = false
}

func (x *StoreSelect) ClearHost() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Host = false
}

func (x *StoreSelect) ClearMode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Mode = false
}

func (x *StoreSelect) ClearAddress() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Address = false
}

func (x *StoreSelect) ClearNamespace() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Namespace = false
}

func (x *StoreSelect) ClearReady() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Ready = false
}

func (x *StoreSelect) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Error = false
}

func (x *StoreSelect) ClearCapabilities() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Capabilities = false
}

type StoreSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All          *bool
	Kind         *bool
	Host         *bool
	Mode         *bool
	Address      *bool
	Namespace    *bool
	Ready        *bool
	Error        *bool
	Capabilities *bool
}

func (b0 StoreSelect_builder) Build() *StoreSelect {
	m0 := &StoreSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 9)
		x.xxx_hidden_All = *b.All
	}
	if b.Kind != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_Kind = *b.Kind
	}
	if b.Host != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_Host = *b.Host
	}
	if b.Mode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 9)
		x.xxx_hidden_Mode = *b.Mode
	}
	if b.Address != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_Address = *b.Address
	}
	if b.Namespace != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_Namespace = *b.Namespace
	}
	if b.Ready != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_Ready = *b.Ready
	}
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 9)
		x.xxx_hidden_Error = *b.Error
	}
	if b.Capabilities != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 9)
		x.xxx_hidden_Capabilities = *b.Capabilities
	}
	return m0
}

type StorePatchRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref              *StoreRef              `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Host             *string                `protobuf:"bytes,5,opt,name=host"`
	xxx_hidden_Mode             StoreMode              `protobuf:"varint,7,opt,name=mode,enum=gantry.StoreMode"`
	xxx_hidden_Address          *string                `protobuf:"bytes,9,opt,name=address"`
	xxx_hidden_Namespace        *string                `protobuf:"bytes,11,opt,name=namespace"`
	xxx_hidden_Ready            bool                   `protobuf:"varint,13,opt,name=ready"`
	xxx_hidden_Error            *string                `protobuf:"bytes,15,opt,name=error"`
	xxx_hidden_Capabilities     *StoreCapabilities     `protobuf:"bytes,17,opt,name=capabilities"`
	xxx_hidden_CapabilitiesNull bool                   `protobuf:"varint,18,opt,name=capabilities_null,json=capabilitiesNull"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *StorePatchRequest) Reset() {
	*x = StorePatchRequest{}
	mi := &file_gantry_store_svc_g_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorePatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorePatchRequest) ProtoMessage() {}

func (x *StorePatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_store_svc_g_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StorePatchRequest) GetRef() *StoreRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *StorePatchRequest) GetHost() string {
	if x != nil {
		if x.xxx_hidden_Host != nil {
			return *x.xxx_hidden_Host
		}
		return ""
	}
	return ""
}

func (x *StorePatchRequest) GetMode() StoreMode {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Mode
		}
	}
	return StoreMode_STORE_MODE_UNSPECIFIED
}

func (x *StorePatchRequest) GetAddress() string {
	if x != nil {
		if x.xxx_hidden_Address != nil {
			return *x.xxx_hidden_Address
		}
		return ""
	}
	return ""
}

func (x *StorePatchRequest) GetNamespace() string {
	if x != nil {
		if x.xxx_hidden_Namespace != nil {
			return *x.xxx_hidden_Namespace
		}
		return ""
	}
	return ""
}

func (x *StorePatchRequest) GetReady() bool {
	if x != nil {
		return x.xxx_hidden_Ready
	}
	return false
}

func (x *StorePatchRequest) GetError() string {
	if x != nil {
		if x.xxx_hidden_Error != nil {
			return *x.xxx_hidden_Error
		}
		return ""
	}
	return ""
}

func (x *StorePatchRequest) GetCapabilities() *StoreCapabilities {
	if x != nil {
		return x.xxx_hidden_Capabilities
	}
	return nil
}

func (x *StorePatchRequest) GetCapabilitiesNull() bool {
	if x != nil {
		return x.xxx_hidden_CapabilitiesNull
	}
	return false
}

func (x *StorePatchRequest) SetRef(v *StoreRef) {
	x.xxx_hidden_Ref = v
}

func (x *StorePatchRequest) SetHost(v string) {
	x.xxx_hidden_Host = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *StorePatchRequest) SetMode(v StoreMode) {
	x.xxx_hidden_Mode = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *StorePatchRequest) SetAddress(v string) {
	x.xxx_hidden_Address = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 9)
}

func (x *StorePatchRequest) SetNamespace(v string) {
	x.xxx_hidden_Namespace = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *StorePatchRequest) SetReady(v bool) {
	x.xxx_hidden_Ready = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *StorePatchRequest) SetError(v string) {
	x.xxx_hidden_Error = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *StorePatchRequest) SetCapabilities(v *StoreCapabilities) {
	x.xxx_hidden_Capabilities = v
}

func (x *StorePatchRequest) SetCapabilitiesNull(v bool) {
	x.xxx_hidden_CapabilitiesNull = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 9)
}

func (x *StorePatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *StorePatchRequest) HasHost() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StorePatchRequest) HasMode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *StorePatchRequest) HasAddress() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *StorePatchRequest) HasNamespace() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *StorePatchRequest) HasReady() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *StorePatchRequest) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *StorePatchRequest) HasCapabilities() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Capabilities != nil
}

func (x *StorePatchRequest) HasCapabilitiesNull() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *StorePatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *StorePatchRequest) ClearHost() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Host = nil
}

func (x *StorePatchRequest) ClearMode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Mode = StoreMode_STORE_MODE_UNSPECIFIED
}

func (x *StorePatchRequest) ClearAddress() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Address = nil
}

func (x *StorePatchRequest) ClearNamespace() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Namespace = nil
}

func (x *StorePatchRequest) ClearReady() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Ready = false
}

func (x *StorePatchRequest) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Error = nil
}

func (x *StorePatchRequest) ClearCapabilities() {
	x.xxx_hidden_Capabilities = nil
}

func (x *StorePatchRequest) ClearCapabilitiesNull() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_CapabilitiesNull = false
}

type StorePatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref              *StoreRef
	Host             *string
	Mode             *StoreMode
	Address          *string
	Namespace        *string
	Ready            *bool
	Error            *string
	Capabilities     *StoreCapabilities
	CapabilitiesNull *bool
}

func (b0 StorePatchRequest_builder) Build() *StorePatchRequest {
	m0 := &StorePatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	if b.Host != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_Host = b.Host
	}
	if b.Mode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_Mode = *b.Mode
	}
	if b.Address != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 9)
		x.xxx_hidden_Address = b.Address
	}
	if b.Namespace != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_Namespace = b.Namespace
	}
	if b.Ready != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_Ready = *b.Ready
	}
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_Error = b.Error
	}
	x.xxx_hidden_Capabilities = b.Capabilities
	if b.CapabilitiesNull != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 9)
		x.xxx_hidden_CapabilitiesNull = *b.CapabilitiesNull
	}
	return m0
}

type StoreListRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Kind        StoreKind              `protobuf:"varint,1,opt,name=kind,enum=gantry.StoreKind"`
	xxx_hidden_PageSize    int32                  `protobuf:"varint,10,opt,name=page_size,json=pageSize"`
	xxx_hidden_PageToken   *string                `protobuf:"bytes,11,opt,name=page_token,json=pageToken"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StoreListRequest) Reset() {
	*x = StoreListRequest{}
	mi := &file_gantry_store_svc_g_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreListRequest) ProtoMessage() {}

func (x *StoreListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_store_svc_g_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StoreListRequest) GetKind() StoreKind {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Kind
		}
	}
	return StoreKind_STORE_KIND_UNSPECIFIED
}

func (x *StoreListRequest) GetPageSize() int32 {
	if x != nil {
		return x.xxx_hidden_PageSize
	}
	return 0
}

func (x *StoreListRequest) GetPageToken() string {
	if x != nil {
		if x.xxx_hidden_PageToken != nil {
			return *x.xxx_hidden_PageToken
		}
		return ""
	}
	return ""
}

func (x *StoreListRequest) SetKind(v StoreKind) {
	x.xxx_hidden_Kind = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *StoreListRequest) SetPageSize(v int32) {
	x.xxx_hidden_PageSize = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *StoreListRequest) SetPageToken(v string) {
	x.xxx_hidden_PageToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *StoreListRequest) HasKind() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StoreListRequest) HasPageSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StoreListRequest) HasPageToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *StoreListRequest) ClearKind() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Kind = StoreKind_STORE_KIND_UNSPECIFIED
}

func (x *StoreListRequest) ClearPageSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PageSize = 0
}

func (x *StoreListRequest) ClearPageToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_PageToken = nil
}

type StoreListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Keep only stores of this kind.
	Kind *StoreKind
	// Maximum items to return; 0 = no limit.
	PageSize *int32
	// Continuation token from the previous response; empty starts from the
	// beginning.
	PageToken *string
}

func (b0 StoreListRequest_builder) Build() *StoreListRequest {
	m0 := &StoreListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Kind != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Kind = *b.Kind
	}
	if b.PageSize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_PageSize = *b.PageSize
	}
	if b.PageToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_PageToken = b.PageToken
	}
	return m0
}

type StoreListResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items         *[]*Store              `protobuf:"bytes,1,rep,name=items"`
	xxx_hidden_NextPageToken *string                `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *StoreListResponse) Reset() {
	*x = StoreListResponse{}
	mi := &file_gantry_store_svc_g_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreListResponse) ProtoMessage() {}

func (x *StoreListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_store_svc_g_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StoreListResponse) GetItems() []*Store {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *StoreListResponse) GetNextPageToken() string {
	if x != nil {
		if x.xxx_hidden_NextPageToken != nil {
			return *x.xxx_hidden_NextPageToken
		}
		return ""
	}
	return ""
}

func (x *StoreListResponse) SetItems(v []*Store) {
	x.xxx_hidden_Items = &v
}

func (x *StoreListResponse) SetNextPageToken(v string) {
	x.xxx_hidden_NextPageToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *StoreListResponse) HasNextPageToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StoreListResponse) ClearNextPageToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NextPageToken = nil
}

type StoreListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// One page of results, sorted by name.
	Items []*Store
	// Empty when there are no further results.
	NextPageToken *string
}

func (b0 StoreListResponse_builder) Build() *StoreListResponse {
	m0 := &StoreListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	if b.NextPageToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_NextPageToken = b.NextPageToken
	}
	return m0
}

type StorePullRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Store       *StoreRef              `protobuf:"bytes,1,opt,name=store"`
	xxx_hidden_Ref         *string                `protobuf:"bytes,2,opt,name=ref"`
	xxx_hidden_Platform    *string                `protobuf:"bytes,3,opt,name=platform"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StorePullRequest) Reset() {
	*x = StorePullRequest{}
	mi := &file_gantry_store_svc_g_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorePullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorePullRequest) ProtoMessage() {}

func (x *StorePullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_store_svc_g_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StorePullRequest) GetStore() *StoreRef {
	if x != nil {
		return x.xxx_hidden_Store
	}
	return nil
}

func (x *StorePullRequest) GetRef() string {
	if x != nil {
		if x.xxx_hidden_Ref != nil {
			return *x.xxx_hidden_Ref
		}
		return ""
	}
	return ""
}

func (x *StorePullRequest) GetPlatform() string {
	if x != nil {
		if x.xxx_hidden_Platform != nil {
			return *x.xxx_hidden_Platform
		}
		return ""
	}
	return ""
}

func (x *StorePullRequest) SetStore(v *StoreRef) {
	x.xxx_hidden_Store = v
}

func (x *StorePullRequest) SetRef(v string) {
	x.xxx_hidden_Ref = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *StorePullRequest) SetPlatform(v string) {
	x.xxx_hidden_Platform = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *StorePullRequest) HasStore() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Store != nil
}

func (x *StorePullRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StorePullRequest) HasPlatform() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *StorePullRequest) ClearStore() {
	x.xxx_hidden_Store = nil
}

func (x *StorePullRequest) ClearRef() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Ref = nil
}

func (x *StorePullRequest) ClearPlatform() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Platform = nil
}

type StorePullRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Engine store that pulls.
	Store *StoreRef
	// Image reference to pull.
	Ref *string
	// Platform to pull ("os/arch"); empty uses the daemon's default.
	Platform *string
}

func (b0 StorePullRequest_builder) Build() *StorePullRequest {
	m0 := &StorePullRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Store = b.Store
	if b.Ref != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Ref = b.Ref
	}
	if b.Platform != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Platform = b.Platform
	}
	return m0
}

type StorePullResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref         *string                `protobuf:"bytes,1,opt,name=ref"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StorePullResponse) Reset() {
	*x = StorePullResponse{}
	mi := &file_gantry_store_svc_g_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorePullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorePullResponse) ProtoMessage() {}

func (x *StorePullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_store_svc_g_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StorePullResponse) GetRef() string {
	if x != nil {
		if x.xxx_hidden_Ref != nil {
			return *x.xxx_hidden_Ref
		}
		return ""
	}
	return ""
}

func (x *StorePullResponse) SetRef(v string) {
	x.xxx_hidden_Ref = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *StorePullResponse) HasRef() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StorePullResponse) ClearRef() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Ref = nil
}

type StorePullResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The reference the engine pulled.
	Ref *string
}

func (b0 StorePullResponse_builder) Build() *StorePullResponse {
	m0 := &StorePullResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Ref != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Ref = b.Ref
	}
	return m0
}

type StoreRemoveRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Store       *StoreRef              `protobuf:"bytes,1,opt,name=store"`
	xxx_hidden_Ref         *string                `protobuf:"bytes,2,opt,name=ref"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StoreRemoveRequest) Reset() {
	*x = StoreRemoveRequest{}
	mi := &file_gantry_store_svc_g_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRemoveRequest) ProtoMessage() {}

func (x *StoreRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_store_svc_g_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StoreRemoveRequest) GetStore() *StoreRef {
	if x != nil {
		return x.xxx_hidden_Store
	}
	return nil
}

func (x *StoreRemoveRequest) GetRef() string {
	if x != nil {
		if x.xxx_hidden_Ref != nil {
			return *x.xxx_hidden_Ref
		}
		return ""
	}
	return ""
}

func (x *StoreRemoveRequest) SetStore(v *StoreRef) {
	x.xxx_hidden_Store = v
}

func (x *StoreRemoveRequest) SetRef(v string) {
	x.xxx_hidden_Ref = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *StoreRemoveRequest) HasStore() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Store != nil
}

func (x *StoreRemoveRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StoreRemoveRequest) ClearStore() {
	x.xxx_hidden_Store = nil
}

func (x *StoreRemoveRequest) ClearRef() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Ref = nil
}

type StoreRemoveRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Engine store to remove from.
	Store *StoreRef
	// Image reference to remove.
	Ref *string
}

func (b0 StoreRemoveRequest_builder) Build() *StoreRemoveRequest {
	m0 := &StoreRemoveRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Store = b.Store
	if b.Ref != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Ref = b.Ref
	}
	return m0
}

type StoreRemoveResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Untagged []string               `protobuf:"bytes,1,rep,name=untagged"`
	xxx_hidden_Deleted  []string               `protobuf:"bytes,2,rep,name=deleted"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StoreRemoveResponse) Reset() {
	*x = StoreRemoveResponse{}
	mi := &file_gantry_store_svc_g_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRemoveResponse) ProtoMessage() {}

func (x *StoreRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_store_svc_g_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StoreRemoveResponse) GetUntagged() []string {
	if x != nil {
		return x.xxx_hidden_Untagged
	}
	return nil
}

func (x *StoreRemoveResponse) GetDeleted() []string {
	if x != nil {
		return x.xxx_hidden_Deleted
	}
	return nil
}

func (x *StoreRemoveResponse) SetUntagged(v []string) {
	x.xxx_hidden_Untagged = v
}

func (x *StoreRemoveResponse) SetDeleted(v []string) {
	x.xxx_hidden_Deleted = v
}

type StoreRemoveResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Tag refs removed; disk is freed only when the last tag and its content
	// are gone.
	Untagged []string
	// Content IDs whose bytes were actually deleted.
	Deleted []string
}

func (b0 StoreRemoveResponse_builder) Build() *StoreRemoveResponse {
	m0 := &StoreRemoveResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Untagged = b.Untagged
	x.xxx_hidden_Deleted = b.Deleted
	return m0
}

type StoreHealthResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Healthy     bool                   `protobuf:"varint,1,opt,name=healthy"`
	xxx_hidden_Kind        StoreKind              `protobuf:"varint,2,opt,name=kind,enum=gantry.StoreKind"`
	xxx_hidden_LatencyMs   int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs"`
	xxx_hidden_Error       *string                `protobuf:"bytes,4,opt,name=error"`
	xxx_hidden_DateChecked *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date_checked,json=dateChecked"`
	xxx_hidden_Cached      bool                   `protobuf:"varint,6,opt,name=cached"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StoreHealthResponse) Reset() {
	*x = StoreHealthResponse{}
	mi := &file_gantry_store_svc_g_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreHealthResponse) ProtoMessage() {}

func (x *StoreHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_store_svc_g_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StoreHealthResponse) GetHealthy() bool {
	if x != nil {
		return x.xxx_hidden_Healthy
	}
	return false
}

func (x *StoreHealthResponse) GetKind() StoreKind {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Kind
		}
	}
	return StoreKind_STORE_KIND_UNSPECIFIED
}

func (x *StoreHealthResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.xxx_hidden_LatencyMs
	}
	return 0
}

func (x *StoreHealthResponse) GetError() string {
	if x != nil {
		if x.xxx_hidden_Error != nil {
			return *x.xxx_hidden_Error
		}
		return ""
	}
	return ""
}

func (x *StoreHealthResponse) GetDateChecked() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateChecked
	}
	return nil
}

func (x *StoreHealthResponse) GetCached() bool {
	if x != nil {
		return x.xxx_hidden_Cached
	}
	return false
}

func (x *StoreHealthResponse) SetHealthy(v bool) {
	x.xxx_hidden_Healthy = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *StoreHealthResponse) SetKind(v StoreKind) {
	x.xxx_hidden_Kind = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *StoreHealthResponse) SetLatencyMs(v int64) {
	x.xxx_hidden_LatencyMs = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *StoreHealthResponse) SetError(v string) {
	x.xxx_hidden_Error = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *StoreHealthResponse) SetDateChecked(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateChecked = v
}

func (x *StoreHealthResponse) SetCached(v bool) {
	x.xxx_hidden_Cached = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *StoreHealthResponse) HasHealthy() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StoreHealthResponse) HasKind() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StoreHealthResponse) HasLatencyMs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *StoreHealthResponse) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *StoreHealthResponse) HasDateChecked() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateChecked != nil
}

func (x *StoreHealthResponse) HasCached() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *StoreHealthResponse) ClearHealthy() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Healthy = false
}

func (x *StoreHealthResponse) ClearKind() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Kind = StoreKind_STORE_KIND_UNSPECIFIED
}

func (x *StoreHealthResponse) ClearLatencyMs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_LatencyMs = 0
}

func (x *StoreHealthResponse) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Error = nil
}

func (x *StoreHealthResponse) ClearDateChecked() {
	x.xxx_hidden_DateChecked = nil
}

func (x *StoreHealthResponse) ClearCached() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Cached = false
}

type StoreHealthResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The probe succeeded.
	Healthy *bool
	// Kind of the probed store.
	Kind *StoreKind
	// Probe round-trip in milliseconds.
	LatencyMs *int64
	// Probe failure text.
	Error       *string
	DateChecked *timestamppb.Timestamp
	// True when served from the TTL cache rather than probed for this call.
	Cached *bool
}

func (b0 StoreHealthResponse_builder) Build() *StoreHealthResponse {
	m0 := &StoreHealthResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Healthy != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Healthy = *b.Healthy
	}
	if b.Kind != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Kind = *b.Kind
	}
	if b.LatencyMs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_LatencyMs = *b.LatencyMs
	}
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Error = b.Error
	}
	x.xxx_hidden_DateChecked = b.DateChecked
	if b.Cached != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_Cached = *b.Cached
	}
	return m0
}

type StoreGcStatusResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Enabled       bool                   `protobuf:"varint,1,opt,name=enabled"`
	xxx_hidden_Running       bool                   `protobuf:"varint,2,opt,name=running"`
	xxx_hidden_Started       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started"`
	xxx_hidden_LastRun       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_run,json=lastRun"`
	xxx_hidden_NextWake      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=next_wake,json=nextWake"`
	xxx_hidden_GraceUntil    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=grace_until,json=graceUntil"`
	xxx_hidden_Schedule      *GcSchedule            `protobuf:"bytes,7,opt,name=schedule"`
	xxx_hidden_Rules         *[]*GcRule             `protobuf:"bytes,8,rep,name=rules"`
	xxx_hidden_Records       int32                  `protobuf:"varint,9,opt,name=records"`
	xxx_hidden_Pins          int32                  `protobuf:"varint,10,opt,name=pins"`
	xxx_hidden_Untagged      int32                  `protobuf:"varint,11,opt,name=untagged"`
	xxx_hidden_UntaggedAfter *durationpb.Duration   `protobuf:"bytes,12,opt,name=untagged_after,json=untaggedAfter"`
	xxx_hidden_Watcher       *GcWatcherStatus       `protobuf:"bytes,13,opt,name=watcher"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *StoreGcStatusResponse) Reset() {
	*x = StoreGcStatusResponse{}
	mi := &file_gantry_store_svc_g_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreGcStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreGcStatusResponse) ProtoMessage() {}

func (x *StoreGcStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_store_svc_g_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StoreGcStatusResponse) GetEnabled() bool {
	if x != nil {
		return x.xxx_hidden_Enabled
	}
	return false
}

func (x *StoreGcStatusResponse) GetRunning() bool {
	if x != nil {
		return x.xxx_hidden_Running
	}
	return false
}

func (x *StoreGcStatusResponse) GetStarted() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Started
	}
	return nil
}

func (x *StoreGcStatusResponse) GetLastRun() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastRun
	}
	return nil
}

func (x *StoreGcStatusResponse) GetNextWake() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_NextWake
	}
	return nil
}

func (x *StoreGcStatusResponse) GetGraceUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_GraceUntil
	}
	return nil
}

func (x *StoreGcStatusResponse) GetSchedule() *GcSchedule {
	if x != nil {
		return x.xxx_hidden_Schedule
	}
	return nil
}

func (x *StoreGcStatusResponse) GetRules() []*GcRule {
	if x != nil {
		if x.xxx_hidden_Rules != nil {
			return *x.xxx_hidden_Rules
		}
	}
	return nil
}

func (x *StoreGcStatusResponse) GetRecords() int32 {
	if x != nil {
		return x.xxx_hidden_Records
	}
	return 0
}

func (x *StoreGcStatusResponse) GetPins() int32 {
	if x != nil {
		return x.xxx_hidden_Pins
	}
	return 0
}

func (x *StoreGcStatusResponse) GetUntagged() int32 {
	if x != nil {
		return x.xxx_hidden_Untagged
	}
	return 0
}

func (x *StoreGcStatusResponse) GetUntaggedAfter() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_UntaggedAfter
	}
	return nil
}

func (x *StoreGcStatusResponse) GetWatcher() *GcWatcherStatus {
	if x != nil {
		return x.xxx_hidden_Watcher
	}
	return nil
}

func (x *StoreGcStatusResponse) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 13)
}

func (x *StoreGcStatusResponse) SetRunning(v bool) {
	x.xxx_hidden_Running = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 13)
}

func (x *StoreGcStatusResponse) SetStarted(v *timestamppb.Timestamp) {
	x.xxx_hidden_Started = v
}

func (x *StoreGcStatusResponse) SetLastRun(v *timestamppb.Timestamp) {
	x.xxx_hidden_LastRun = v
}

func (x *StoreGcStatusResponse) SetNextWake(v *timestamppb.Timestamp) {
	x.xxx_hidden_NextWake = v
}

func (x *StoreGcStatusResponse) SetGraceUntil(v *timestamppb.Timestamp) {
	x.xxx_hidden_GraceUntil = v
}

func (x *StoreGcStatusResponse) SetSchedule(v *GcSchedule) {
	x.xxx_hidden_Schedule = v
}

func (x *StoreGcStatusResponse) SetRules(v []*GcRule) {
	x.xxx_hidden_Rules = &v
}

func (x *StoreGcStatusResponse) SetRecords(v int32) {
	x.xxx_hidden_Records = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 13)
}

func (x *StoreGcStatusResponse) SetPins(v int32) {
	x.xxx_hidden_Pins = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 13)
}

func (x *StoreGcStatusResponse) SetUntagged(v int32) {
	x.xxx_hidden_Untagged = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 13)
}

func (x *StoreGcStatusResponse) SetUntaggedAfter(v *durationpb.Duration) {
	x.xxx_hidden_UntaggedAfter = v
}

func (x *StoreGcStatusResponse) SetWatcher(v *GcWatcherStatus) {
	x.xxx_hidden_Watcher = v
}

func (x *StoreGcStatusResponse) HasEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StoreGcStatusResponse) HasRunning() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StoreGcStatusResponse) HasStarted() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Started != nil
}

func (x *StoreGcStatusResponse) HasLastRun() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastRun != nil
}

func (x *StoreGcStatusResponse) HasNextWake() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_NextWake != nil
}

func (x *StoreGcStatusResponse) HasGraceUntil() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_GraceUntil != nil
}

func (x *StoreGcStatusResponse) HasSchedule() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Schedule != nil
}

func (x *StoreGcStatusResponse) HasRecords() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *StoreGcStatusResponse) HasPins() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *StoreGcStatusResponse) HasUntagged() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *StoreGcStatusResponse) HasUntaggedAfter() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UntaggedAfter != nil
}

func (x *StoreGcStatusResponse) HasWatcher() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Watcher != nil
}

func (x *StoreGcStatusResponse) ClearEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Enabled = false
}

func (x *StoreGcStatusResponse) ClearRunning() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Running = false
}

func (x *StoreGcStatusResponse) ClearStarted() {
	x.xxx_hidden_Started = nil
}

func (x *StoreGcStatusResponse) ClearLastRun() {
	x.xxx_hidden_LastRun = nil
}

func (x *StoreGcStatusResponse) ClearNextWake() {
	x.xxx_hidden_NextWake = nil
}

func (x *StoreGcStatusResponse) ClearGraceUntil() {
	x.xxx_hidden_GraceUntil = nil
}

func (x *StoreGcStatusResponse) ClearSchedule() {
	x.xxx_hidden_Schedule = nil
}

func (x *StoreGcStatusResponse) ClearRecords() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Records = 0
}

func (x *StoreGcStatusResponse) ClearPins() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_Pins = 0
}

func (x *StoreGcStatusResponse) ClearUntagged() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_Untagged = 0
}

func (x *StoreGcStatusResponse) ClearUntaggedAfter() {
	x.xxx_hidden_UntaggedAfter = nil
}

func (x *StoreGcStatusResponse) ClearWatcher() {
	x.xxx_hidden_Watcher = nil
}

type StoreGcStatusResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Scheduling is on for this store.
	Enabled *bool
	// A GC run is in flight right now.
	Running    *bool
	Started    *timestamppb.Timestamp
	LastRun    *timestamppb.Timestamp
	NextWake   *timestamppb.Timestamp
	GraceUntil *timestamppb.Timestamp
	// Effective scheduler settings.
	Schedule *GcSchedule
	// Configured retention rules.
	Rules []*GcRule
	// Tracked image records.
	Records *int32
	// Live pins.
	Pins *int32
	// Tracked untagged images (reap clocks running).
	Untagged *int32
	// Reap delay; absent when the reaper is off.
	UntaggedAfter *durationpb.Duration
	// Usage-event stream health.
	Watcher *GcWatcherStatus
}

func (b0 StoreGcStatusResponse_builder) Build() *StoreGcStatusResponse {
	m0 := &StoreGcStatusResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Enabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 13)
		x.xxx_hidden_Enabled = *b.Enabled
	}
	if b.Running != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 13)
		x.xxx_hidden_Running = *b.Running
	}
	x.xxx_hidden_Started = b.Started
	x.xxx_hidden_LastRun = b.LastRun
	x.xxx_hidden_NextWake = b.NextWake
	x.xxx_hidden_GraceUntil = b.GraceUntil
	x.xxx_hidden_Schedule = b.Schedule
	x.xxx_hidden_Rules = &b.Rules
	if b.Records != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 13)
		x.xxx_hidden_Records = *b.Records
	}
	if b.Pins != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 13)
		x.xxx_hidden_Pins = *b.Pins
	}
	if b.Untagged != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 13)
		x.xxx_hidden_Untagged = *b.Untagged
	}
	x.xxx_hidden_UntaggedAfter = b.UntaggedAfter
	x.xxx_hidden_Watcher = b.Watcher
	return m0
}

type StoreGcRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Store    *StoreRef              `protobuf:"bytes,1,opt,name=store"`
	xxx_hidden_Override *GcOverride            `protobuf:"bytes,2,opt,name=override"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StoreGcRequest) Reset() {
	*x = StoreGcRequest{}
	mi := &file_gantry_store_svc_g_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreGcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreGcRequest) ProtoMessage() {}

func (x *StoreGcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_store_svc_g_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StoreGcRequest) GetStore() *StoreRef {
	if x != nil {
		return x.xxx_hidden_Store
	}
	return nil
}

func (x *StoreGcRequest) GetOverride() *GcOverride {
	if x != nil {
		return x.xxx_hidden_Override
	}
	return nil
}

func (x *StoreGcRequest) SetStore(v *StoreRef) {
	x.xxx_hidden_Store = v
}

func (x *StoreGcRequest) SetOverride(v *GcOverride) {
	x.xxx_hidden_Override = v
}

func (x *StoreGcRequest) HasStore() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Store != nil
}

func (x *StoreGcRequest) HasOverride() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Override != nil
}

func (x *StoreGcRequest) ClearStore() {
	x.xxx_hidden_Store = nil
}

func (x *StoreGcRequest) ClearOverride() {
	x.xxx_hidden_Override = nil
}

type StoreGcRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Store to run GC against.
	Store *StoreRef
	// Optional one-shot policy override.
	Override *GcOverride
}

func (b0 StoreGcRequest_builder) Build() *StoreGcRequest {
	m0 := &StoreGcRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Store = b.Store
	x.xxx_hidden_Override = b.Override
	return m0
}

type StoreGcPlanResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Delete     *[]*GcCandidate        `protobuf:"bytes,1,rep,name=delete"`
	xxx_hidden_Keep       *[]*GcKept             `protobuf:"bytes,2,rep,name=keep"`
	xxx_hidden_NextAgeOut *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=next_age_out,json=nextAgeOut"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StoreGcPlanResponse) Reset() {
	*x = StoreGcPlanResponse{}
	mi := &file_gantry_store_svc_g_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreGcPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreGcPlanResponse) ProtoMessage() {}

func (x *StoreGcPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_store_svc_g_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StoreGcPlanResponse) GetDelete() []*GcCandidate {
	if x != nil {
		if x.xxx_hidden_Delete != nil {
			return *x.xxx_hidden_Delete
		}
	}
	return nil
}

func (x *StoreGcPlanResponse) GetKeep() []*GcKept {
	if x != nil {
		if x.xxx_hidden_Keep != nil {
			return *x.xxx_hidden_Keep
		}
	}
	return nil
}

func (x *StoreGcPlanResponse) GetNextAgeOut() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_NextAgeOut
	}
	return nil
}

func (x *StoreGcPlanResponse) SetDelete(v []*GcCandidate) {
	x.xxx_hidden_Delete = &v
}

func (x *StoreGcPlanResponse) SetKeep(v []*GcKept) {
	x.xxx_hidden_Keep = &v
}

func (x *StoreGcPlanResponse) SetNextAgeOut(v *timestamppb.Timestamp) {
	x.xxx_hidden_NextAgeOut = v
}

func (x *StoreGcPlanResponse) HasNextAgeOut() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_NextAgeOut != nil
}

func (x *StoreGcPlanResponse) ClearNextAgeOut() {
	x.xxx_hidden_NextAgeOut = nil
}

type StoreGcPlanResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Images that would be deleted.
	Delete []*GcCandidate
	// Records kept, and why.
	Keep []*GcKept
	// The soonest a currently-kept record could become age-deletable; absent
	// when nothing is on an age path.
	NextAgeOut *timestamppb.Timestamp
}

func (b0 StoreGcPlanResponse_builder) Build() *StoreGcPlanResponse {
	m0 := &StoreGcPlanResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Delete = &b.Delete
	x.xxx_hidden_Keep = &b.Keep
	x.xxx_hidden_NextAgeOut = b.NextAgeOut
	return m0
}

type StoreGcApplyResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Evaluated   int32                  `protobuf:"varint,1,opt,name=evaluated"`
	xxx_hidden_Untagged    []string               `protobuf:"bytes,2,rep,name=untagged"`
	xxx_hidden_Deleted     []string               `protobuf:"bytes,3,rep,name=deleted"`
	xxx_hidden_Reaped      []string               `protobuf:"bytes,4,rep,name=reaped"`
	xxx_hidden_Skipped     []string               `protobuf:"bytes,5,rep,name=skipped"`
	xxx_hidden_Errors      []string               `protobuf:"bytes,6,rep,name=errors"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StoreGcApplyResponse) Reset() {
	*x = StoreGcApplyResponse{}
	mi := &file_gantry_store_svc_g_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreGcApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreGcApplyResponse) ProtoMessage() {}

func (x *StoreGcApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_store_svc_g_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StoreGcApplyResponse) GetEvaluated() int32 {
	if x != nil {
		return x.xxx_hidden_Evaluated
	}
	return 0
}

func (x *StoreGcApplyResponse) GetUntagged() []string {
	if x != nil {
		return x.xxx_hidden_Untagged
	}
	return nil
}

func (x *StoreGcApplyResponse) GetDeleted() []string {
	if x != nil {
		return x.xxx_hidden_Deleted
	}
	return nil
}

func (x *StoreGcApplyResponse) GetReaped() []string {
	if x != nil {
		return x.xxx_hidden_Reaped
	}
	return nil
}

func (x *StoreGcApplyResponse) GetSkipped() []string {
	if x != nil {
		return x.xxx_hidden_Skipped
	}
	return nil
}

func (x *StoreGcApplyResponse) GetErrors() []string {
	if x != nil {
		return x.xxx_hidden_Errors
	}
	return nil
}

func (x *StoreGcApplyResponse) SetEvaluated(v int32) {
	x.xxx_hidden_Evaluated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *StoreGcApplyResponse) SetUntagged(v []string) {
	x.xxx_hidden_Untagged = v
}

func (x *StoreGcApplyResponse) SetDeleted(v []string) {
	x.xxx_hidden_Deleted = v
}

func (x *StoreGcApplyResponse) SetReaped(v []string) {
	x.xxx_hidden_Reaped = v
}

func (x *StoreGcApplyResponse) SetSkipped(v []string) {
	x.xxx_hidden_Skipped = v
}

func (x *StoreGcApplyResponse) SetErrors(v []string) {
	x.xxx_hidden_Errors = v
}

func (x *StoreGcApplyResponse) HasEvaluated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StoreGcApplyResponse) ClearEvaluated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Evaluated = 0
}

type StoreGcApplyResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Number of records considered (delete + keep).
	Evaluated *int32
	// Tag refs removed.
	Untagged []string
	// Content-hash IDs whose bytes were freed.
	Deleted []string
	// Untagged image IDs whose content was reaped.
	Reaped []string
	// Untagged image IDs not reapable right now (re-tagged, container ref,
	// in-flight pull).
	Skipped []string
	// Per-ref removal failures, "<ref>: <err>".
	Errors []string
}

func (b0 StoreGcApplyResponse_builder) Build() *StoreGcApplyResponse {
	m0 := &StoreGcApplyResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Evaluated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Evaluated = *b.Evaluated
	}
	x.xxx_hidden_Untagged = b.Untagged
	x.xxx_hidden_Deleted = b.Deleted
	x.xxx_hidden_Reaped = b.Reaped
	x.xxx_hidden_Skipped = b.Skipped
	x.xxx_hidden_Errors = b.Errors
	return m0
}

var File_gantry_store_svc_g_proto protoreflect.FileDescriptor

const file_gantry_store_svc_g_proto_rawDesc = "" +
	"\n" +
	"\x18gantry/store_svc.g.proto\x12\x06gantry\x1a\x0fgantry/gc.proto\x1a\x12gantry/store.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x02\n" +
	"\x0fStoreAddRequest\x12\x19\n" +
	"\x04name\x18\x01 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04name\x12,\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x11.gantry.StoreKindB\x05\xaa\x01\x02\b\x02R\x04kind\x12\x19\n" +
	"\x04host\x18\x03 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04host\x12,\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x11.gantry.StoreModeB\x05\xaa\x01\x02\b\x02R\x04mode\x12\x1f\n" +
	"\aaddress\x18\x05 \x01(\tB\x05\xaa\x01\x02\b\x02R\aaddress\x12#\n" +
	"\tnamespace\x18\x06 \x01(\tB\x05\xaa\x01\x02\b\x02R\tnamespace\x12\x1b\n" +
	"\x05ready\x18\a \x01(\bB\x05\xaa\x01\x02\b\x02R\x05ready\x12\x1b\n" +
	"\x05error\x18\b \x01(\tB\x05\xaa\x01\x02\b\x02R\x05error\x12=\n" +
	"\fcapabilities\x18\t \x01(\v2\x19.gantry.StoreCapabilitiesR\fcapabilities\"b\n" +
	"\x0fStoreGetRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.gantry.StoreRefR\x03ref\x12+\n" +
	"\x06select\x18\x02 \x01(\v2\x13.gantry.StoreSelectR\x06select\"'\n" +
	"\bStoreRef\x12\x14\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04nameB\x05\n" +
	"\x03key\"\xe3\x01\n" +
	"\vStoreSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\bR\x04kind\x12\x12\n" +
	"\x04host\x18\x03 \x01(\bR\x04host\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\bR\x04mode\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\bR\aaddress\x12\x1c\n" +
	"\tnamespace\x18\x06 \x01(\bR\tnamespace\x12\x14\n" +
	"\x05ready\x18\a \x01(\bR\x05ready\x12\x14\n" +
	"\x05error\x18\b \x01(\bR\x05error\x12\"\n" +
	"\fcapabilities\x18\t \x01(\bR\fcapabilities\"\xc2\x02\n" +
	"\x11StorePatchRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.gantry.StoreRefR\x03ref\x12\x12\n" +
	"\x04host\x18\x05 \x01(\tR\x04host\x12%\n" +
	"\x04mode\x18\a \x01(\x0e2\x11.gantry.StoreModeR\x04mode\x12\x18\n" +
	"\aaddress\x18\t \x01(\tR\aaddress\x12\x1c\n" +
	"\tnamespace\x18\v \x01(\tR\tnamespace\x12\x14\n" +
	"\x05ready\x18\r \x01(\bR\x05ready\x12\x14\n" +
	"\x05error\x18\x0f \x01(\tR\x05error\x12=\n" +
	"\fcapabilities\x18\x11 \x01(\v2\x19.gantry.StoreCapabilitiesR\fcapabilities\x12+\n" +
	"\x11capabilities_null\x18\x12 \x01(\bR\x10capabilitiesNull\"u\n" +
	"\x10StoreListRequest\x12%\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x11.gantry.StoreKindR\x04kind\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\v \x01(\tR\tpageToken\"`\n" +
	"\x11StoreListResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.gantry.StoreR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"h\n" +
	"\x10StorePullRequest\x12&\n" +
	"\x05store\x18\x01 \x01(\v2\x10.gantry.StoreRefR\x05store\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\"%\n" +
	"\x11StorePullResponse\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\"N\n" +
	"\x12StoreRemoveRequest\x12&\n" +
	"\x05store\x18\x01 \x01(\v2\x10.gantry.StoreRefR\x05store\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\"K\n" +
	"\x13StoreRemoveResponse\x12\x1a\n" +
	"\buntagged\x18\x01 \x03(\tR\buntagged\x12\x18\n" +
	"\adeleted\x18\x02 \x03(\tR\adeleted\"\xe2\x01\n" +
	"\x13StoreHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12%\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x11.gantry.StoreKindR\x04kind\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12=\n" +
	"\fdate_checked\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vdateChecked\x12\x16\n" +
	"\x06cached\x18\x06 \x01(\bR\x06cached\"\xc3\x04\n" +
	"\x15StoreGcStatusResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x18\n" +
	"\arunning\x18\x02 \x01(\bR\arunning\x124\n" +
	"\astarted\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\astarted\x125\n" +
	"\blast_run\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\alastRun\x127\n" +
	"\tnext_wake\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bnextWake\x12;\n" +
	"\vgrace_until\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"graceUntil\x12.\n" +
	"\bschedule\x18\a \x01(\v2\x12.gantry.GcScheduleR\bschedule\x12$\n" +
	"\x05rules\x18\b \x03(\v2\x0e.gantry.GcRuleR\x05rules\x12\x18\n" +
	"\arecords\x18\t \x01(\x05R\arecords\x12\x12\n" +
	"\x04pins\x18\n" +
	" \x01(\x05R\x04pins\x12\x1a\n" +
	"\buntagged\x18\v \x01(\x05R\buntagged\x12@\n" +
	"\x0euntagged_after\x18\f \x01(\v2\x19.google.protobuf.DurationR\runtaggedAfter\x121\n" +
	"\awatcher\x18\r \x01(\v2\x17.gantry.GcWatcherStatusR\awatcher\"h\n" +
	"\x0eStoreGcRequest\x12&\n" +
	"\x05store\x18\x01 \x01(\v2\x10.gantry.StoreRefR\x05store\x12.\n" +
	"\boverride\x18\x02 \x01(\v2\x12.gantry.GcOverrideR\boverride\"\xa4\x01\n" +
	"\x13StoreGcPlanResponse\x12+\n" +
	"\x06delete\x18\x01 \x03(\v2\x13.gantry.GcCandidateR\x06delete\x12\"\n" +
	"\x04keep\x18\x02 \x03(\v2\x0e.gantry.GcKeptR\x04keep\x12<\n" +
	"\fnext_age_out\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"nextAgeOut\"\xb4\x01\n" +
	"\x14StoreGcApplyResponse\x12\x1c\n" +
	"\tevaluated\x18\x01 \x01(\x05R\tevaluated\x12\x1a\n" +
	"\buntagged\x18\x02 \x03(\tR\buntagged\x12\x18\n" +
	"\adeleted\x18\x03 \x03(\tR\adeleted\x12\x16\n" +
	"\x06reaped\x18\x04 \x03(\tR\x06reaped\x12\x18\n" +
	"\askipped\x18\x05 \x03(\tR\askipped\x12\x16\n" +
	"\x06errors\x18\x06 \x03(\tR\x06errors2\x85\x05\n" +
	"\fStoreService\x12-\n" +
	"\x03Add\x12\x17.gantry.StoreAddRequest\x1a\r.gantry.Store\x12-\n" +
	"\x03Get\x12\x17.gantry.StoreGetRequest\x1a\r.gantry.Store\x121\n" +
	"\x05Patch\x12\x19.gantry.StorePatchRequest\x1a\r.gantry.Store\x121\n" +
	"\x05Erase\x12\x10.gantry.StoreRef\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\x04List\x12\x18.gantry.StoreListRequest\x1a\x19.gantry.StoreListResponse\x12;\n" +
	"\x04Pull\x12\x18.gantry.StorePullRequest\x1a\x19.gantry.StorePullResponse\x12A\n" +
	"\x06Remove\x12\x1a.gantry.StoreRemoveRequest\x1a\x1b.gantry.StoreRemoveResponse\x127\n" +
	"\x06Health\x12\x10.gantry.StoreRef\x1a\x1b.gantry.StoreHealthResponse\x12;\n" +
	"\bGcStatus\x12\x10.gantry.StoreRef\x1a\x1d.gantry.StoreGcStatusResponse\x12=\n" +
	"\x06GcPlan\x12\x16.gantry.StoreGcRequest\x1a\x1b.gantry.StoreGcPlanResponse\x12?\n" +
	"\aGcApply\x12\x16.gantry.StoreGcRequest\x1a\x1c.gantry.StoreGcApplyResponseB\x1fZ\x1dgithub.com/lesomnus/gantry/pbb\beditionsp\xe8\a"

var file_gantry_store_svc_g_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_gantry_store_svc_g_proto_goTypes = []any{
	(*StoreAddRequest)(nil),       // 0: gantry.StoreAddRequest
	(*StoreGetRequest)(nil),       // 1: gantry.StoreGetRequest
	(*StoreRef)(nil),              // 2: gantry.StoreRef
	(*StoreSelect)(nil),           // 3: gantry.StoreSelect
	(*StorePatchRequest)(nil),     // 4: gantry.StorePatchRequest
	(*StoreListRequest)(nil),      // 5: gantry.StoreListRequest
	(*StoreListResponse)(nil),     // 6: gantry.StoreListResponse
	(*StorePullRequest)(nil),      // 7: gantry.StorePullRequest
	(*StorePullResponse)(nil),     // 8: gantry.StorePullResponse
	(*StoreRemoveRequest)(nil),    // 9: gantry.StoreRemoveRequest
	(*StoreRemoveResponse)(nil),   // 10: gantry.StoreRemoveResponse
	(*StoreHealthResponse)(nil),   // 11: gantry.StoreHealthResponse
	(*StoreGcStatusResponse)(nil), // 12: gantry.StoreGcStatusResponse
	(*StoreGcRequest)(nil),        // 13: gantry.StoreGcRequest
	(*StoreGcPlanResponse)(nil),   // 14: gantry.StoreGcPlanResponse
	(*StoreGcApplyResponse)(nil),  // 15: gantry.StoreGcApplyResponse
	(StoreKind)(0),                // 16: gantry.StoreKind
	(StoreMode)(0),                // 17: gantry.StoreMode
	(*StoreCapabilities)(nil),     // 18: gantry.StoreCapabilities
	(*Store)(nil),                 // 19: gantry.Store
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
	(*GcSchedule)(nil),            // 21: gantry.GcSchedule
	(*GcRule)(nil),                // 22: gantry.GcRule
	(*durationpb.Duration)(nil),   // 23: google.protobuf.Duration
	(*GcWatcherStatus)(nil),       // 24: gantry.GcWatcherStatus
	(*GcOverride)(nil),            // 25: gantry.GcOverride
	(*GcCandidate)(nil),           // 26: gantry.GcCandidate
	(*GcKept)(nil),                // 27: gantry.GcKept
	(*emptypb.Empty)(nil),         // 28: google.protobuf.Empty
}
var file_gantry_store_svc_g_proto_depIdxs = []int32{
	16, // 0: gantry.StoreAddRequest.kind:type_name -> gantry.StoreKind
	17, // 1: gantry.StoreAddRequest.mode:type_name -> gantry.StoreMode
	18, // 2: gantry.StoreAddRequest.capabilities:type_name -> gantry.StoreCapabilities
	2,  // 3: gantry.StoreGetRequest.ref:type_name -> gantry.StoreRef
	3,  // 4: gantry.StoreGetRequest.select:type_name -> gantry.StoreSelect
	2,  // 5: gantry.StorePatchRequest.ref:type_name -> gantry.StoreRef
	17, // 6: gantry.StorePatchRequest.mode:type_name -> gantry.StoreMode
	18, // 7: gantry.StorePatchRequest.capabilities:type_name -> gantry.StoreCapabilities
	16, // 8: gantry.StoreListRequest.kind:type_name -> gantry.StoreKind
	19, // 9: gantry.StoreListResponse.items:type_name -> gantry.Store
	2,  // 10: gantry.StorePullRequest.store:type_name -> gantry.StoreRef
	2,  // 11: gantry.StoreRemoveRequest.store:type_name -> gantry.StoreRef
	16, // 12: gantry.StoreHealthResponse.kind:type_name -> gantry.StoreKind
	20, // 13: gantry.StoreHealthResponse.date_checked:type_name -> google.protobuf.Timestamp
	20, // 14: gantry.StoreGcStatusResponse.started:type_name -> google.protobuf.Timestamp
	20, // 15: gantry.StoreGcStatusResponse.last_run:type_name -> google.protobuf.Timestamp
	20, // 16: gantry.StoreGcStatusResponse.next_wake:type_name -> google.protobuf.Timestamp
	20, // 17: gantry.StoreGcStatusResponse.grace_until:type_name -> google.protobuf.Timestamp
	21, // 18: gantry.StoreGcStatusResponse.schedule:type_name -> gantry.GcSchedule
	22, // 19: gantry.StoreGcStatusResponse.rules:type_name -> gantry.GcRule
	23, // 20: gantry.StoreGcStatusResponse.untagged_after:type_name -> google.protobuf.Duration
	24, // 21: gantry.StoreGcStatusResponse.watcher:type_name -> gantry.GcWatcherStatus
	2,  // 22: gantry.StoreGcRequest.store:type_name -> gantry.StoreRef
	25, // 23: gantry.StoreGcRequest.override:type_name -> gantry.GcOverride
	26, // 24: gantry.StoreGcPlanResponse.delete:type_name -> gantry.GcCandidate
	27, // 25: gantry.StoreGcPlanResponse.keep:type_name -> gantry.GcKept
	20, // 26: gantry.StoreGcPlanResponse.next_age_out:type_name -> google.protobuf.Timestamp
	0,  // 27: gantry.StoreService.Add:input_type -> gantry.StoreAddRequest
	1,  // 28: gantry.StoreService.Get:input_type -> gantry.StoreGetRequest
	4,  // 29: gantry.StoreService.Patch:input_type -> gantry.StorePatchRequest
	2,  // 30: gantry.StoreService.Erase:input_type -> gantry.StoreRef
	5,  // 31: gantry.StoreService.List:input_type -> gantry.StoreListRequest
	7,  // 32: gantry.StoreService.Pull:input_type -> gantry.StorePullRequest
	9,  // 33: gantry.StoreService.Remove:input_type -> gantry.StoreRemoveRequest
	2,  // 34: gantry.StoreService.Health:input_type -> gantry.StoreRef
	2,  // 35: gantry.StoreService.GcStatus:input_type -> gantry.StoreRef
	13, // 36: gantry.StoreService.GcPlan:input_type -> gantry.StoreGcRequest
	13, // 37: gantry.StoreService.GcApply:input_type -> gantry.StoreGcRequest
	19, // 38: gantry.StoreService.Add:output_type -> gantry.Store
	19, // 39: gantry.StoreService.Get:output_type -> gantry.Store
	19, // 40: gantry.StoreService.Patch:output_type -> gantry.Store
	28, // 41: gantry.StoreService.Erase:output_type -> google.protobuf.Empty
	6,  // 42: gantry.StoreService.List:output_type -> gantry.StoreListResponse
	8,  // 43: gantry.StoreService.Pull:output_type -> gantry.StorePullResponse
	10, // 44: gantry.StoreService.Remove:output_type -> gantry.StoreRemoveResponse
	11, // 45: gantry.StoreService.Health:output_type -> gantry.StoreHealthResponse
	12, // 46: gantry.StoreService.GcStatus:output_type -> gantry.StoreGcStatusResponse
	14, // 47: gantry.StoreService.GcPlan:output_type -> gantry.StoreGcPlanResponse
	15, // 48: gantry.StoreService.GcApply:output_type -> gantry.StoreGcApplyResponse
	38, // [38:49] is the sub-list for method output_type
	27, // [27:38] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_gantry_store_svc_g_proto_init() }
func file_gantry_store_svc_g_proto_init() {
	if File_gantry_store_svc_g_proto != nil {
		return
	}
	file_gantry_gc_proto_init()
	file_gantry_store_proto_init()
	file_gantry_store_svc_g_proto_msgTypes[2].OneofWrappers = []any{
		(*storeRef_Name)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gantry_store_svc_g_proto_rawDesc), len(file_gantry_store_svc_g_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gantry_store_svc_g_proto_goTypes,
		DependencyIndexes: file_gantry_store_svc_g_proto_depIdxs,
		MessageInfos:      file_gantry_store_svc_g_proto_msgTypes,
	}.Build()
	File_gantry_store_svc_g_proto = out.File
	file_gantry_store_svc_g_proto_goTypes = nil
	file_gantry_store_svc_g_proto_depIdxs = nil
}
