// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: gantry/store_svc.g.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreAddRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name         string                 `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Kind         StoreKind              `protobuf:"varint,2,opt,name=kind,enum=gantry.StoreKind"`
	xxx_hidden_Host         string                 `protobuf:"bytes,3,opt,name=host"`
	xxx_hidden_Mode         StoreMode              `protobuf:"varint,4,opt,name=mode,enum=gantry.StoreMode"`
	xxx_hidden_Address      string                 `protobuf:"bytes,5,opt,name=address"`
	xxx_hidden_Namespace    string                 `protobuf:"bytes,6,opt,name=namespace"`
	xxx_hidden_Ready        bool                   `protobuf:"varint,7,opt,name=ready"`
	xxx_hidden_Error        string                 `protobuf:"bytes,8,opt,name=error"`
	xxx_hidden_Capabilities *StoreCapabilities     `protobuf:"bytes,9,opt,name=capabilities"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *StoreAddRequest) Reset() {
	*x = StoreAddRequest{}
	mi := &file_gantry_store_svc_g_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreAddRequest) ProtoMessage() {}

func (x *StoreAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_store_svc_g_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StoreAddRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *StoreAddRequest) GetKind() StoreKind {
	if x != nil {
		return x.xxx_hidden_Kind
	}
	return StoreKind_STORE_KIND_UNSPECIFIED
}

func (x *StoreAddRequest) GetHost() string {
	if x != nil {
		return x.xxx_hidden_Host
	}
	return ""
}

func (x *StoreAddRequest) GetMode() StoreMode {
	if x != nil {
		return x.xxx_hidden_Mode
	}
	return StoreMode_STORE_MODE_UNSPECIFIED
}

func (x *StoreAddRequest) GetAddress() string {
	if x != nil {
		return x.xxx_hidden_Address
	}
	return ""
}

func (x *StoreAddRequest) GetNamespace() string {
	if x != nil {
		return x.xxx_hidden_Namespace
	}
	return ""
}

func (x *StoreAddRequest) GetReady() bool {
	if x != nil {
		return x.xxx_hidden_Ready
	}
	return false
}

func (x *StoreAddRequest) GetError() string {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return ""
}

func (x *StoreAddRequest) GetCapabilities() *StoreCapabilities {
	if x != nil {
		return x.xxx_hidden_Capabilities
	}
	return nil
}

func (x *StoreAddRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *StoreAddRequest) SetKind(v StoreKind) {
	x.xxx_hidden_Kind = v
}

func (x *StoreAddRequest) SetHost(v string) {
	x.xxx_hidden_Host = v
}

func (x *StoreAddRequest) SetMode(v StoreMode) {
	x.xxx_hidden_Mode = v
}

func (x *StoreAddRequest) SetAddress(v string) {
	x.xxx_hidden_Address = v
}

func (x *StoreAddRequest) SetNamespace(v string) {
	x.xxx_hidden_Namespace = v
}

func (x *StoreAddRequest) SetReady(v bool) {
	x.xxx_hidden_Ready = v
}

func (x *StoreAddRequest) SetError(v string) {
	x.xxx_hidden_Error = v
}

func (x *StoreAddRequest) SetCapabilities(v *StoreCapabilities) {
	x.xxx_hidden_Capabilities = v
}

func (x *StoreAddRequest) HasCapabilities() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Capabilities != nil
}

func (x *StoreAddRequest) ClearCapabilities() {
	x.xxx_hidden_Capabilities = nil
}

type StoreAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name         string
	Kind         StoreKind
	Host         string
	Mode         StoreMode
	Address      string
	Namespace    string
	Ready        bool
	Error        string
	Capabilities *StoreCapabilities
}

func (b0 StoreAddRequest_builder) Build() *StoreAddRequest {
	m0 := &StoreAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Kind = b.Kind
	x.xxx_hidden_Host = b.Host
	x.xxx_hidden_Mode = b.Mode
	x.xxx_hidden_Address = b.Address
	x.xxx_hidden_Namespace = b.Namespace
	x.xxx_hidden_Ready = b.Ready
	x.xxx_hidden_Error = b.Error
	x.xxx_hidden_Capabilities = b.Capabilities
	return m0
}

type StoreGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *StoreRef              `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *StoreSelect           `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StoreGetRequest) Reset() {
	*x = StoreGetRequest{}
	mi := &file_gantry_store_svc_g_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreGetRequest) ProtoMessage() {}

func (x *StoreGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_store_svc_g_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StoreGetRequest) GetRef() *StoreRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *StoreGetRequest) GetSelect() *StoreSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *StoreGetRequest) SetRef(v *StoreRef) {
	x.xxx_hidden_Ref = v
}

func (x *StoreGetRequest) SetSelect(v *StoreSelect) {
	x.xxx_hidden_Select = v
}

func (x *StoreGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *StoreGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *StoreGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *StoreGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type StoreGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *StoreRef
	Select *StoreSelect
}

func (b0 StoreGetRequest_builder) Build() *StoreGetRequest {
	m0 := &StoreGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type StoreRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isStoreRef_Key         `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StoreRef) Reset() {
	*x = StoreRef{}
	mi := &file_gantry_store_svc_g_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRef) ProtoMessage() {}

func (x *StoreRef) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_store_svc_g_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StoreRef) GetName() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*storeRef_Name); ok {
			return x.Name
		}
	}
	return ""
}

func (x *StoreRef) SetName(v string) {
	x.xxx_hidden_Key = &storeRef_Name{v}
}

func (x *StoreRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *StoreRef) HasName() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*storeRef_Name)
	return ok
}

func (x *StoreRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *StoreRef) ClearName() {
	if _, ok := x.xxx_hidden_Key.(*storeRef_Name); ok {
		x.xxx_hidden_Key = nil
	}
}

const StoreRef_Key_not_set_case case_StoreRef_Key = 0
const StoreRef_Name_case case_StoreRef_Key = 1

func (x *StoreRef) WhichKey() case_StoreRef_Key {
	if x == nil {
		return StoreRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *storeRef_Name:
		return StoreRef_Name_case
	default:
		return StoreRef_Key_not_set_case
	}
}

type StoreRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Name *string
	// -- end of xxx_hidden_Key
}

func (b0 StoreRef_builder) Build() *StoreRef {
	m0 := &StoreRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		x.xxx_hidden_Key = &storeRef_Name{*b.Name}
	}
	return m0
}

type case_StoreRef_Key protoreflect.FieldNumber

func (x case_StoreRef_Key) String() string {
	md := file_gantry_store_svc_g_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isStoreRef_Key interface {
	isStoreRef_Key()
}

type storeRef_Name struct {
	Name string `protobuf:"bytes,1,opt,name=name,oneof"`
}

func (*storeRef_Name) isStoreRef_Key() {}

type StoreSelect struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All          bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_Kind         bool                   `protobuf:"varint,2,opt,name=kind"`
	xxx_hidden_Host         bool                   `protobuf:"varint,3,opt,name=host"`
	xxx_hidden_Mode         bool                   `protobuf:"varint,4,opt,name=mode"`
	xxx_hidden_Address      bool                   `protobuf:"varint,5,opt,name=address"`
	xxx_hidden_Namespace    bool                   `protobuf:"varint,6,opt,name=namespace"`
	xxx_hidden_Ready        bool                   `protobuf:"varint,7,opt,name=ready"`
	xxx_hidden_Error        bool                   `protobuf:"varint,8,opt,name=error"`
	xxx_hidden_Capabilities bool                   `protobuf:"varint,9,opt,name=capabilities"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *StoreSelect) Reset() {
	*x = StoreSelect{}
	mi := &file_gantry_store_svc_g_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreSelect) ProtoMessage() {}

func (x *StoreSelect) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_store_svc_g_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StoreSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *StoreSelect) GetKind() bool {
	if x != nil {
		return x.xxx_hidden_Kind
	}
	return false
}

func (x *StoreSelect) GetHost() bool {
	if x != nil {
		return x.xxx_hidden_Host
	}
	return false
}

func (x *StoreSelect) GetMode() bool {
	if x != nil {
		return x.xxx_hidden_Mode
	}
	return false
}

func (x *StoreSelect) GetAddress() bool {
	if x != nil {
		return x.xxx_hidden_Address
	}
	return false
}

func (x *StoreSelect) GetNamespace() bool {
	if x != nil {
		return x.xxx_hidden_Namespace
	}
	return false
}

func (x *StoreSelect) GetReady() bool {
	if x != nil {
		return x.xxx_hidden_Ready
	}
	return false
}

func (x *StoreSelect) GetError() bool {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return false
}

func (x *StoreSelect) GetCapabilities() bool {
	if x != nil {
		return x.xxx_hidden_Capabilities
	}
	return false
}

func (x *StoreSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 9)
}

func (x *StoreSelect) SetKind(v bool) {
	x.xxx_hidden_Kind = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *StoreSelect) SetHost(v bool) {
	x.xxx_hidden_Host = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *StoreSelect) SetMode(v bool) {
	x.xxx_hidden_Mode = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 9)
}

func (x *StoreSelect) SetAddress(v bool) {
	x.xxx_hidden_Address = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *StoreSelect) SetNamespace(v bool) {
	x.xxx_hidden_Namespace = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *StoreSelect) SetReady(v bool) {
	x.xxx_hidden_Ready = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *StoreSelect) SetError(v bool) {
	x.xxx_hidden_Error = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 9)
}

func (x *StoreSelect) SetCapabilities(v bool) {
	x.xxx_hidden_Capabilities = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 9)
}

func (x *StoreSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StoreSelect) HasKind() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StoreSelect) HasHost() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *StoreSelect) HasMode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *StoreSelect) HasAddress() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *StoreSelect) HasNamespace() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *StoreSelect) HasReady() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *StoreSelect) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *StoreSelect) HasCapabilities() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *StoreSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *StoreSelect) ClearKind() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Kind = false
}

func (x *StoreSelect) ClearHost() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Host = false
}

func (x *StoreSelect) ClearMode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Mode = false
}

func (x *StoreSelect) ClearAddress() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Address = false
}

func (x *StoreSelect) ClearNamespace() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Namespace = false
}

func (x *StoreSelect) ClearReady() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Ready = false
}

func (x *StoreSelect) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Error = false
}

func (x *StoreSelect) ClearCapabilities() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Capabilities = false
}

type StoreSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All          *bool
	Kind         *bool
	Host         *bool
	Mode         *bool
	Address      *bool
	Namespace    *bool
	Ready        *bool
	Error        *bool
	Capabilities *bool
}

func (b0 StoreSelect_builder) Build() *StoreSelect {
	m0 := &StoreSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 9)
		x.xxx_hidden_All = *b.All
	}
	if b.Kind != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_Kind = *b.Kind
	}
	if b.Host != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_Host = *b.Host
	}
	if b.Mode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 9)
		x.xxx_hidden_Mode = *b.Mode
	}
	if b.Address != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_Address = *b.Address
	}
	if b.Namespace != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_Namespace = *b.Namespace
	}
	if b.Ready != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_Ready = *b.Ready
	}
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 9)
		x.xxx_hidden_Error = *b.Error
	}
	if b.Capabilities != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 9)
		x.xxx_hidden_Capabilities = *b.Capabilities
	}
	return m0
}

type StorePatchRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref              *StoreRef              `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Host             *string                `protobuf:"bytes,5,opt,name=host"`
	xxx_hidden_Mode             StoreMode              `protobuf:"varint,7,opt,name=mode,enum=gantry.StoreMode"`
	xxx_hidden_Address          *string                `protobuf:"bytes,9,opt,name=address"`
	xxx_hidden_Namespace        *string                `protobuf:"bytes,11,opt,name=namespace"`
	xxx_hidden_Ready            bool                   `protobuf:"varint,13,opt,name=ready"`
	xxx_hidden_Error            *string                `protobuf:"bytes,15,opt,name=error"`
	xxx_hidden_Capabilities     *StoreCapabilities     `protobuf:"bytes,17,opt,name=capabilities"`
	xxx_hidden_CapabilitiesNull bool                   `protobuf:"varint,18,opt,name=capabilities_null,json=capabilitiesNull"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *StorePatchRequest) Reset() {
	*x = StorePatchRequest{}
	mi := &file_gantry_store_svc_g_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorePatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorePatchRequest) ProtoMessage() {}

func (x *StorePatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_store_svc_g_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StorePatchRequest) GetRef() *StoreRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *StorePatchRequest) GetHost() string {
	if x != nil {
		if x.xxx_hidden_Host != nil {
			return *x.xxx_hidden_Host
		}
		return ""
	}
	return ""
}

func (x *StorePatchRequest) GetMode() StoreMode {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Mode
		}
	}
	return StoreMode_STORE_MODE_UNSPECIFIED
}

func (x *StorePatchRequest) GetAddress() string {
	if x != nil {
		if x.xxx_hidden_Address != nil {
			return *x.xxx_hidden_Address
		}
		return ""
	}
	return ""
}

func (x *StorePatchRequest) GetNamespace() string {
	if x != nil {
		if x.xxx_hidden_Namespace != nil {
			return *x.xxx_hidden_Namespace
		}
		return ""
	}
	return ""
}

func (x *StorePatchRequest) GetReady() bool {
	if x != nil {
		return x.xxx_hidden_Ready
	}
	return false
}

func (x *StorePatchRequest) GetError() string {
	if x != nil {
		if x.xxx_hidden_Error != nil {
			return *x.xxx_hidden_Error
		}
		return ""
	}
	return ""
}

func (x *StorePatchRequest) GetCapabilities() *StoreCapabilities {
	if x != nil {
		return x.xxx_hidden_Capabilities
	}
	return nil
}

func (x *StorePatchRequest) GetCapabilitiesNull() bool {
	if x != nil {
		return x.xxx_hidden_CapabilitiesNull
	}
	return false
}

func (x *StorePatchRequest) SetRef(v *StoreRef) {
	x.xxx_hidden_Ref = v
}

func (x *StorePatchRequest) SetHost(v string) {
	x.xxx_hidden_Host = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *StorePatchRequest) SetMode(v StoreMode) {
	x.xxx_hidden_Mode = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *StorePatchRequest) SetAddress(v string) {
	x.xxx_hidden_Address = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 9)
}

func (x *StorePatchRequest) SetNamespace(v string) {
	x.xxx_hidden_Namespace = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *StorePatchRequest) SetReady(v bool) {
	x.xxx_hidden_Ready = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *StorePatchRequest) SetError(v string) {
	x.xxx_hidden_Error = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *StorePatchRequest) SetCapabilities(v *StoreCapabilities) {
	x.xxx_hidden_Capabilities = v
}

func (x *StorePatchRequest) SetCapabilitiesNull(v bool) {
	x.xxx_hidden_CapabilitiesNull = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 9)
}

func (x *StorePatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *StorePatchRequest) HasHost() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StorePatchRequest) HasMode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *StorePatchRequest) HasAddress() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *StorePatchRequest) HasNamespace() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *StorePatchRequest) HasReady() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *StorePatchRequest) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *StorePatchRequest) HasCapabilities() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Capabilities != nil
}

func (x *StorePatchRequest) HasCapabilitiesNull() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *StorePatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *StorePatchRequest) ClearHost() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Host = nil
}

func (x *StorePatchRequest) ClearMode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Mode = StoreMode_STORE_MODE_UNSPECIFIED
}

func (x *StorePatchRequest) ClearAddress() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Address = nil
}

func (x *StorePatchRequest) ClearNamespace() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Namespace = nil
}

func (x *StorePatchRequest) ClearReady() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Ready = false
}

func (x *StorePatchRequest) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Error = nil
}

func (x *StorePatchRequest) ClearCapabilities() {
	x.xxx_hidden_Capabilities = nil
}

func (x *StorePatchRequest) ClearCapabilitiesNull() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_CapabilitiesNull = false
}

type StorePatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref              *StoreRef
	Host             *string
	Mode             *StoreMode
	Address          *string
	Namespace        *string
	Ready            *bool
	Error            *string
	Capabilities     *StoreCapabilities
	CapabilitiesNull *bool
}

func (b0 StorePatchRequest_builder) Build() *StorePatchRequest {
	m0 := &StorePatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	if b.Host != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_Host = b.Host
	}
	if b.Mode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_Mode = *b.Mode
	}
	if b.Address != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 9)
		x.xxx_hidden_Address = b.Address
	}
	if b.Namespace != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_Namespace = b.Namespace
	}
	if b.Ready != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_Ready = *b.Ready
	}
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_Error = b.Error
	}
	x.xxx_hidden_Capabilities = b.Capabilities
	if b.CapabilitiesNull != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 9)
		x.xxx_hidden_CapabilitiesNull = *b.CapabilitiesNull
	}
	return m0
}

type StoreListRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Kind        StoreKind              `protobuf:"varint,1,opt,name=kind,enum=gantry.StoreKind"`
	xxx_hidden_PageSize    int32                  `protobuf:"varint,10,opt,name=page_size,json=pageSize"`
	xxx_hidden_PageToken   *string                `protobuf:"bytes,11,opt,name=page_token,json=pageToken"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StoreListRequest) Reset() {
	*x = StoreListRequest{}
	mi := &file_gantry_store_svc_g_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreListRequest) ProtoMessage() {}

func (x *StoreListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_store_svc_g_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StoreListRequest) GetKind() StoreKind {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Kind
		}
	}
	return StoreKind_STORE_KIND_UNSPECIFIED
}

func (x *StoreListRequest) GetPageSize() int32 {
	if x != nil {
		return x.xxx_hidden_PageSize
	}
	return 0
}

func (x *StoreListRequest) GetPageToken() string {
	if x != nil {
		if x.xxx_hidden_PageToken != nil {
			return *x.xxx_hidden_PageToken
		}
		return ""
	}
	return ""
}

func (x *StoreListRequest) SetKind(v StoreKind) {
	x.xxx_hidden_Kind = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *StoreListRequest) SetPageSize(v int32) {
	x.xxx_hidden_PageSize = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *StoreListRequest) SetPageToken(v string) {
	x.xxx_hidden_PageToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *StoreListRequest) HasKind() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StoreListRequest) HasPageSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StoreListRequest) HasPageToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *StoreListRequest) ClearKind() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Kind = StoreKind_STORE_KIND_UNSPECIFIED
}

func (x *StoreListRequest) ClearPageSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PageSize = 0
}

func (x *StoreListRequest) ClearPageToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_PageToken = nil
}

type StoreListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Kind      *StoreKind
	PageSize  *int32
	PageToken *string
}

func (b0 StoreListRequest_builder) Build() *StoreListRequest {
	m0 := &StoreListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Kind != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Kind = *b.Kind
	}
	if b.PageSize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_PageSize = *b.PageSize
	}
	if b.PageToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_PageToken = b.PageToken
	}
	return m0
}

type StoreListResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items         *[]*Store              `protobuf:"bytes,1,rep,name=items"`
	xxx_hidden_NextPageToken *string                `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *StoreListResponse) Reset() {
	*x = StoreListResponse{}
	mi := &file_gantry_store_svc_g_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreListResponse) ProtoMessage() {}

func (x *StoreListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_store_svc_g_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StoreListResponse) GetItems() []*Store {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *StoreListResponse) GetNextPageToken() string {
	if x != nil {
		if x.xxx_hidden_NextPageToken != nil {
			return *x.xxx_hidden_NextPageToken
		}
		return ""
	}
	return ""
}

func (x *StoreListResponse) SetItems(v []*Store) {
	x.xxx_hidden_Items = &v
}

func (x *StoreListResponse) SetNextPageToken(v string) {
	x.xxx_hidden_NextPageToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *StoreListResponse) HasNextPageToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StoreListResponse) ClearNextPageToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NextPageToken = nil
}

type StoreListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items         []*Store
	NextPageToken *string
}

func (b0 StoreListResponse_builder) Build() *StoreListResponse {
	m0 := &StoreListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	if b.NextPageToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_NextPageToken = b.NextPageToken
	}
	return m0
}

var File_gantry_store_svc_g_proto protoreflect.FileDescriptor

const file_gantry_store_svc_g_proto_rawDesc = "" +
	"\n" +
	"\x18gantry/store_svc.g.proto\x12\x06gantry\x1a\x12gantry/store.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xe2\x02\n" +
	"\x0fStoreAddRequest\x12\x19\n" +
	"\x04name\x18\x01 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04name\x12,\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x11.gantry.StoreKindB\x05\xaa\x01\x02\b\x02R\x04kind\x12\x19\n" +
	"\x04host\x18\x03 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04host\x12,\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x11.gantry.StoreModeB\x05\xaa\x01\x02\b\x02R\x04mode\x12\x1f\n" +
	"\aaddress\x18\x05 \x01(\tB\x05\xaa\x01\x02\b\x02R\aaddress\x12#\n" +
	"\tnamespace\x18\x06 \x01(\tB\x05\xaa\x01\x02\b\x02R\tnamespace\x12\x1b\n" +
	"\x05ready\x18\a \x01(\bB\x05\xaa\x01\x02\b\x02R\x05ready\x12\x1b\n" +
	"\x05error\x18\b \x01(\tB\x05\xaa\x01\x02\b\x02R\x05error\x12=\n" +
	"\fcapabilities\x18\t \x01(\v2\x19.gantry.StoreCapabilitiesR\fcapabilities\"b\n" +
	"\x0fStoreGetRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.gantry.StoreRefR\x03ref\x12+\n" +
	"\x06select\x18\x02 \x01(\v2\x13.gantry.StoreSelectR\x06select\"'\n" +
	"\bStoreRef\x12\x14\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04nameB\x05\n" +
	"\x03key\"\xe3\x01\n" +
	"\vStoreSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\bR\x04kind\x12\x12\n" +
	"\x04host\x18\x03 \x01(\bR\x04host\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\bR\x04mode\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\bR\aaddress\x12\x1c\n" +
	"\tnamespace\x18\x06 \x01(\bR\tnamespace\x12\x14\n" +
	"\x05ready\x18\a \x01(\bR\x05ready\x12\x14\n" +
	"\x05error\x18\b \x01(\bR\x05error\x12\"\n" +
	"\fcapabilities\x18\t \x01(\bR\fcapabilities\"\xc2\x02\n" +
	"\x11StorePatchRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.gantry.StoreRefR\x03ref\x12\x12\n" +
	"\x04host\x18\x05 \x01(\tR\x04host\x12%\n" +
	"\x04mode\x18\a \x01(\x0e2\x11.gantry.StoreModeR\x04mode\x12\x18\n" +
	"\aaddress\x18\t \x01(\tR\aaddress\x12\x1c\n" +
	"\tnamespace\x18\v \x01(\tR\tnamespace\x12\x14\n" +
	"\x05ready\x18\r \x01(\bR\x05ready\x12\x14\n" +
	"\x05error\x18\x0f \x01(\tR\x05error\x12=\n" +
	"\fcapabilities\x18\x11 \x01(\v2\x19.gantry.StoreCapabilitiesR\fcapabilities\x12+\n" +
	"\x11capabilities_null\x18\x12 \x01(\bR\x10capabilitiesNull\"u\n" +
	"\x10StoreListRequest\x12%\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x11.gantry.StoreKindR\x04kind\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\v \x01(\tR\tpageToken\"`\n" +
	"\x11StoreListResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.gantry.StoreR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\x8f\x02\n" +
	"\fStoreService\x12-\n" +
	"\x03Add\x12\x17.gantry.StoreAddRequest\x1a\r.gantry.Store\x12-\n" +
	"\x03Get\x12\x17.gantry.StoreGetRequest\x1a\r.gantry.Store\x121\n" +
	"\x05Patch\x12\x19.gantry.StorePatchRequest\x1a\r.gantry.Store\x121\n" +
	"\x05Erase\x12\x10.gantry.StoreRef\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\x04List\x12\x18.gantry.StoreListRequest\x1a\x19.gantry.StoreListResponseB\x1fZ\x1dgithub.com/lesomnus/gantry/pbb\beditionsp\xe8\a"

var file_gantry_store_svc_g_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gantry_store_svc_g_proto_goTypes = []any{
	(*StoreAddRequest)(nil),   // 0: gantry.StoreAddRequest
	(*StoreGetRequest)(nil),   // 1: gantry.StoreGetRequest
	(*StoreRef)(nil),          // 2: gantry.StoreRef
	(*StoreSelect)(nil),       // 3: gantry.StoreSelect
	(*StorePatchRequest)(nil), // 4: gantry.StorePatchRequest
	(*StoreListRequest)(nil),  // 5: gantry.StoreListRequest
	(*StoreListResponse)(nil), // 6: gantry.StoreListResponse
	(StoreKind)(0),            // 7: gantry.StoreKind
	(StoreMode)(0),            // 8: gantry.StoreMode
	(*StoreCapabilities)(nil), // 9: gantry.StoreCapabilities
	(*Store)(nil),             // 10: gantry.Store
	(*emptypb.Empty)(nil),     // 11: google.protobuf.Empty
}
var file_gantry_store_svc_g_proto_depIdxs = []int32{
	7,  // 0: gantry.StoreAddRequest.kind:type_name -> gantry.StoreKind
	8,  // 1: gantry.StoreAddRequest.mode:type_name -> gantry.StoreMode
	9,  // 2: gantry.StoreAddRequest.capabilities:type_name -> gantry.StoreCapabilities
	2,  // 3: gantry.StoreGetRequest.ref:type_name -> gantry.StoreRef
	3,  // 4: gantry.StoreGetRequest.select:type_name -> gantry.StoreSelect
	2,  // 5: gantry.StorePatchRequest.ref:type_name -> gantry.StoreRef
	8,  // 6: gantry.StorePatchRequest.mode:type_name -> gantry.StoreMode
	9,  // 7: gantry.StorePatchRequest.capabilities:type_name -> gantry.StoreCapabilities
	7,  // 8: gantry.StoreListRequest.kind:type_name -> gantry.StoreKind
	10, // 9: gantry.StoreListResponse.items:type_name -> gantry.Store
	0,  // 10: gantry.StoreService.Add:input_type -> gantry.StoreAddRequest
	1,  // 11: gantry.StoreService.Get:input_type -> gantry.StoreGetRequest
	4,  // 12: gantry.StoreService.Patch:input_type -> gantry.StorePatchRequest
	2,  // 13: gantry.StoreService.Erase:input_type -> gantry.StoreRef
	5,  // 14: gantry.StoreService.List:input_type -> gantry.StoreListRequest
	10, // 15: gantry.StoreService.Add:output_type -> gantry.Store
	10, // 16: gantry.StoreService.Get:output_type -> gantry.Store
	10, // 17: gantry.StoreService.Patch:output_type -> gantry.Store
	11, // 18: gantry.StoreService.Erase:output_type -> google.protobuf.Empty
	6,  // 19: gantry.StoreService.List:output_type -> gantry.StoreListResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_gantry_store_svc_g_proto_init() }
func file_gantry_store_svc_g_proto_init() {
	if File_gantry_store_svc_g_proto != nil {
		return
	}
	file_gantry_store_proto_init()
	file_gantry_store_svc_g_proto_msgTypes[2].OneofWrappers = []any{
		(*storeRef_Name)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gantry_store_svc_g_proto_rawDesc), len(file_gantry_store_svc_g_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gantry_store_svc_g_proto_goTypes,
		DependencyIndexes: file_gantry_store_svc_g_proto_depIdxs,
		MessageInfos:      file_gantry_store_svc_g_proto_msgTypes,
	}.Build()
	File_gantry_store_svc_g_proto = out.File
	file_gantry_store_svc_g_proto_goTypes = nil
	file_gantry_store_svc_g_proto_depIdxs = nil
}
